glide.lock, glide.yaml
* Remove a bunch of unused dependencies (aws, coreos, etc...)
* Rename the package to match the full name; i.e. github.com/jlewi/mlkube.io
=> Update glide config.

README.md, tf-job-operator-chart/templates/rbac.yaml
added missing required cluster roles (batch.jobs and extensions.deployments)
=> Updated chart with batch.jobs and extensions.deployments cluster roles

test-infra/image/bootstrap.py
Change bootstrap.py to fix the periodic test.
* For periodic test REPO_OWNER and REPO_NAME won't be set so we
need to hard code the value.
=> Fix periodic test

test-infra/runner.py
Write a json file to GCS with the results of the test on success. 
This way we can keep track of the latest green results.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jlewi/mlkube.io/66)
=> Record latest green from postsubmit

test-infra/runner.py
* GCS location needs to include github organization and name.
* Fixes #62
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jlewi/mlkube.io/74)
=> Fix location of the post submit results.

images/tf_operator/build_and_push.py
=> Tag docker images with "latest".

developer_guide.md, pkg/controller/controller.go
This PR will fix typo and remove some redundancy code.
@jlewi PTAL.
=> Minor fix typo and redundancy

pkg/util/k8sutil/tpr_util.go
Fix https://github.com/tensorflow/k8s/issues/130.
@jlewi PTAL.
=> Remove trailing slash of host

test/e2e/main.go
=> fix a log issue

pkg/controller/controller.go
This is a bad name from etcd-operator
=> rename clus to tfjob in controller.go

cmd/tf_operator/main.go, developer_guide.md, pkg/util/k8sutil/k8sutil.go, pkg/util/k8sutil/tpr_util.go
rename InClusterConfig() to GetClusterConfig(), remove todo
also use env var KUBECONFIG to retrieve kubeconfig (same as kubectl)
=> rename InClusterConfig() to GetClusterConfig()

pkg/util/k8sutil/fake/fake.go, pkg/util/k8sutil/tf_job_client.go
rename tpr_util.go to tf_job_client.go
same as pr #140 , based on new master branch
=> add Create(), Delete() in TfJobClient interface

pkg/trainer/replicas.go, pkg/trainer/replicas_test.go, pkg/trainer/tensorboard.go, pkg/trainer/tensorboard_test.go, pkg/trainer/training_test.go, test/e2e/main.go
same as pr#139, truncate jobname to 16 characters, based on new master branch
=> change jobname from task-runtimeid-index to jobname-task-runtimeid-index

test-infra/airflow/Dockerfile.prow, test-infra/airflow/deployment.yaml
* This should hopefully fix the presubmits #196.
=> Update the Airflow deployment to use Docker images built from a clean tree

README.md
=> minor spelling porxy => proxy

developer_guide.md
Update developer guide to include launching local operator with required config.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/k8s/216)
=> update developer guide

examples/tf_job_gpu.yaml, py/deploy.py, py/tf_job_client.py, test-infra/README.md, test-infra/airflow/Dockerfile.prow, test-infra/airflow/dags/e2e_tests_dag.py, test-infra/airflow/deployment.yaml
* Fixes #164
* Modify our test to setup a GPU cluster.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/k8s/213)
=> Add a basic GPU job test as part of our E2E tests.

pkg/controller/controller.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/k8s/226)
=> controller.go: Fix a print error

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/k8s/225)
=> replace tf-job-operator-config configmap when it already exist

py/util.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/k8s/231)
=> use glide install --strip-vendor remove subpackage vendor

py/airflow.py, py/deploy.py, py/test_runner.py, py/util.py, py/util_test.py, test-infra/airflow/Dockerfile, test-infra/airflow/Dockerfile.prow, test-infra/airflow/deployment.yaml
* The setup cluster step should wait for the TfJob operator deployment to
be ready.
* Ensure that all exceptions result in a failure message being reported to Gubernator.
* Upgrade and fix issues with Kubernetes py client 4.0.0; Fixes #242 
* Bugs with gpu_test Fix #240
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/k8s/241)
=> Fix issues with tf_job_gpu test

version/version.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/k8s/253)
=> fix(no-dup): reduce dup code in printVersion

README.md, cmd/tf_operator/main.go, developer_guide.md, tf-job-operator-chart/templates/config.yaml, tf-job-operator-chart/templates/deployment.yaml, tf-job-operator-chart/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/k8s/259)
=> follow kubernetes flag convension

pkg/trainer/replicas.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/k8s/272)
=> bugfix: set faliures=true if failed deleting configmap

tf_job_design_doc.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/k8s/305)
=> fix broken link

pkg/trainer/training.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/k8s/307)
=> replace TPR with CRD

cmd/tf_operator/app/options/options.go, cmd/tf_operator/app/server.go, cmd/tf_operator/main.go, pkg/apis/tensorflow/helper/helpers.go, pkg/apis/tensorflow/helper/helpers_test.go, pkg/apis/tensorflow/v1alpha1/defaults.go, pkg/apis/tensorflow/v1alpha1/defaults_test.go, pkg/apis/tensorflow/v1alpha1/doc.go, pkg/apis/tensorflow/v1alpha1/register.go, pkg/apis/tensorflow/v1alpha1/types.go, pkg/apis/tensorflow/validation/validation.go, pkg/apis/tensorflow/validation/validation_test.go, pkg/controller/controller.go, pkg/trainer/labels.go, pkg/trainer/replicas.go, pkg/trainer/replicas_test.go, pkg/trainer/tensorboard.go, pkg/trainer/tensorboard_test.go, pkg/trainer/training.go, pkg/trainer/training_test.go, pkg/util/k8sutil/k8sutil.go, pkg/util/retryutil/retry_util.go, pkg/util/util.go
Close https://github.com/tensorflow/k8s/issues/266
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/k8s/364)
=> *: Add copyright owner in go files

.travis.yml
Close #382 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/k8s/383)
=> travis: Add go build command

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/387)
=> fix a typo in the README file.

developer_guide.md, py/release.py
There are some problems when I follow the developer guide to build in local , and I fix these problems.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/390)
=> Fix something after move to kubeflow/tf-operator

README.md
PTAL
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/392)
=> README: Add community section and quick links

build/release/Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/409)
=> Fix typo in Makefile

OWNERS
Hi, Jeremy
Suppose to add me as approver/reviewer.
@jlewi @gaocegege @DjangoPeng PTAL.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/419)
=> Add ScorpioCPH as approver/reviewer

pkg/client/clientset/versioned/clientset.go, pkg/trainer/training.go, pkg/util/k8sutil/k8sutil.go
This PR is to revert the changes in client by `hack/update-codegen.sh`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/428)
=> clientset: Fix code which is changed manually

test/workflows/components/params.libsonnet, test/workflows/components/workflows.libsonnet
Related: https://github.com/kubeflow/testing/issues/18
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/459)
=> Change test cluster to kubeflow-ci

OWNERS
fix my id lol
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/462)
=> Fix owners file id

.travis.yml, pkg/controller/controller_test.go, pkg/controller/controller_utils.go
Close #455 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/467)
=> test: Add unit test for controller

pkg/controller/controller.go, pkg/controller/controller_pod.go, pkg/controller/controller_service.go
This PR will update TFJob status in each sync loop.
@gaocegege @jlewi PTAL, thanks!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/472)
=> Update tfjob status

linter_config.json, pkg/apis/tensorflow/v1alpha2/types.go, pkg/controller/controller.go, pkg/controller/controller_pod.go, pkg/controller/controller_service.go, pkg/controller/controller_test.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/477)
=> *: Fix some errors in Travis CI

pkg/controller/controller_pod.go, pkg/controller/controller_test.go
Add some internal state test cases and fix a bug about status update imported by myself.
/assign @ScorpioCPH
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/480)
=> controller: Add internal state test 

pkg/controller/controller_test.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/482)
=> controller: Add check for service and fix service

pkg/trainer/replicas.go
ref https://github.com/kubeflow/tf-operator/issues/40
cc @gaocegege
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/471)
=> Use headless services for Training jobs

pkg/controller/controller_pod.go, pkg/controller/controller_pod_test.go, pkg/controller/controller_service_test.go, pkg/controller/controller_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/488)
=>  test: Add test cases 

pkg/controller/controller_pod.go
This PR fix ENV append issue, @gaocegege @jlewi PTAL.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/494)
=> Fix env append issue

py/release.py, py/release_test.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/498)
=> release: Fix style

pkg/controller/controller_pod.go, pkg/controller/controller_test.go
/cc @ScorpioCPH 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/505)
=> test: Fix failed case because of update status

pkg/controller/controller.go, pkg/controller/controller_pod.go, pkg/controller/controller_test.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/506)
=> test: Add test cases for condition

pkg/controller/controller_pod.go, pkg/controller/controller_utils.go
Hi, this PR check running status more gracefully.
@gaocegege @yph152 PTAL, thanks!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/507)
=> Check running status more gracefully

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/513)
=> Fix outdated information about GPUs in README

pkg/controller/controller_test.go, version/version.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/527)
=> tests: Fix

cmd/tf-operator/app/options/options.go
@gaocegege  fix #522 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/525)
=> v1alpha2: update flag kubeconfig

pkg/util/signals/signal.go, pkg/util/signals/signal_posix.go, pkg/util/signals/signal_windows.go
/assign @jlewi 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/531)
=> signals: Add

OWNERS
@willb could help us to review the code about release process. See https://github.com/kubeflow/tf-operator/pull/517
@ddysher could help us to review the code about v1alpha2.
/assign @jlewi @ScorpioCPH 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/529)
=> OWNERS: Add @ddysher and @willb as reviewers

README.md
/assign @ScorpioCPH @jlewi 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/553)
=> README: Add tf-operator v1alpha2 design doc

pkg/controller.v2/controller_pod.go
set completion time on success
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/554)
=> set completion time on success

examples/gke/test_notebook.py, py/prow.py, py/release.py, test/workflows/components/workflows.libsonnet
Related https://github.com/kubeflow/testing/issues/90
Fixes https://github.com/kubeflow/tf-operator/issues/567
/cc @DjangoPeng @gaocegege @ScorpioCPH
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/568)
=> Update test worker image to kubeflow-ci

pkg/controller.v2/controller_pod.go
@gaocegege  fix bug for int convert
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/571)
=> [v1alpha2]fix bug int to string for index

dashboard/backend/handler/api_handler.go, test/e2e/main.go
Format go code and fix spelling errors
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/585)
=> Format go code and fix spelling errors

examples/crd/crd-v1alpha2.yaml, test/e2e/dist-mnist/README.md, test/e2e/dist-mnist/tj_job_mnist.yaml
It eases the use of the test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/583)
=> mnist: Add correponding yaml config

test/e2e/dist-mnist/dist_mnist.py
Fix #588 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/604)
=> dist_mnist: Add unused_argv

dashboard/backend/handler/api_handler.go, dashboard/frontend/src/components/CreateJob.js, dashboard/frontend/src/components/CreateReplicaSpec.js, dashboard/frontend/src/components/Job.js, dashboard/frontend/src/components/JobDetail.js, dashboard/frontend/src/components/JobSummary.js, dashboard/frontend/src/components/PodList.js, dashboard/frontend/src/components/ReplicaSpec.js, dashboard/frontend/src/components/VolumeCreator.js
Upgrade dashboard to v1alpha2 api.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/613)
=> [dashboard] Upgrade to v1alpha2

test/workflows/components/params.libsonnet, test/workflows/components/simple_tfjob.jsonnet
Related to https://github.com/kubeflow/kubeflow/issues/852
/assign @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/619)
=> Add apiVersion parameter to simple_tfjob component

.travis.yml, dashboard/backend/handler/api_handler.go, linter_config.json
This PR is to fix the Travis CI error in #613 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/618)
=> api_handler: Fix import order

pkg/controller.v2/controller.go, pkg/controller.v2/controller_helper.go, pkg/controller.v2/controller_tfjob.go, pkg/controller.v2/informer.go
Close #620 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/623)
=> pkg: Send events when reveive invalid spec

py/test_runner.py, py/tf_job_client.py
Related https://github.com/kubeflow/kubeflow/issues/852
/assign @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/626)
=> Pass TFJob API version instead of hardcoding it

pkg/controller.v2/controller_pod.go, pkg/controller.v2/controller_pod_test.go, pkg/controller.v2/controller_tfjob_test.go
/assign @jlewi 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/649)
=> pods: Add cluster spec test

pkg/controller.v2/controller_helper.go, pkg/controller.v2/controller_pod_test.go, pkg/controller.v2/controller_service.go, pkg/controller.v2/controller_tensorflow.go
Close #654 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/656)
=> *: Remove namespace from service name

pkg/controller.v2/controller_tfjob_test.go
Close #542 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/658)
=> tfjob: Add test for copy labels and annotations

cmd/tf-operator.v2/app/options/options.go, cmd/tf-operator.v2/app/server.go
/assign @jlewi 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/662)
=> server: Make threadiness configurable

pkg/controller.v2/controller_tensorflow.go
seems page https://cloud.google.com/ml-engine/docs/trainer-considerations  has changed its content
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/679)
=> change comment with more related link

prow_config.yaml, py/deploy.py, py/test_runner.py, py/tf_job_client.py, test/workflows/app.yaml, test/workflows/components/master_is_chief_v1alpha2.jsonnet, test/workflows/components/worker0_is_chief_v1alpha2.jsonnet, test/workflows/components/workflows.libsonnet
Fix #634
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/667)
=> Enable the E2E tests for v1alpha2.

pkg/apis/tensorflow/v1alpha2/constants.go, pkg/apis/tensorflow/v1alpha2/defaults.go, pkg/apis/tensorflow/v1alpha2/defaults_test.go, pkg/apis/tensorflow/v1alpha2/types.go, pkg/controller.v2/controller_pod.go, pkg/controller.v2/controller_pod_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/676)
=> fix restart policy with comment

pkg/controller.v2/informer.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/684)
=> informer: Add comments and TODO

pkg/control/service_control.go, pkg/controller.v2/controller.go, pkg/controller.v2/controller_pod.go, pkg/controller.v2/controller_status.go, pkg/controller.v2/controller_status_test.go, pkg/controller.v2/controller_tfjob.go, py/test_runner.py
/hold
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/686)
=> pkg: Delete pods and services after finished

pkg/controller.v2/controller_status.go, pkg/controller.v2/controller_status_test.go
This is to fail the TFJob if PS is failed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/690)
=> status: Fail the TFJob if PS is failed

pkg/controller.v2/controller_tfjob.go, pkg/controller.v2/informer.go
fix #680 
/cc @gaocegege
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/694)
=> [v1alpha2]update tfjob condition for Created

pkg/apis/tensorflow/v1alpha2/defaults.go, pkg/apis/tensorflow/v1alpha2/types.go
fixes #698
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/699)
=> Wrong comment when setting default CleanPodPolicy

pkg/controller.v2/controller_pod_test.go, pkg/util/testutil/tfjob.go
Add test cases for evaluator issues#651 
Signed-off-by: Pengyu Chen <chenpengyu@caicloud.io>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/700)
=> [v1alpha2] controller_pod_test: Add test cases for evaluator

OWNERS
/cc @yph152 @codeflitting @jlewi 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/714)
=> OWNERS: Add yph152 and codeflitting as reviewers

py/tf_job_client.py
Sometimes it takes a while for the tfjob to show up
This fails the entire test if there is an exception
/assign @kunmingg
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/728)
=> Add retrying to log_status function

developer_guide.md
update to  the correct directory
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/726)
=> Update developer_guide.md for v1alpha2

pkg/controller.v2/informer.go
Make it easier to debug
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/732)
=> Add err msg for TFJob from Unstructured

dashboard/backend/handler/api_handler.go
Fix #737
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/738)
=> fix list all the pods of tfjob

OWNERS
/assign @cheyang 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/741)
=> OWNER: Add cheyang, Remove mitake

cmd/tf-operator/app/server.go, linter_config.json, pkg/controller.v2/controller_pod.go, pkg/controller.v2/controller_service.go, pkg/controller.v2/controller_tensorflow.go
Ref https://github.com/alecthomas/gometalinter/pull/505
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/758)
=> linter: Rename gas to gosec and fix linting errors

OWNERS
/assign @gaocegege 
Thanks!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/784)
=> OWNERS: Add ChanYiLin as reviewers

pkg/controller.v2/tfcontroller/status.go
When the JOB goes to FAILED state, the completion time is not set
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/797)
=> Job completion time is not set for job FAILED state

pkg/controller.v2/tfcontroller/pod.go, pkg/controller.v2/tfcontroller/status.go, pkg/controller.v2/tfcontroller/status_test.go, test/workflows/components/workflows.libsonnet
Fix https://github.com/kubeflow/tf-operator/issues/751.
@jlewi @gaocegege PTAL, thanks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/791)
=> Mark TFJob succeeded if worker 0 completed.

build/images/tf_operator/Dockerfile
Thanks to @johnugeorge 's report, I imported a bug from #802 , this PR is to fix it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/803)
=> Dockerfile: Fix typo

py/test_runner.py, test/workflows/components/clean_pod_all.jsonnet, test/workflows/components/clean_pod_none.jsonnet, test/workflows/components/clean_pod_running.jsonnet, test/workflows/components/params.libsonnet, test/workflows/components/workflows.libsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/795)
=> Add an e2etest to verify clean pod policy in TF job operator

pkg/controller.v2/tfcontroller/tfjob.go
Close #755 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/807)
=> tfjob: Send event to object

pkg/controller.v2/tensorflow/pod.go
/assign @johnugeorge @jlewi 
Close #818 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/819)
=> pod: Fix eventf

prow_config.yaml
* Related to kubeflow/kubeflow#1599
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/832)
=> Fix postusbmit builds; registry is incorrect.

.travis.yml
Build both v1 and v2 in travis.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/835)
=> travis: Fix a typo

CHANGELOG.md, hack/scripts/update-changelog.sh
* I created a v0.3 tag to support this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/839)
=> Update changelog to include changes in v0.3.

dashboard/backend/main.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/841)
=> add frontend-dir & port flag to backend program

OWNERS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/847)
=> Add richardsliu to OWNERS

e2e_testing.md
Fixes https://github.com/kubeflow/tf-operator/issues/822
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/852)
=> Add documentation for writing E2E tests

cmd/tf-operator.v2/app/options/options.go, cmd/tf-operator/app/options/options.go, pkg/controller.v2/jobcontroller/jobcontroller.go, pkg/trainer/training.go
should rename kube-arbitrator to kube-batch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/855)
=> Rename kube-arbitrator to kube-batch.

pkg/controller.v1beta1/tensorflow/controller.go, pkg/controller.v1beta1/tensorflow/pod.go, pkg/controller.v1beta1/tensorflow/service.go, pkg/controller.v1beta1/tensorflow/tensorflow.go
Related to https://github.com/kubeflow/tf-operator/issues/866
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/867)
=> Import jobcontroller from common package

Gopkg.lock, Gopkg.toml
This is to ensure that tf-operator can be imported to katib.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/874)
=> Upgrade k8s dependency to 1.10.1

pkg/common/util/testutil/tfjob.go, pkg/controller.v1beta1/tensorflow/pod_test.go, pkg/controller.v1beta1/tensorflow/tensorflow.go, pkg/controller.v2/tensorflow/pod_test.go, pkg/controller.v2/tensorflow/tensorflow.go, pkg/util/testutil/tfjob.go, py/estimator_runconfig_tests.py
As we discussed here https://github.com/kubeflow/tf-operator/issues/875, this PR is a proposal for this feature.
@jlewi @gaocegege @richardsliu PTAL.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/876)
=> Support custom defined cluster domain

pkg/controller.v2/tensorflow/status.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/891)
=> bug: get condition just get last, should get special type condition

pkg/controller.v2/tensorflow/controller.go, pkg/controller.v2/tensorflow/informer.go, pkg/controller.v2/tensorflow/job.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/890)
=> feat: optimize code

pkg/controller.v2/tensorflow/job.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/905)
=> job: Fix log output

pkg/controller.v1beta1/tensorflow/controller.go
/hold
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/897)
=> Don't reinitialize replica statuses after TFJob completes

py/estimator_runconfig_tests.py, test/workflows/components/estimator_runconfig_v1alpha2.jsonnet, test/workflows/components/estimator_runconfig_v1beta1.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/909)
=> Add evaluator to E2E test.

.gitignore
Ignore VIM temporary files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/912)
=> Add .swp to gitignore.

dashboard/backend/handler/api_handler.go
This PR addresses the issue that causes TFJob UI to fail on /tfjobs/api/TFJob endpoint due to apiVersion mismatch.
Signed-off-by: Abhilash Pallerlamudi <stp.abhi@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/917)
=> Update backend apiVersion to v1beta1 to fix tfjob list.

py/tf_job_client.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/918)
=> fix wrong var used of wait_for_condition method

pkg/common/jobcontroller/jobcontroller.go, pkg/controller.v1beta1/tensorflow/controller_test.go
Fixes: #922
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/930)
=> Removing PDB check for Min available replicas 

pkg/apis/tensorflow/v1beta2/types.go, pkg/client/clientset/versioned/typed/kubeflow/v1beta2/fake/fake_tfjob.go, pkg/client/clientset/versioned/typed/kubeflow/v1beta2/tfjob.go, pkg/controller.v1beta2/tensorflow/controller_test.go, pkg/controller.v1beta2/tensorflow/job.go, pkg/controller.v1beta2/tensorflow/status.go, pkg/util/k8sutil/client.go, test/test-app/components/core.jsonnet, test/test-app/vendor/kubeflow/core/prototypes/tf-job-operator.jsonnet, test/test-app/vendor/kubeflow/core/tf-job-operator.libsonnet
Fixes #924 #927
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/939)
=> Add status subresource to CRD; use UpdateStatus

py/deploy.py, test/test-app/components/params.libsonnet, test/test-app/environments/default/params.libsonnet, test/test-app/vendor/kubeflow/core/prototypes/all.jsonnet, test/test-app/vendor/kubeflow/core/prototypes/tf-job-operator.jsonnet, test/test-app/vendor/kubeflow/core/tf-job-operator.libsonnet, test/workflows/components/workflows.libsonnet
Porting changes from https://github.com/kubeflow/kubeflow/pull/2474 to tf-operator.
Fixes https://github.com/kubeflow/tf-operator/issues/932
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/943)
=> Support multiple CRD versions for TFJob

build/images/tf_operator/Dockerfile
restructure the dockerfile to make it more readable and easy to port to other platforms.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/893)
=> refactor the dockerfile

pkg/controller.v1beta2/tensorflow/pod.go
Fix issue https://github.com/kubeflow/tf-operator/issues/920
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/957)
=> Use kube-batch as scheduler by default when gang-scheduling is enabled

pkg/apis/tensorflow/validation/validation.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/940)
=> Avoid hardcoded tf container name in log

.github/issue_label_bot.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/973)
=> Issue Label Bot Alias Yaml 

OWNERS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/986)
=> Prune tf-operator OWNERS file

pkg/controller.v1beta2/tensorflow/pod.go
Reverts kubeflow/tf-operator#974. Fixes #987. 
/cc johnugeorge
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/992)
=> Revert "Fix ineffassign error in masterRole assignment"

pkg/controller.v1beta2/tensorflow/controller.go
fix https://github.com/kubeflow/tf-operator/issues/994
/assign @richardsliu @gaocegege
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/995)
=> set CompletionTime first when tfjob exceeds limit

prow_config.yaml
Only run v1beta2 tests if relevant or common code is changed. Same for v1.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1008)
=> Scope presubmits by version

docs/quick-start-v1.md, pkg/apis/common/v1/openapi_generated.go, pkg/apis/common/v1/types.go, pkg/apis/tensorflow/v1/openapi_generated.go, pkg/apis/tensorflow/v1/types.go
Fix up the documentation for v1.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1009)
=> Polish documentation for TFJob V1

pkg/controller.v1/tensorflow/status.go, pkg/controller.v1beta2/tensorflow/status.go
Ref https://github.com/kubeflow/pytorch-operator/issues/88
/cc @johnugeorge @richardsliu 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/982)
=> status: Avoid setting last transition time

pkg/common/jobcontroller/pod.go
@gaocegege @richardsliu @johnugeorge
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1015)
=> do not ignore DeletedFinalStateUnknown event when delete pod

pkg/controller.v1/tensorflow/controller.go, pkg/controller.v1beta2/tensorflow/controller.go
ref https://github.com/kubernetes/kubernetes/issues/77644
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1014)
=> Add pending status for pastBackoffLimitOnFailure

OWNERS
I would like to help review PRs if it is ok.
/assign @gaocegege @richardsliu
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1017)
=> Add wackxu as reviewers

pkg/controller.v1/tensorflow/controller.go, pkg/controller.v1beta2/tensorflow/controller.go
/assign @johnugeorge
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1021)
=> fix bug for check PodPending

build/images/tf_operator/Dockerfile, py/kubeflow/tf_operator/Pipfile.lock
Moved image base from dev preview to GA
/assign @richardsliu
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1023)
=> Update image base to UBI8 GA

cmd/tf-operator.v1/app/server.go
CoreV1 scheme is added as in v1beta2 version
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1037)
=> Minor fix to add CoreV1 to scheme

pkg/common/jobcontroller/jobcontroller.go
Update from kube-arbitrator to kube-batch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1028)
=> Update gang scheduler name

build/images/tf_operator/Dockerfile
Fixes: #1058 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1062)
=> rewrite dockerfile

examples/v1/mnist_with_summaries/tf_job_mnist.yaml, examples/v1beta2/mnist_with_summaries/tf_job_mnist.yaml
Fixes: https://github.com/kubeflow/tf-operator/issues/1053.
/cc @gaocegege @richardsliu
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1073)
=> Fix example Mnist With Summaries 

py/kubeflow/tf_operator/release.py
Signed-off-by: yeya24 <yb532204897@gmail.com>
fix #1035
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1052)
=> add ldflag verion

hack/python-sdk/gen-sdk.sh, sdk/python/README.md, sdk/python/examples/kubeflow-tfjob-sdk.ipynb
The PR is going to:
- Fixed one problems on SDK README files.
- Replaced the sdk examples to sdk/python dir so that user can easy find the example that shows how to use the sdk basically.
- Other mini env variable update.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1114)
=> Enhance tfjobs sdk docs

pkg/common/util/v1/testutil/util.go
for https://github.com/kubeflow/pytorch-operator/pull/241
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1118)
=> fix(ConvertTFJobToUnstructured): ConvertTFJobToUnstructured uses function ToUnstructured to convert TFJob to Unstructured

build/images/tf_operator/Dockerfile, py/kubeflow/tf_operator/deploy.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1128)
=> Copy third party vendor source code to Docker image

py/kubeflow/tf_operator/tf_job_client_py3.py
httplib has been renamed as `http.client`: https://stackoverflow.com/questions/13778252/import-httplib-importerror-no-module-named-httplib
adding new script to prevent breaking changes.
Related: kubeflow/kfctl#228
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1133)
=> add tf-operator test in py3

docs/roadmap.md
/assign @johnugeorge @richardsliu 
Is there anything we should do?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1140)
=> docs: Add roadmap

pkg/common/util/v1/testutil/pod.go, pkg/controller.v1/tensorflow/pod_test.go, pkg/controller.v1/tensorflow/status_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1145)
=> Remove unused function arg

OWNERS
I would like to be the approver of Kubeflow/tf-operator and to participate more in the future roadmap.
Have discussed with @gaocegege 
/cc @richardsliu  @johnugeorge
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1147)
=> OWNERS: Add ChanYiLin as approver

pkg/controller.v1/tensorflow/pod_test.go, pkg/controller.v1/tensorflow/tensorflow.go, py/kubeflow/tf_operator/estimator_runconfig_tests.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1146)
=> Fix evaluator runconfig

pkg/apis/tensorflow/v1/openapi_generated.go, pkg/apis/tensorflow/v1/types.go, pkg/common/jobcontroller/pod.go, pkg/common/jobcontroller/service.go, pkg/controller.v1/tensorflow/controller.go, pkg/controller.v1/tensorflow/pod.go, pkg/controller.v1/tensorflow/pod_test.go, pkg/controller.v1/tensorflow/service.go, pkg/controller.v1/tensorflow/tensorflow.go, pkg/controller.v1/tensorflow/tensorflow_test.go
Proposal: https://github.com/kubeflow/tf-operator/issues/1141
Test:
`go test -v ./pkg/controller.v1/tensorflow`
=> Support ClusterSpec Propagation Feature in TF 1.14

py/kubeflow/tf_operator/tf_job_client.py
=> Update tf_job_client.py remove unused variable. 

.pylintrc
context: https://sites.google.com/corp/google.com/os-respectfulcode-fixit
=> b/168938304 - Inclusive Language Fix-It, repo has non-inclusive language

cmd/tf-operator.v1/app/server.go, cmd/tf-operator.v1/main.go, vendor/modules.txt
This PR is to:
- Fix import order
- Improve logging
=> chore: Refactor cmd

cmd/tf-operator.v1/app/server.go
add err log for create client set failed and code minor optimization
=> add err log for create client set failed and code minor optimization

examples/crd/crd-v1.yaml
add Evaluator type for CRD example , that is a user friendly way.
=> add Evaluator type for CRD example

pkg/common/util/v1/testutil/tfjob.go, pkg/controller.v1/tensorflow/pod.go, pkg/controller.v1/tensorflow/pod_test.go
fix bug #1214, add a condition before  access worker instance
@gaocegege
=> Fix updateStatus no worker Crashoff

README.md, deploy/v1/tf-operator.yaml
=> feat(deploy): Add standalone deployment yaml

go.mod, go.sum
As titled, upgrade kubeflow common to 0.3.2.
=> Update kubeflow common to 0.3.2

build/images/tf_operator/Dockerfile
=> fix: Remove vendor cp command

docs/adopters.md
=> chore: Add tencent cloud

pkg/controller.v1/tensorflow/pod.go, pkg/controller.v1/tensorflow/pod_test.go
=> fix: Observe the creation when failed to create the pod

cmd/tf-operator.v1/app/server.go, pkg/controller.v1/tensorflow/controller_test.go, pkg/controller.v1/tensorflow/informer.go
Remove default resync period in unstructured informer to avoid frequent resync.
/cc @terrytangyuan @ChanYiLin 
=> fix: Remove default resync period

examples/crd/crd-v1.yaml
=> support multiple evaluators

pkg/apis/tensorflow/validation/validation.go, pkg/apis/tensorflow/validation/validation_test.go
There are some cases that contain more than 1 evaluator. It is to fix it.
/assign @ChanYiLin @terrytangyuan 
=> fix: Do not validate evaluator

deploy/v1/tf-operator.yaml
crd definition support multiple evaluator
=> crd definition support multiple evaluator

go.mod, go.sum, vendor/github.com/kubeflow/common/pkg/controller.v1/common/job_controller.go, vendor/modules.txt
Signed-off-by: jiangkaihua <jiangkaihua1@huawei.com>
=> Update vendor as kubeflow/common is updated.

pkg/controller.v1/tensorflow/controller.go, pkg/controller.v1/tensorflow/pod.go
Signed-off-by: jiangkaihua <jiangkaihua1@huawei.com>
=> Add task type annotation for pods when EnableGangScheduling is true.

OWNERS
@ChanYiLin  @johnugeorge @gaocegege @andreyvelich 
Wang and I are working on common operator. I am asking team to temporarily grant me approver permission so we two can quickly merge requests to catch summit timeline. 
We plan to create a separate branch in tf-operator and develop the features  there. Once it's ready, changes will be merged back to master. The strategy is to make original tf-operator work for all other frameworks as well and then rename the repo. 
issues, stars and followers will be automatically redirected to the new repo per @terrytangyuan's suggestion. https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/renaming-a-repository
=> Temporarily add Jeffwan@ to OWNERS

examples/v1/distribution_strategy/keras-API/Dockerfile
The latest version tries to get a google authentication bearer token
https://github.com/tensorflow/datasets/issues/2761
=> add a specific version of tensorflow_datasets

cmd/training-operator.v1/main.go, pkg/controller.v1/register_controller.go
=> add option to enable schemes

pkg/controller.v1/xgboost/xgboostjob_controller.go
This is used to test post-submit jobs. We are merging to a dev branch "all-in-one-operator" but not master. 
/cc @PatrickXYS
=> Trigger post-submit job

manifests/overlays/kubeflow/kustomization.yaml, manifests/overlays/standalone/kustomization.yaml
Updating manifests to latest image tag
=> Update manifests with  latest image tag

manifests/overlays/kubeflow/kustomization.yaml, manifests/overlays/standalone/kustomization.yaml
Address #1403 
/cc @kubeflow/wg-training-leads
=> chore: Update image tags in manifests

OWNERS
Signed-off-by: Yuan Tang <terrytangyuan@gmail.com>
=> docs: Move myself to approvers

docs/adopters.md
I added Cisco to Adopters List.
/assign @terrytangyuan @Jeffwan 
/cc @ramdootp @amsaha
=> Add Cisco to Adopters List

examples/xgboost/lightgbm-dist/Dockerfile, examples/xgboost/lightgbm-dist/README.md, examples/xgboost/lightgbm-dist/main.py, examples/xgboost/lightgbm-dist/train.py, examples/xgboost/lightgbm-dist/utils.py, examples/xgboost/lightgbm-dist/xgboostjob_v1_lightgbm_dist_training.yaml, examples/xgboost/smoke-dist/Dockerfile, examples/xgboost/smoke-dist/README.md, examples/xgboost/smoke-dist/requirements.txt, examples/xgboost/smoke-dist/tracker.py, examples/xgboost/smoke-dist/xgboost_smoke_test.py, examples/xgboost/smoke-dist/xgboostjob_v1_rabit_test.yaml, examples/xgboost/smoke-dist/xgboostjob_v1alpha1_rabit_test.yaml, examples/xgboost/xgboost-dist/Dockerfile, examples/xgboost/xgboost-dist/README.md, examples/xgboost/xgboost-dist/build.sh, examples/xgboost/xgboost-dist/local_test.py, examples/xgboost/xgboost-dist/main.py, examples/xgboost/xgboost-dist/predict.py, examples/xgboost/xgboost-dist/requirements.txt, examples/xgboost/xgboost-dist/tracker.py, examples/xgboost/xgboost-dist/train.py, examples/xgboost/xgboost-dist/utils.py, examples/xgboost/xgboost-dist/xgboostjob_v1_iris_predict.yaml, examples/xgboost/xgboost-dist/xgboostjob_v1_iris_train.yaml, examples/xgboost/xgboost-dist/xgboostjob_v1alpha1_iris_predict.yaml, examples/xgboost/xgboost-dist/xgboostjob_v1alpha1_iris_predict_local.yaml, examples/xgboost/xgboost-dist/xgboostjob_v1alpha1_iris_train.yaml, examples/xgboost/xgboost-dist/xgboostjob_v1alpha1_iris_train_local.yaml
See https://github.com/kubeflow/xgboost-operator/pull/125#issuecomment-964456796.
Signed-off-by: terrytangyuan <terrytangyuan@gmail.com>
=> Migrate additional examples from xgboost-operator

README.md
https://github.com/kubeflow/training-operator/pull/1477
=> Add MPI job to README now that it's supported

.github/workflows/test-go.yaml
In PR #1440, I forgot to put a space in `exit1`, so I fixed it.
Fixes #
=> chore: Fix GitHub Actions script

pkg/controller.v1/mpi/mpijob_controller.go
Signed-off-by: lubingtan <lubingtan@126.com>
Fix a typo in mpi controller.
Fixes #
**Checklist:**
=> Fix a typo in mpi controller log

examples/mpi/tensorflow-mnist.yaml
#1502[](https://github.com/kubeflow/training-operator/issues/1502) add the example of MPIJob in the kubeflow/training-operator.
=> add the example of MPIJob

sdk/python/kubeflow/__init__.py
PR is cherry picked from master
=> Cherry pick PR:   extends path in __init__.py for SDK correctly (#1531)

docs/design/tf_job_design_doc.md
=> update img url in design doc

hack/update-codegen.sh
Signed-off-by: Peng Gao <peng.gao.dut@gmail.com>
Fixes #
**Checklist:**
=> Add mpi in update-codegen.sh

pkg/controller.v1/pytorch/pytorchjob_controller.go
fix comments for pytorch-controller.
=> fix comments for pytorch-controller

pkg/apis/kubeflow.org/v1/tensorflow_types.go, pkg/controller.v1/register_controller_test.go
I fixed some typos.
Fixes #
**Checklist:**
=> [chore] fix typo

hack/python-sdk/swagger_config.json, sdk/python/kubeflow/training/__init__.py, sdk/python/kubeflow/training/api_client.py, sdk/python/kubeflow/training/configuration.py
Cherry pick:  #1651   to 1.5 release branch
=> Cherry-pick #1651:  Update SDK version to 1.5.0

README.md
Signed-off-by: Alex Wang <wangqingcan1990@gmail.com>
Update the cmd to support MPI operator
Fixes #
**Checklist:**
=> Update the cmd to support MPI operator in ReadME

Makefile
Signed-off-by: tenzen-y <yuki.iwai.tz@gmail.com>
We upgraded the K8s version in #1684, so I also upgraded the envtest and setup-env version.
/cc @johnugeorge 
Fixes #
**Checklist:**
=> Upgrade the envtest version

OWNERS
Add myself to reviewer.
Fixes #
**Checklist:**
=> Add myself to reviewer.

README.md
=> docs: Update Kubernetes requirement and version matrix

README.md
Update it to https://www.kubeflow.org/docs/about/community/#kubeflow-slack which will always have a working link. (rather than using the invited link directly).
fix: https://github.com/kubeflow/community/issues/602
like https://github.com/kubeflow/community/pull/604
**Checklist:**
=> Update join Slack link

scripts/gha/setup-training-operator.sh
Cherry-pick of #1773 on v1.6-release.
Fixes #
**Checklist:**
=> Automated cherry pick of #1773: Pin the scheduler-plugins version

pkg/apis/kubeflow.org/v1/mpi_defaults.go, pkg/apis/kubeflow.org/v1/mpi_defaults_test.go
Fixes #1799 
Set Default Replicas for MPIJob.
=> Set Default Replicas for MPIJob

pkg/controller.v1/pytorch/hpa.go
word spelling error
Fixes #
**Checklist:**
=> fix comment word spelling error

pkg/controller.v1/tensorflow/tfjob_controller_test.go
I implemented integration test for TFJob related to suspend semantics.
Fixes #
**Checklist:**
=> Implement integration test for TFJob related to suspend semantics

go.mod, go.sum
I upgraded the scheduler-plugins version to v0.26.0.
Fixes #
**Checklist:**
=> Upgrade scheduler-plugins version to v0.26.0

go.mod, go.sum
keep update with volcano release 1.8.0
Fixes #1883
**Checklist:**
=> update volcano scheduler to 1.8.0

CHANGELOG.md
add link of full change list in change log
Fixes #
**Checklist:**
=> update full change list in changelog

pkg/controller.v1/common/job.go, pkg/controller.v1/common/service_test.go
=> chore: pkg import only once

cmd/training-operator.v1/main.go, pkg/controller.v1/common/job.go, pkg/controller.v1/common/pod.go, pkg/controller.v1/common/service.go, pkg/controller.v1/pytorch/elastic.go, pkg/controller.v1/pytorch/pytorchjob_controller.go
Corrected some spelling and grammatical errors.
N/A
=> Corrected Some Spelling And Grammatical Errors

examples/sdk/train_api.ipynb
=> train api jupyternotebook fix

examples/pytorch/elastic/imagenet/Dockerfile
Add installation of python etcd library in the example Dockerfile of pytorch elastic training.
Fixes #2050 
**Checklist:**
=> fix(example): add installation of python-etcd in Pytorch example

.github/workflows/unittests.yaml, manifests/overlays/kubeflow/kustomization.yaml, manifests/overlays/standalone/kustomization.yaml
Update the training operator image to latest in release branch
=> Update training operator image to latest

examples/xgboost/lightgbm-dist/main.py, examples/xgboost/lightgbm-dist/utils.py, examples/xgboost/smoke-dist/tracker.py, examples/xgboost/smoke-dist/xgboost_smoke_test.py, examples/xgboost/xgboost-dist/local_test.py, examples/xgboost/xgboost-dist/main.py, examples/xgboost/xgboost-dist/predict.py, examples/xgboost/xgboost-dist/tracker.py, examples/xgboost/xgboost-dist/train.py, examples/xgboost/xgboost-dist/utils.py
Fixed sorting issue in xgboost folder's imports
Fixes #
**Checklist:**
=> chore(fix): isort xgboost

.github/workflows/publish-example-images.yaml
**What this PR does / why we need it**: Supports ARM64 for users to try training-example
Fixes #2111
=> ARM64 supported in PyTorch examples

.github/workflows/publish-example-images.yaml, examples/tensorflow/distribution_strategy/keras-API/Dockerfile
**What this PR does / why we need it**: Support ARM64 platform in TensorFlow examples
Fixes #2112 
**Checklist:**
=> Support ARM64 platform in TensorFlow examples

.github/workflows/build-and-publish-images.yaml, .github/workflows/integration-tests.yaml, .github/workflows/template-publish-image/action.yaml, .github/workflows/test-go.yaml, .github/workflows/unittests.yaml
Updated Github Action Workflows as per issue #2117
Fixes #2117 
**Checklist:**
=> Updated Github Action Workflows as per issue #2117

.github/workflows/unittests.yaml, manifests/overlays/kubeflow/kustomization.yaml, manifests/overlays/standalone/kustomization.yaml
To have the latest changes in the master branch, tag is updated to `latest`
=> Update the images to the latest tag in master branch

.github/ISSUE_TEMPLATE/config.yml, README.md, sdk/python/kubeflow/training/api/training_client.py
I updated Slack invitation for Training Operator Slack channel.
=> Update Slack Invitation

sdk/python/README.md
Follow up after this PR: https://github.com/kubeflow/katib/pull/2354
=> [SDK] Explain Python version support cycle

go.mod, go.sum
/kind feature
follow up volcano release v1.9.0
Fixes #
**Checklist:**
=> update volcano to v1.9.0

CHANGELOG.md
I added changelog for Training Operator v1.8.0-rc.1
Thanks everyone for your contribution to Training Operator 🎉
/assign @kubeflow/wg-training-leads @ckyuto
=> Add Changelog for Training Operator v1.8.0-rc.1

docs/release/README.md
I updated the release document.
Eventually, we should automate the release process for Training Operator.
I will create separate issue to track release improvements that we need to follow for Training Operator.
=> Update release document

.pre-commit-config.yaml, examples/pytorch/elastic/imagenet/imagenet.py, examples/pytorch/mnist/mnist.py, examples/tensorflow/dist-mnist/dist_mnist.py, examples/tensorflow/distribution_strategy/estimator-API/keras_model_to_estimator.py, examples/tensorflow/distribution_strategy/keras-API/multi_worker_strategy-with-keras.py, examples/tensorflow/mnist_with_summaries/mnist_with_summaries.py, examples/tensorflow/tf_sample/setup.py, examples/xgboost/lightgbm-dist/main.py, examples/xgboost/smoke-dist/tracker.py, examples/xgboost/smoke-dist/xgboost_smoke_test.py, examples/xgboost/xgboost-dist/local_test.py, examples/xgboost/xgboost-dist/predict.py, examples/xgboost/xgboost-dist/tracker.py, examples/xgboost/xgboost-dist/train.py, examples/xgboost/xgboost-dist/utils.py, sdk/python/kubeflow/storage_initializer/abstract_dataset_provider.py, sdk/python/kubeflow/storage_initializer/abstract_model_provider.py, sdk/python/kubeflow/storage_initializer/hugging_face.py, sdk/python/kubeflow/storage_initializer/s3.py, sdk/python/kubeflow/storage_initializer/storage.py, sdk/python/kubeflow/trainer/hf_llm_training.py, sdk/python/kubeflow/training/api/training_client.py, sdk/python/kubeflow/training/api/training_client_test.py, sdk/python/kubeflow/training/utils/utils.py
Change isort profile to black for full compatibility as per @andreyvelich [request ](https://github.com/kubeflow/katib/pull/2413#issuecomment-2305191750)
Fixes #
**Checklist:**
=> Change isort profile to black for full compatibility

sdk/python/kubeflow/storage_initializer/hugging_face.py, sdk/python/kubeflow/storage_initializer/requirements.txt, sdk/python/kubeflow/trainer/Dockerfile, sdk/python/kubeflow/trainer/hf_llm_training.py, sdk/python/kubeflow/training/api/training_client.py
Cherry pick this bug fixes into release branch:
- https://github.com/kubeflow/training-operator/pull/2180
- https://github.com/kubeflow/training-operator/pull/2230
cc @kubeflow/wg-training-leads @helenxie-bit
=> Cherry pick of #2180 #2230 into v1.8-branch

pkg/controller.v1/common/job.go, pkg/controller.v1/tensorflow/job_test.go
This needs to be released in v1.8.1, containing https://github.com/kubeflow/training-operator/pull/2243.
Part-of: https://github.com/kubeflow/training-operator/issues/2241
**Checklist:**
=> Release-1.8: Cherry-pick of #2243

sdk/python/kubeflow/training/utils/utils.py
This PR fixed a small typo of helper function "get_pvc_spec" in `utils.py`.
Fixes #
**Checklist:**
=> [SDK] Fix typo of "get_pvc_spec"

sdk/python/kubeflow/training/api/training_client.py, sdk/python/kubeflow/training/constants/constants.py
Address: https://github.com/kubeflow/training-operator/pull/2261#pullrequestreview-2322345791
**Checklist:**
=> [SDK] move env var to constants.py

sdk/python/kubeflow/training/api/training_client_test.py
New unit test for get_job_logs function
To verify run:
```
pytest -v sdk/python/kubeflow/training/api/training_client_test.py -k test_get_job_logs
```
Ref: #2161 
**Checklist:**
=> [SDK] test: add unit test for get_job_logs method of the training_client

examples/pytorch/deepspeed-demo/requirements.txt
Upgrade deepspeed demo dependencies and remove unused dependencies.
Fixes #2287 #2288 
**Checklist:**
=> Upgrade Deepspeed demo dependencies

examples/pytorch/fsdp/fine-tune-t5-with-fsdp.ipynb
Related: https://github.com/kubeflow/training-operator/issues/2040
I added simple FSDP example for T5 fine-tuning and PyTorchJob.
I refactored example from the PyTorch tutorial: https://pytorch.org/tutorials/intermediate/FSDP_adavnced_tutorial.html
=> FSDP Example for T5 Fine-Tuning and PyTorchJob

Makefile, manifests/base/webhook/kustomization.yaml
Migration from kustomize v4 to kustomize v5
Fixes #2292
**Checklist:**
=> Upgrade kustomization files to Kustomize v5

docs/proposals/2170-kubeflow-training-v2/README.md
Part of: https://github.com/kubeflow/training-operator/issues/2217
I've updated KEP with the MPI Runtime information.
/assign @tenzen-y @kubeflow/wg-training-leads @eero-t @kuizhiqing @ArangoGutierrez @alculquicondor
=> KEP-2170: Update V2 KEP with MPI Runtime info

test/integration/controller/trainjob_controller_test.go
Fix flaky integration testings: https://github.com/kubeflow/training-operator/actions/runs/13184127926/job/36802036532
Fixes #
**Checklist:**
=> IntegraionTests: Waiting for expected conditions before emulate JobSet controller manager

docs/proposals/README.md
=> Add 'KEP Usage' KEP and template link

manifests/base/runtimes/pretraining/mpi_distributed.yaml
Use the correct apiVersion name, fixed the "**resource mapping not found**" error when installing the runtime
=> Use the correct apiVersion name

go.mod, go.sum, pkg/runtime/runtime.go
Remove Kueue dependencies and use core kube PodRequests calculation helper.
Fixes #2280 
**Checklist:**
=> Replace Kueue PodRequests helper with core k/k one

examples/pytorch/deepspeed-demo/train_bert_ds.py, pkg/runtime.v2/framework/core/framework_test.go
Fix some small typos in code.
Some typos in scripts, no reference issues.
**Checklist:**
=> fix: fix typos in script comments.

pkg/runtime/core/clustertrainingruntime_test.go, pkg/runtime/core/trainingruntime_test.go, pkg/runtime/framework/plugins/plainml/plainml_test.go, pkg/util/testing/wrapper.go, test/integration/controller/trainjob_controller_test.go
I added a following:
- UTs for PlainML plugin
- Testing Wrappers for plugin UTs
Part-of https://github.com/kubeflow/trainer/issues/2468
**Checklist:**
=> Implement UTs for PlainML plugin

.github/workflows/test-e2e.yaml, .gitignore, Makefile
Followup after this: https://github.com/kubeflow/trainer/pull/2470#discussion_r1980633754
/assign @tenzen-y @Electronic-Waste
=> chore(test): Upload artifacts from dir

pkg/runtime/framework/plugins/mpi/mpi.go, pkg/runtime/framework/plugins/mpi/mpi_test.go, pkg/util/testing/wrapper.go
I added UTs for MPI plugin and found some of bugs or unimplemented items in the followings:
- hostFile is not align with OpenMPI specification. Especially, the slots generation is not correct
- runLauncherAsWorker is not considered when we build hostfile
- ...
The above unimplemented items will be implemented in the next PR.
Part-of #2468
**Checklist:**
=> Implement MPI plugin UTs

cmd/initializer/model/Dockerfile
**What this PR does / why we need it**: Fix a typo in the model initializer dockerfile
Fixes #
**Checklist:**
=> fix type in model initializer entrypoint

test/e2e/e2e_test.go
I added MPI runtime E2E tests.
Fixes https://github.com/kubeflow/trainer/issues/2496
**Checklist:**
=> Implement E2E for OpenMPI workload 

manifests/base/manager/manager.yaml, manifests/overlays/manager/kustomization.yaml
=> [feature] pull images in manifest from ghcr

.github/workflows/build-and-push-images.yaml
fix docker credentials
**Checklist:**
=> [hotfix] fix docker cred

.github/workflows/build-and-push-images.yaml
=> [hotfix] fix checkout on workflow

.github/workflows/build-and-publish-images.yaml, .github/workflows/publish-core-images.yaml
=> Push images to GHCR for release-1.9

pkg/runtime/core/trainingruntime_test.go, pkg/runtime/framework/plugins/jobset/builder.go, pkg/runtime/framework/plugins/jobset/jobset.go, pkg/util/testing/wrapper.go, test/integration/controller/trainjob_controller_test.go
We can safely remove `Launcher` chain in jobset, because we have already validated the replica by webhook.
Fixes #2554
**Checklist:**
PTAL @tenzen-y
=> feat(runtime): remove needless Launcher chainer.

.github/workflows/unittests.yaml, manifests/base/deployment.yaml
=> [bug] pull image from ghcr

pkg/runtime/indexer/indexer_test.go
This PR adds unit tests for [runtime indexers](https://github.com/kubeflow/trainer/blob/b9c0ee2fb53dfbdbe1b47d880f9da57bffa86b66/pkg/runtime/indexer/indexer.go)
Fixes #2600
=> test(runtime): add UT for IndexTrainJobTrainingRuntime

pkg/runtime/framework/plugins/coscheduling/indexer_test.go
This PR adds unit tests for [coscheduling indexers](https://github.com/kubeflow/trainer/blob/master/pkg/runtime/framework/plugins/coscheduling/indexer.go)
Fixes #2600
=> test(coscheduling) : add test coverage for coscheduling indexer

pkg/runtime/core/trainingruntime_test.go, pkg/runtime/framework/plugins/torch/torch_test.go
The codes should avoid the vendor specific parameters like `nvidia.com` and represent the codes do not depend on the vendor.
Fixes #
**Checklist:**
=> chore: Remove the vendor specific parameters

examples/torchtune/llama3_2/alpaca-trainjob-yaml.ipynb
This PR cherry-picks #2670 to release-2.0 branch
/cc @andreyvelich @tenzen-y @astefanutti 
Fixes #
**Checklist:**
=> [cherry-pick] feat(example): Add alpaca-trianjob-yaml.ipynb. (#2670)

docs/release/README.md
I updated the Kubeflow Trainer release guide.
/assign @tenzen-y @astefanutti @Electronic-Waste
=> chore(docs): Update Release Guide

CHANGELOG.md
Adding changelog for v2.0.0-rc.1
/assign @kubeflow/wg-training-leads @astefanutti @Electronic-Waste @franciscojavierarceo @szaher @kramaranya
=> chore(docs): Add Changelog for v2.0.0-rc.1

.github/workflows/check-pr-title.yaml, CONTRIBUTING.md
I added GitHub action to verify PR title.
That should help us with Changelog generation.
/assign @kubeflow/wg-training-leads @Electronic-Waste @astefanutti @franciscojavierarceo @szaher @kramaranya 
/hold for scope review
=> chore(ci): Add GitHub action to verify PR titles

docs/proposals/2401-llm-trainer-v2/README.md
This PR updates the KEP-2401 to make it consistent with current implementation:
1. Change example from Llama3.1 to Llama3.2
2. Update parameter tables in alphabetical order
/cc @kubeflow/kubeflow-trainer-team @astefanutti @kramachandran @mahdikhashan @franciscojavierarceo @deepanker13 
Fixes #
**Checklist:**
=> fix(docs): update KEP-2401 according to current implementation.

charts/kubeflow-trainer/crds/trainer.kubeflow.org_trainjobs.yaml, manifests/base/crds/trainer.kubeflow.org_trainjobs.yaml
This follows up #2804 after merging on top of #2795.
**Checklist:**
=> fix(api): Regenerate TrainJob CRD

docs/proposals/2432-gpu-testing-on-llm-blueprints/OCI VM/bootstrap.sh, docs/proposals/2432-gpu-testing-on-llm-blueprints/OCI VM/main.tf, docs/proposals/2432-gpu-testing-on-llm-blueprints/OCI VM/terraform.tfvars, docs/proposals/2432-gpu-testing-on-llm-blueprints/README.md
This PR convert GSoC proposal to KEP. The detailed description of the project is https://github.com/kubeflow/trainer/issues/2432. The new feature aims at setup self runner ( using GitHub ARC ) where we can execute GPU intensive tasks on dedicated GPU infra.
Links #2674 
CC: @andreyvelich @varodrig @Electronic-Waste 
**Checklist:**
=> feat: KEP-2432: GPU Testing for LLM Blueprints

examples/deepspeed/text-summarization/T5-Fine-Tuning.ipynb, examples/mlx/image-classification/mnist.ipynb, examples/mlx/language-modeling/fine-tune-llama.ipynb, examples/pytorch/question-answering/fine-tune-distilbert.ipynb
Manual cherry-pick of #2815 in release-2.0 branch.
**Checklist:**
=> [release-2.0] fix: update examples to reflect func_args now being unpacked (#2815)

CHANGELOG.md
I added changelog for KF Trainer v2.0.1
/assign @kubeflow/kubeflow-trainer-team @kaisoz @mimowo
=> feat(docs): Add changelog for Kubeflow Trainer v2.0.1

cmd/trainers/torchtune/requirements.txt
TorchTune has stopped it's development, so we can fix TorchTune version to the highest version `v0.6.1`
/cc @kubeflow/kubeflow-trainer-team 
Fixes #
**Checklist:**
=> chore(runtimes): Upgrade torchtune version to v0.6.1
