kubeflow/trainer

- README.md
- cmd/tf_operator/main.go
- examples/tf_job_gpu.yaml
- pkg/controller/controller.go
- pkg/spec/controller.go
- pkg/spec/tf_job.go
- pkg/spec/tf_job_test.go
- pkg/trainer/training.go
- pkg/trainer/training_test.go
- tf-job-chart/templates/tf_job_operator_deployment.yaml
* Job controller is configured with a list of volumes that need to be added to pods that use GPUs.
* Controller looks at pods that specify GPU resources and adds volume mounts needed for GPUs.
> Simplify GPU configuration process.

- pkg/controller/controller.go
- pkg/trainer/replicas.go
- pkg/trainer/training.go
- tf-job-operator-chart/values.yaml
* If a job can't be constructed because it fails validation the job should
be marked as failed and the reason set to an appropriate error.
* We do this by modifying initJob to update the status if there is a problem
initializing the job.
* replicaStatusFromPodList needs to take into account the state where
a container is running and there is no lastTerminationState.
* Otherwise we get log spam complaining about no tensorflow container
found in the running state.
* Clean up some log spam.
> Fix a couple bugs.

- examples/tf_job.yaml
- examples/tf_job_defaults.yaml
- examples/tf_job_gpu.yaml
- pkg/spec/tf_job.go
- pkg/spec/tf_job_test.go
- pkg/trainer/training.go
- pkg/trainer/training_test.go
- tf-job-operator-chart/values.yaml
* Default values are set before calling validation so that validation will
be applied to defaults.
* Picked a random value (2222) as the default port.
* Move creation of TFReplicaSet out of initJob and into TrainingJob.setup.
This is needed because we need to call SetDefaults before creating the TfReplicaSet since SetDefaults sets the default value for number of replicas.
* Update the image used by the chart.
> Set default values for Replicas, TfPort, TfReplicaType.

- pkg/controller/controller.go
- pkg/trainer/replicas.go
- pkg/trainer/replicas_test.go
- pkg/trainer/tensorboard.go
- pkg/trainer/tensorboard_test.go
- pkg/util/k8sutil/tpr_util.go
If tfjob controller runs as a deployment in k8s default namespace, we can't not create tfjob crd in another namespace.This PR fix the issue.There are three major modification:
1）tf job controller should watch crd event in all namespaces.
2）tfjob controller creates/deletes training job/tensorboard in specific namespace instead of its own ns.
3）tfjob controller maintain a map from crd name to crd object.The map key should add crd namespace as prefix.
> support multi namespaces

- pkg/controller/controller.go
Fix #41 
* Whenever we start the controller, we should check if there are existing
TfJobs and instantiate controllers for them so they aren't orphaned.
* Previously we only did this if the CRD already existed. IMO it seems
more robust to always do it and not rely on the CRD already existing.
> Always check for existing TfJobs and instantiate controllers for them.

- pkg/trainer/replicas.go
- pkg/trainer/training.go
- pkg/trainer/training_test.go
* Code should not depend on the termination message being set to decide
whether to trust exit code. This is legacy code that dependend on a
script setting the termination message. But the CRD no longer uses
a script to launch the TF process.
* Fixes #28
> Fix bug that prevents permanent errors from causing job failure.

- README.md
- tf-job-operator-chart/templates/deployment.yaml
- tf-job-operator-chart/templates/rbac.yaml
- tf-job-operator-chart/templates/service-account.yaml
- tf-job-operator-chart/values.yaml
If you have an RBAC enabled cluster, you can install helm chart with `helm install tf-job-operator-chart -n tf-job --wait --replace --set rbac.install=true`.
> Added RBAC support for tf-operator chart

- README.md
- images/tf_operator/build_and_push.py
- test-infra/README.md
- test-infra/helm-test/main.go
- test-infra/image/Dockerfile
- test-infra/image/Makefile
- test-infra/image/bootstrap.py
- test-infra/image/runner.py
- test-infra/runner.py
- tf-job-operator-chart/Chart.yaml
* Add links to the testgrid.
* Start expanding runner.py to run an actual E2E test.
> E2E test for the CRD

- images/tf_operator/build_and_push.py
- test-infra/image/bootstrap.py
- test-infra/runner.py
* When testing PR's for other committers we need to fetch the appropriate
branch.
* For periodic jobs no sha will be set so we need to checkout master
and then get the sha.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jlewi/mlkube.io/60)
> Fix presubmit jobs and periodic jobs

- test-infra/runner.py
* GCS output for periodic jobs appears to be in kubernetes-jenkins/logs/mlkube-build-periodic
* Don't set PULL in started.json if its an empty string; this is causing the
parse errors.
* Attempt to Fix #76
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jlewi/mlkube.io/77)
> Another attempt to fix periodic jobs.

- test-infra/runner.py
- test-infra/runner_test.py
* Presubmit tests need a symbolic link in GCS pointing to the results.
* Hopefully this will cause presubmit results to show up in test grid (issue #75)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jlewi/mlkube.io/79)
> Create symbolic links in GCS to output of presubmit results.

- .gitignore
- README.md
- cmd/tf_operator/main.go
- developer_guide.md
- images/tf_operator/build_and_push.py
- pkg/controller/controller.go
- pkg/controller/util.go
- pkg/garbagecollection/gc.go
- pkg/spec/tf_job.go
- pkg/spec/tf_job_test.go
- pkg/trainer/replicas.go
- pkg/trainer/replicas_test.go
- pkg/trainer/tensorboard.go
- pkg/trainer/tensorboard_test.go
- pkg/trainer/training.go
- pkg/trainer/training_test.go
- pkg/util/k8sutil/election/election.go
- pkg/util/k8sutil/fake/fake.go
- pkg/util/k8sutil/k8sutil.go
- pkg/util/k8sutil/tpr_util.go
- rename.sh
- test-infra/README.md
- test-infra/helm-test/main.go
- test-infra/image/bootstrap.py
- test-infra/runner.py
- test/e2e/main.go
* Update our E2E tests to use repository tensorflow/k8s
* Part of fix to #84
* Rename go imports to tensorflow/k8s #85
> Update test infrastructure to use repo tensorflow/k8s

- py/util.py
- test-infra/README.md
- test-infra/helm-test/main.go
* We need to specify the cloud flag when deploying the helm package so
the a volume is properly created with the TfJob config.
* This should fix issue/96
* run functions in util.py should capture stderr in addition to stdout so
we get the output from help-test
* This should fix issue/95
* Add an option to helm-test not to purge the helm release; this can help manually debugging.
> Fix the E2E test by specifying cloud when deploying the helm package.

- pkg/trainer/replicas.go
- pkg/trainer/replicas_test.go
- pkg/trainer/training.go
* RunConfig (part of Estimator API) depends on the environment being
set in TF_CONFIG to 'cloud'. If we don't set environment to 'cloud'
then is_chief isn't enabled for the master and the TF program doesn't
make progress.
* TF 1.4 should be backwards compatible; i.e. it doesn't make use of
environment in TF_CONFIG. So this code should be forward compatible.
* Expand the unittest for replicas.go to cover the new code.
* In replicas.go we should make a full DeepCopy of the PodTemplateSpec
before modifying it. It turns out K8s provides auto-generated code to
perform deep copies.
> Need to set environment to enable Estimators with TF <=1.3 

- py/release.py
- py/util.py
- release/Dockerfile.release
- release/Makefile
- release/README.md
- release/releaser.yaml
* release.py will regularly check for postsubmit results and cut new
releases.
* Create a Docker image to run and it a Kubernetes spec file to deploy it
on a K8s cluster.
* Fixes #63
> Update release.py so we can run it continuously.

- py/release.py
- py/util.py
- release/Dockerfile.release
- release/Makefile
- release/README.md
- release/releaser.yaml
- test-infra/image/Dockerfile
* Need to set GOPATH properly before building the code.
* Copy the release scripts to the Docker image rather than cloning the
repo. This makes it easier to push changes to the releaser because
we can just build the image with local changes. Otherwise we need to
commit the changes first and then build the Docker image.
* Need to break out of the loop if only building once
* Need to install helm in the releaser image because we use it to build the helm package.
* Need to build the docker images using GCB so we don't need to access docker inside the pod running the releaser.
* Store the image version in a json file inside the container and print out.
* Related to #63
>  Fix bugs in the release script.

- README.md
- examples/tf_job.yaml
- examples/tf_job/templates/tf_job.yaml
- examples/tf_job_defaults.yaml
- examples/tf_job_gpu.yaml
- examples/tf_job_tensorboard_azure.yaml
- pkg/spec/tf_job.go
- pkg/trainer/replicas.go
- pkg/trainer/replicas_test.go
- pkg/trainer/tensorboard.go
- pkg/trainer/tensorboard_test.go
* We have abandoned the name mlkube.io and moved the code into tensorflow
so it makes sense to use tensorflow.org as the group.
* We downgrade the API version from v1beta1 to v1alpha1.
We want to follow the guidelines used by K8s for alpha, beta, stable:
https://github.com/kubernetes/community/blob/master/contributors/devel/api_changes.md#alpha-beta-and-stable-versions
according to this definition we our closer to alpha since the API hasn't
achieved stability.
> Change group to tensorflow.org and version to v1alpha1.

- tf-job-operator-chart/templates/rbac.yaml
updates apiGroup from `mlkube.io` to `tensorflow.org`
> Update API group in the chart

- pkg/util/k8sutil/tpr_util.go
Currently, calling `Delete()` delete all the jobs in the namespace, even though a `name` is passed as argument.
> Fix issue in tpr_util.Delete()

- tf-job-operator-chart/Chart.yaml
- tf-job-operator-chart/templates/rbac.yaml
* TfJob operator needs permissions to create configmaps because we create
a configmap for the PS in order to create a std gRPC server.
* Change the source repository mentioned in the chart.
> Fix rbac settings in chart.

- tf_job_design_doc.md
There is a conflict about the number of worker and PS between the yaml and figure comment.
> fix(*): amend the number of worker and ps in example yaml spec for a distributed job

- py/deploy.py
- py/release.py
- py/test_util.py
- py/test_util_test.py
- py/util.py
* deploy provides commands to provision resources (K8s clusters) needed
for E2E tests.
* release.py make some changes needed to build artifacts as part of an
E2E pipeline.
* util.py add a work around for an issue with the Kubernetes Python client
library that prevents credentials from working correctly when using a
service account.
* test_util provides routines for creating junit XML files; this will be
used to create results for gubernator.
* These binaries will be used in #120
> Create binaries to run steps in an E2E test pipeline.

- tf-job-operator-chart/templates/config.yaml
Stop hardcoding the namespace for the config map that controls the TfJob operator to default.
* The namespace can be specified using helm install --namespace
* We don't set the namespace for the TfJob controller; so forcing the namespace for the configmap was a bug.
> Stop hardcoding namespace for TfJob config map

- glide.lock
Fix https://github.com/tensorflow/k8s/issues/171 .
* To better accommodate Chinese contributors we use mirrors of golang.org and google in Github because the former are blocked in China but Github is not.
> replace Google and Golang repos with corresponding github repos

- tf_job_design_doc.md
https://github.com/jlewi/mlkube.io/ is moved to this repository but the link is not updated.
PTAL
> tf_job_design_doc.md: Fix a typo

- test-infra/airflow/Dockerfile.prow
- test-infra/airflow/deployment.yaml
Resolve a merge conflict imported by commit [ae8c31](https://github.com/tensorflow/k8s/commit/ae8c3182fb47b65e84eb6e1ac3b5d5fe5be7b128)
> resolve a merge conflict imported by commit ae8c31

- developer_guide.md
- py/requirements.txt
The requirements.txt works well for me, I think it is better to add it into the repo.
WDYT
> py: Add requirements.txt

- tf_job_design_doc.md
```
error: unable to recognize "./example.yaml": no matches for mlkube.io/, Kind=TfJob
```
PTAL
> tf_job_design_doc: Fix the apiVersion

- examples/tf_sample/build_and_push.py
I tried to run the code in python 3 but it fails:
```
Traceback (most recent call last):
File "./examples/tf_sample/build_and_push.py", line 90, in <module>
image += ":" + GetGitHash()
TypeError: Can't convert 'bytes' object to str implicitly
```
Adding `decode` makes the code compatible with Python 3.
> build_and_push.py: Support python3

- examples/tf_sample/tf_sample/tf_smoke.py
Replace deprecated `tf.initialize_all_variables` with `tf.global_variables_initializer`. The deprecated API has been removed after 2017-03-02. When users run the example, they would get the WARNING as below:
```
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/python/util/tf_should_use.py:175: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
```
It should be updated with the new and official API `tf.global_variables_initializer`.
> replace deprecated tf.initialize_all_variables

- tf-job-operator-chart/templates/config.yaml
Mount NVIDIA libs in `/usr/local/nvidia/lib64` instead, that way we don't need to update `LD_LIBRARY_PATH`, avoiding some issues with CUDA.
> Fix some cuda issues on Azure

- py/build_and_push_image.py
* Building with GCB can be much faster when using GCP and GCR because we
can avoid pushing and pulling images to our local machine.
> Add an option to build Docker images with GCB.

- README.md
- tf-job-operator-chart/templates/deployment.yaml
- tf-job-operator-chart/values.yaml
* If no --cloud isn't specified then we shouldn't specify
controller_config_file
* Add options to allow the user to specify the name of a config map
if they want to set the configmap themselves.
* The options are set so that specifying a custom configmap overrides
the value selected by setting cloud so that the two options can be used
together.
Fixes #175
> Fix helm templates so that we don't require a configmap. 

- test-infra/airflow/Dockerfile
* These will be used to build the Dashboard.
* We split these changes off from 125 because they need to be submitted
first and Airflow rebuilt in order to get the presubmits for #125 to pass.
> Install yarn and nodejs inside the Airflow container.

- py/release.py
- py/release_test.py
- py/util.py
* The goal is to be able to split cloning the repo and building the artifacts into two steps #189 
* We want cloning the repo to be a separate step because we want to pull release.py from the repo when actually building the code. But in order to invoke release.py from the repo we first have to check it out.
* In a follow on PR we will update the E2E test pipeline to use the new commands.
> Create separate commands to clone and build the repo

- test-infra/airflow/Dockerfile.prow
- test-infra/airflow/dags/e2e_tests_dag.py
- test-infra/airflow/deployment.yaml
* Fixes #189 
* We want cloning the repo to be its own step because for all subsequent steps we want to use the code pulled from the repo so that we can test the code in presubmits.
> Split cloning the repo and building the images into two steps in our airflow pipeline

- py/tf_job_client.py
- test-infra/airflow/Dockerfile.prow
- test-infra/airflow/dags/e2e_tests_dag.py
- test-infra/airflow/deployment.yaml
* Fix a syntax error in handling of json parsing problems in tf_job_client
* Always run the teardown step in our E2E pipeline so we don't leave clusters up.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/k8s/220)
> Fix issue with handling of json errors.

- tf-job-operator-chart/templates/config.yaml
* GKE uses device plugins so we should no longer need to configure the TfJob
controller to mount files from the host.
* So we can remove entries from the config map.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/k8s/217)
> On GKE mounting volumes should no longer be required for GPUs.

- pkg/spec/controller.go
- pkg/spec/tf_job.go
- pkg/spec/tf_job_test.go
- pkg/trainer/training.go
- tf-job-operator-chart/templates/config.yaml
- tf-job-operator-chart/values.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/k8s/228)
Fixes #207
/cc @cwbeitel @jlewi
> let tfJob image configurable

- .travis.yml
- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/k8s/232)
fixes #155
> feat(coverage): add covealls support

- py/util.py
- test-infra/airflow/Dockerfile
- test-infra/airflow/Dockerfile.prow
- test-infra/airflow/dags/e2e_tests_dag.py
- test-infra/airflow/deployment.yaml
* The steps in our E2E tests should use the version of the test scripts
at the revision that is being tested as opposed to the version baked into
the container.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/k8s/237)
> Use the release/test python scripts pulled from the repo.

- .travis.yml
* We now check in the vendor directory so there shouldn't be any reason to run
glide install in our travis builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/k8s/236)
> Don't run glide install in travis builds.

- py/release.py
- version/version.go
```
I1214 14:57:52.480730   20446 main.go:83] No controller_config_file provided; using empty config.
I1214 14:57:52.481311   20446 main.go:113] tf_operator Version: 0.3.0+git
I1214 14:57:52.481332   20446 main.go:114] Git SHA: ba0bdfb
I1214 14:57:52.481338   20446 main.go:115] Go Version: go1.9.2
I1214 14:57:52.481343   20446 main.go:116] Go OS/Arch: darwin/amd64
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/k8s/227)
> remove todo, add gitSHA into version information

- dashboard/frontend/.eslintrc.json
- dashboard/frontend/package.json
- dashboard/frontend/yarn.lock
See #244 for a consistent auto-reformat of current code
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/k8s/243)
> feature(lint): use prettier and lint-staged for frontend javascript code

- cmd/tf_operator/main.go
- version/version.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/k8s/245)
> refactor code and format imported package

- dashboard/frontend/.eslintrc.json
- dashboard/frontend/README.md
- dashboard/frontend/package.json
- dashboard/frontend/src/components/App.css
- dashboard/frontend/src/components/App.js
- dashboard/frontend/src/components/App.test.js
- dashboard/frontend/src/components/AppBar.js
- dashboard/frontend/src/components/CreateJob.js
- dashboard/frontend/src/components/CreateTensorBoard.js
- dashboard/frontend/src/components/EnvVar.js
- dashboard/frontend/src/components/EnvVarCreator.js
- dashboard/frontend/src/components/Home.js
- dashboard/frontend/src/components/InfoEntry.js
- dashboard/frontend/src/components/Job.js
- dashboard/frontend/src/components/JobDetail.js
- dashboard/frontend/src/components/JobList.js
- dashboard/frontend/src/components/JobSummary.js
- dashboard/frontend/src/components/PodList.js
- dashboard/frontend/src/components/ReplicaSpec.js
- dashboard/frontend/src/components/RequiredTextField.js
- dashboard/frontend/src/components/TensorBoard.js
- dashboard/frontend/src/components/Volume.js
- dashboard/frontend/src/components/VolumeCreator.js
- dashboard/frontend/src/index.js
- dashboard/frontend/src/registerServiceWorker.js
- dashboard/frontend/src/services.js
- dashboard/frontend/yarn.lock
merge after #243
a follow-up PR will be made to fix all `eslint` errors (for now they stayed put). 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/k8s/244)
> feat(lint): apply prettier to format frontend src/ code

- test-infra/airflow/Dockerfile.prow
- test-infra/airflow/dags/e2e_tests_dag.py
- test-infra/airflow/deployment.yaml
* setup_cluster needs to push the cluster name so that it is available to
the teardown step before we try to setup the cluster so that the name
is available even if setup_cluster fails.
* setup_cluster also needs to handle the case where setup_cluster might
already have been attempted; in which case we should reuse that cluster.
* Fix #80 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/k8s/250)
> Fix leaking of clusters in E2E tests #80

- .travis.yml
- README.md
- linter_config.json
- pkg/controller/controller.go
- pkg/spec/tf_job.go
- pkg/spec/tf_job_test.go
- pkg/trainer/replicas.go
- pkg/trainer/replicas_test.go
- pkg/trainer/tensorboard.go
- pkg/trainer/training.go
- pkg/trainer/training_test.go
- pkg/util/k8sutil/fake/fake.go
- pkg/util/k8sutil/k8sutil.go
- pkg/util/util.go
and gradually tighten the linting rules. for now `unused` and `golint` are left out.
some fixes are included in this PR.
using `gometaliner` instead of just `golint` because:
- it covers more cases, e.g. the typo checkings.
- it also allows for disabling rules w.r.t regex, e.g. when you don't want to enforce all the comment rules enforced by `golint`
* Part of #53
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/k8s/254)
> add gometaliner into travis build 

- py/airflow.py
- py/test_util.py
- py/test_util_test.py
- py/util.py
- py/util_test.py
* Define a wrap_test function that takes care of some of the repitive work
of configuring a TestCase object.
* Define a TestSuite class to represent more than 1 TestCase.
* This should make it easy to define a suite of TestCases ahead of time
so that if we abort early, the junit file will still have an entry for
all test cases even the ones that didn't get run.
* airflow.py should set the logging formatter for the logger that logs to a
file. The file handler doesn't appear to pick up the BasicConfig.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/k8s/251)
> Improve utilities for E2E tests.

- linter_config.json
- pkg/apis/tensorflow/helper/helpers.go
- pkg/apis/tensorflow/helper/helpers_test.go
- pkg/apis/tensorflow/v1alpha1/defaults.go
- pkg/apis/tensorflow/v1alpha1/register.go
- pkg/apis/tensorflow/v1alpha1/types.go
- pkg/apis/tensorflow/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/tensorflow/validation/validation.go
- pkg/client/clientset/versioned/fake/register.go
- pkg/client/clientset/versioned/scheme/register.go
- pkg/client/informers/externalversions/factory.go
- pkg/client/informers/externalversions/generic.go
- pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
- pkg/client/informers/externalversions/tensorflow/v1alpha1/tfjob.go
fixes #256
No good way to tell whether a file was generated. a better way is to ensure that all files and newly submitted ones are `goimport`ed. also from now on I think it is better to enforce that even generated code are pre-`goimport`ed.
I didn't fix all the lint warnings because I am afraid of changing any code other than using `goimport`. I suggest that the original author do the changes instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/k8s/257)
> apply goimports -w to generated files

- py/prow.py
* Fix a typo in a comment.
* Remove the function run_lint in prow.py; this function is no longer used
to run lint checks; there is a python script for that now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/k8s/262)
> Misc Cleanup.

- cmd/tf_operator/main.go
we should use real event recorder, then we can get event from tf_operator endpoint when tf_operator failover
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/k8s/260)
> record event when tf_operator failover

- dashboard/backend/client/manager.go
- dashboard/backend/handler/api_handler.go
we should remove `/Users/admin/go/src/github.com/tensorflow/k8s/pkg/util/k8sutil/tf_job_client.go` soon when we refactor controller logic
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/k8s/258)
> refactor dashboard backend, use versioned tfjob clientset

- developer_guide.md
@jlewi @gaocegege @zjj2wry @wackxu @DjangoPeng This PR proposed new directories layout as shown below:
```sh
$ tree -d -I 'vendor|bin|.git'
├── build
│   ├── images
│   └── release
├── cmd
│   └── tf_operator
├── dashboard
│   ├── backend
│   └── frontend
├── docs
│   └── diagrams
├── examples
│   ├── charts
│   ├── gke
│   ├── tensorflow-models
│   ├── tf_job
│   └── tf_sample
├── hack
│   └── py
├── pkg
│   ├── apis
│   │   └── tensorflow
│   ├── client
│   ├── controller
│   └── util
├── test
│   ├── e2e
│   └── test-infra
└── version
```
PTAL and leave your comments about this change, and after discussion i will send a PR to do this directories refactor. Thanks!
--- …
> Add proposed directories layout

- py/deploy.py
- addressing https://github.com/tensorflow/k8s/issues/268
- previously thought GCS read/write was also necessary for tensorflow/agents
but does not appear to be the case so oauthScopes left unchanged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/k8s/269)
> update initialClusterVersion to 1.7.11-gke.1

- py/release.py
- py/util.py
- py/util_test.py
- release/Dockerfile.release
- release/launch_build.sh
- release/releaser.yaml
* Fix our continuous release process which is broken (#270)
* Docker image used to build releases needs YARN and NodeJs to build the FE.
* We refactored release.py and split cloning and building the code into two steps in #189. So we had to refactor how we build from the latest green to account for these changes. 
* release.py no longer has a function to periodically check the latest post submit and rebuild if necessary
* Created a simple shell script launch_build.sh to check out the latest green commit and then build
the code; We invoke the build function in the code checked out.
* Our releaser has been crash looping and not released any new images since 12/23.
--- …
> Fix our continuous release process

- cmd/tf_operator/app/options/options.go
- cmd/tf_operator/app/server.go
- cmd/tf_operator/main.go
Close #275 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/k8s/277)
> cmd: Fix the flag error caused by pflag

- pkg/apis/tensorflow/v1alpha1/types.go
Close #274 
I am not sure why the typo is not reported by our tests.
And, besides this, I found another error after this patch:
```
ERROR: logging before flag.Parse: I0110 16:52:24.938826    3707 controller.go:117] Starting TfJob controller
ERROR: logging before flag.Parse: I0110 16:52:24.938863    3707 controller.go:120] Waiting for informer caches to sync
ERROR: logging before flag.Parse: E0110 16:52:24.998866    3707 runtime.go:66] Observed a panic: &errors.errorString{s:"*v1alpha1.TfJobList does not implement the List interface"} (*v1alpha1.TfJobList does not implement the List interface)
```
--- …
> types.go: Fix CRDKind

- py/deploy.py
- py/test_util.py
- py/test_util_test.py
* Test failures weren't being properly reported to gubernator because we had
the wrong XML format. We need to use a nested failure tag and specify the
message inside the tag.
* Gubernator still reports the test as succeeded even if there were failures (I think we need to exit with now zero exit code from the prow job). I'll fix that in a follow on PR. In the meantime this allows us to see test failures if we click through to the gubernator dashboard.
* Related to #280
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/k8s/291)
> Fix the junit XML file format.

- pkg/apis/tensorflow/v1alpha1/register.go
- pkg/trainer/training.go
* Need to register the default functions.
* In setup we need to invoke setting the defaults on the objects.
* This fixes a break introduced when we refactored the code.
* Fix #284
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/k8s/299)
> Fix setting defaults.

- pkg/apis/tensorflow/helper/helpers.go
- pkg/apis/tensorflow/v1alpha1/register.go
- pkg/trainer/replicas_test.go
- pkg/trainer/tensorboard_test.go
Close #288 
The API version from the event is empty, we should use the definition in apis, or we can not create the resources.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/k8s/289)
> *: Fix API Version

- pkg/controller/controller.go
* Add an Update function to the controller.
* The informer periodically generates an Update event but we aren't processing these because we don't have an update function.
* As a result, TrainingJob.reconcile doesn't get called periodically and we aren't properly updating the status of the job.
ref https://github.com/tensorflow/k8s/issues/309
ref #293
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/k8s/313)
> add UpdateFunc to handle update events

- pkg/apis/tensorflow/v1alpha1/types.go
- pkg/apis/tensorflow/validation/validation.go
- pkg/apis/tensorflow/validation/validation_test.go
- pkg/controller/controller.go
- pkg/trainer/replicas.go
- pkg/trainer/training.go
- pkg/trainer/training_test.go
- py/test_runner.py
* In syncTfJob when checking whether a work queue item corresponds to a TrainingJob already in the map we need to check the UID. Otherwise we will not properly handle the case where a training job is deleted and then a new job is recreated with the same name.
* We need to make sure that the Replicas field in TrainingJob is always properly set;
* We were only initializing replicas in setup which was problematic in the case where the TfJob controller gets restarted because on restarted setup won't be invoked because the job is past that phase and as a result the replicas won't be reinitialized.
* test_runner needs to ignore case when checking whether the job succeeded otherwise we conclude
that successful jobs failed
* The controller should only forget about job after the job has been …
> Fix a bunch of problems in TfJob CRD that crept in while tests were broken

- rename.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/k8s/316)
> remove unused file rename.sh

- tf-job-operator-chart/templates/dashboard.yaml
- tf-job-operator-chart/templates/deployment.yaml
- tf-job-operator-chart/templates/rbac.yaml
- tf-job-operator-chart/templates/service-account.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/k8s/298)
> Add service account name to dashboard if RBAC.

- dashboard/backend/handler/api_handler.go
fixes #335
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/k8s/336)
> feat(dashboard): better error handling in dashboard code

- examples/tf_job.yaml
- py/deploy.py
- test/e2e/main.go
- test/e2e/simple_job.yaml.template
Helm test was failing because validation for a tfjob required that replicaSpecs for a Parameter server specify a template.  Helm test failure also was not reported.
Changes made:
- Updated e2e tests and examples to include a template for the PS replicaSpec 
- Check for `None` before concatenating the error.
Fixes https://github.com/tensorflow/k8s/issues/351 and https://github.com/tensorflow/k8s/issues/355
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/k8s/356)
> Fix helm test

- py/release.py
* This will facilitate replacing Airflow with Argo because it will allow
us to not rely on xcom to pass information between steps.
* Instead we will just pick a label based on the prow environment variables.
* Related to #205
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/k8s/357)
> Add an option to release.py to specify the tag for the image to use.

- py/release.py
Changes made:
- Moved version_tag to the common args to fix local release
Intended to fix https://github.com/tensorflow/k8s/issues/360
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/k8s/361)
> Fix local releaser

- cmd/tf_operator/app/server.go
- developer_guide.md
- pkg/util/util.go
- tf-job-operator-chart/templates/deployment.yaml
Hi, this PR fixes https://github.com/tensorflow/k8s/issues/341:
- Deprecate the ENV `MY_POD_NAMESPACE` and `MY_POD_NAME`
- And use `NamespaceDefault` by default
@jlewi PTAL, thanks!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/k8s/348)
> Deprecate the ENV MY_POD_NAME and use default namespace

- pkg/controller/controller.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/k8s/368)
> controller.go: Fix a glog typo

- py/util.py
FIxes a typo in the getenv for MASTER_REPO_NAME
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/k8s/372)
> Fix repo name env

- cmd/tf_operator/app/server.go
- version/version.go
this is a bug fix. if we using following command
```
$ ./tf_operator -version
```
it will not print any version information.
**Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):**
NONE
**Special notes for your reviewer:**
NONE @jlewi 
**Release note:**
NONE
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/k8s/367)
> fix -version option: print version

- config.sh
As we discussed in slack, we could remove the file since it is not used in the repository.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/k8s/381)
> config.sh: Remove

- README.md
- prow_config.yaml
- py/prow.py
- py/py_checks.py
- py/release.py
- py/release_test.py
- py/test_runner.py
- py/tf_job_client.py
- py/util.py
- test/workflows/components/params.libsonnet
- test/workflows/components/workflows.libsonnet
* See kubeflow/testing#12
* Our prow jobs will trigger a script that will process prow_config.yaml
and figure out which workflows to run.
* This will allow us to easily run multiple workflows as part of our E2E tests.
* Fix one source of flakiness in TFJob test
* If we get the status right after creating the TFJob the status might not be set yet
* This was causing wait_for_tfjob to exit with KeyError exception which caused the test
to fail with a very cryptic error message
* We fix this by explicitly allowing for status not being set yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/388)
> Add a prow_config.yaml file to configure our prow jobs.

- cmd/tf-operator/app/server.go
- dashboard/backend/handler/api_handler.go
Addressing https://github.com/kubeflow/tf-operator/issues/395.
There are some errors in our code but it won't caught by the compilers
```commandline
$ go vet $(go list ./... | grep -v /vendor/)
```
Output:
```
cmd/tf-operator/app/server.go:129: unreachable code
exit status 1
dashboard/backend/handler/api_handler.go:36: struct field tfJobs has json tag but is not exported
dashboard/backend/handler/api_handler.go:41: struct field namespaces has json tag but is not exported
exit status 1
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/397)
> Fixes go vet errors

- pkg/controller/controller.go
- py/test_runner.py
- py/tf_job_client.py
* This appears to be a bug with the informer forgetting about active jobs.
* I think the root cause is that delete events are processed directly
as opposed to using the work queue. This causes race conditions because
the work queue is what ensures only on thread is processing a given job
at a time.
* Since we no longer explicitly handle delete events we rely on garbage
collection and owner references to delete the pods.
* We add testing to our test runner to verify pods are garbage collected.
* We update test_runner.py to try recreating jobs with the same name.
In general this doesn't reproduce the original bug.
Related to #322 (to need to push a new image to fix).
Fix #310
Related to #373
--- …
> Fix bug with jobs not working if you recreate a job with same name as previous job

- .travis.yml
adding go 1.10 support
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/402)
> add go 1.10 support in travis

- .style.yapf
- developer_guide.md
- py/build_and_push_image.py
- py/deploy.py
- py/prow.py
- py/prow_test.py
- py/py_checks.py
- py/release.py
- py/release_test.py
- py/test_runner.py
- py/test_util.py
- py/test_util_test.py
- py/tf_job_client.py
- py/util.py
- py/util_test.py
to enforce more consistent code style.
python code changes are all automated by the tool.
I think yapf is better because it is more aggressive with a reasonable default. Ideally I've imagined something opinionated such as https://prettier.io/, and having such a tool means that the code format can only be in one shape. YMMV.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/401)
> use yapf to format python code

- OWNERS
* This will hopefully help us spread the review, approve workload around.
* Related to
kubeflow/community#10
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/414)
> Create an initial OWNERS file.

- dashboard/README.md
https://github.com/kubeflow/tf-operator/issues/411
Add a developer guide for the dashboard.
More doc is ultimately needed, but this is the most pressing part to unblock people from contributing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/417)
> Dashboard: Dev Guide

- py/deploy.py
- py/release_test.py
* We need to stop pinning GKE version to 1.8.5 because that is no longer
a valid version.
* We should no longer need to pin because 1.8 is now the default.
* Fix some lint issues that seem to have crept in.
Fix #240
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/421)
> Fix setup_cluster.

- py/deploy.py
- py/release_test.py
- py/util.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/429)
> format the python files with yapf

- pkg/trainer/replicas.go
- pkg/trainer/replicas_test.go
- pkg/trainer/training.go
This PR is a part of https://github.com/tensorflow/k8s/issues/325:
- rename `jobName()` to `genName()`
- create Pod instead of Job
TODOs (in another PR):
- use `controller.PodControlInterface` and `CreatePodsWithControllerRef` to create Pod
- Listen Pod CRUD and update TFJob status which descried in  https://github.com/tensorflow/k8s/issues/314
@jlewi @gaocegege
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/k8s/344)
> Create Pod instead of Job

- pkg/trainer/training.go
As we have checked `j.job.Status.Phase` [here](https://github.com/kubeflow/tf-operator/blob/master/pkg/trainer/training.go#L312) before calling setup(), these codes can never be reached.
@gaocegege @jlewi PTAL, thanks!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/434)
> Remove unreachable code

- pkg/apis/tensorflow/helper/helpers.go
- pkg/apis/tensorflow/v1alpha1/types.go
- pkg/apis/tensorflow/validation/validation.go
- pkg/trainer/replicas.go
- pkg/trainer/replicas_test.go
The type for the default name of the container is not needed, and the PR is to eliminate it.
/assign @jlewi  @ScorpioCPH 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/432)
> *: Remove type ContainerName

- pkg/apis/tensorflow/v1alpha1/types.go
- pkg/trainer/replicas.go
- pkg/trainer/replicas_test.go
- pkg/trainer/training.go
This commit adds a new field SchedulerName to the definition of TFJob.
The purpose of the field is specifying the scheduler name of the pods
created by tf-operator and let the scheduler (which wouldn't be the
default scheduler) handle them. It would be convenient for letting
kube-batchd (a component of kube-arbitrator) handle the pods.
/cc @jlewi this is a newer version of https://github.com/kubeflow/tf-operator/pull/398
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/408)
> Add a field SchedulerName to TFJob for specifying a scheduler

- py/release.py
- py/util.py
This PR makes `py.release` work correctly on all platforms (important for local releasing for testing).
See comments for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/445)
> Make local release cross-platform + fix

- OWNERS
- dashboard/OWNERS
fix #443.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/446)
> Add OWNERS file for dashboard

- pkg/trainer/replicas.go
- pkg/trainer/replicas_test.go
- pkg/trainer/training.go
Hi, this PR update a little in `Reconcile()` loop:
- Move the `GetStatus()` logic out of `Creation` block.
- Call `GetStatus()` in each reconcile loop to make it more robust.
- set `TFJob.Status.Phase` to `TFJobPhaseRunning` to keep creating resources (services/jobs) only once.
@jlewi @gaocegege @wackxu PTAL.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/418)
> Create resources (Services/Jobs) only once

- cmd/tf-operator/app/server.go
- cmd/tf-operator/main.go
- pkg/controller/controller.go
- pkg/util/k8sutil/k8sutil.go
It seems that the APIExtension client is not used in our code, then we could remove it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/454)
> *: Remove APIExtension clientset

- .travis.yml
Now our coverage test includes generated code and this PR is to remove them from the list of coveralls.
Coverage increased (+16.3%) to 44.86% when pulling e97e51a on gaocegege:test-ignore into 423b0d0 on kubeflow:master.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/453)
> travis: Ignore generated code

- pkg/controller/controller_pod.go
We should not rewrite any user-defined labels, just append tf-operator generated labels.
@gaocegege PTAL.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/468)
> Append labels instead of rewriting

- pkg/apis/tensorflow/v1alpha2/types.go
Hi, this PR make RestartPolicy a property of the ReplicaSpec, as we designed in [proposal](https://github.com/kubeflow/community/blob/master/proposals/tf-operator-design-v1alpha2.md).
@jlewi @gaocegege PTAL :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/473)
> Make RestartPolicy a property of the ReplicaSpec

- pkg/trainer/replicas.go
@gaocegege
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/474)
> add LabelsByIndex method to eliminate code duplication

- cmd/tf-operator/app/options/options.go
- cmd/tf-operator/app/server.go
- pkg/controller/controller.go
- pkg/trainer/training.go
- pkg/trainer/training_test.go
kube-arbitrator (technically its component kube-batchd) requires PDB
for its gang scheduling feature. The feature is useful for creating
every pod of TFJob at the same time. This commit lets tf-operator
create the PDB for the purpose.
The change isn't tested yet for now (I will be able to test it with a working k8s cluster probably next week...). I'm glad if I can have feedback about the design, especially the usage of kube-arbitrator.
/cc @jlewi @gaocegege @ScorpioCPH @k82cn @jinzhejz
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/452)
> Create PDB of TFReplicaSet for gang scheduling by kube-arbitrator

- pkg/controller/controller.go
- pkg/controller/controller_pod.go
- pkg/controller/controller_test.go
Now we do not update the status because we return error before the update function call. Then I changed the behaviour.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/476)
> controller: Update status in time

- pkg/controller/controller_pod.go
- pkg/controller/controller_service.go
- pkg/controller/controller_test.go
We do not separate the pods of PS and workers in the controller, then it has bugs when the replicas are succeeded.
If the PR LGTM, I will file another PR for service.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/481)
> controller: Separate ps and worker pods

- test/e2e/sleep-and-random-exit/Dockerfile
- test/e2e/sleep-and-random-exit/sleep-and-random-exit.sh
Hi, this PR add an image for e2e test:
- Run a script that sleep a random seconds.
- Then exit a random code:
- Exit 0 means this pod is `succeeded`.
- Exit nonzero means this pod is `failed`.
We can use this image to count active/failed/succeeded pods.
@jlewi @gaocegege PTAL, thanks!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/487)
> Add sleep and random exit image for e2e test

- pkg/controller/controller_pod.go
Hi, this PR set the `RestartPolicy` of `Pod`.
@gaocegege PTAL.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/491)
> Set restart policy

- test/e2e/dist-mnist/Dockerfile
- test/e2e/dist-mnist/README.md
- test/e2e/dist-mnist/build_dist_mnist.sh
- test/e2e/dist-mnist/dist_mnist.py
Hi, this PR add a distributed mnist model for e2e test:
- Read environment variable `TF_CONFIG` to create TensorFlow `ClusterSpec`.
- Create TFJob with this model.
@gaocegege @jlewi PTAL, thanks!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/493)
> Add dist-mnist for e2e test

- cmd/tf-operator/app/options/options.go
This PR set JSONLogFormat to false by default for debug.
@gaocegege PTAL.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/495)
> Set JSONLogFormat to false by default

- pkg/controller/controller.go
- pkg/trainer/replicas.go
- pkg/trainer/training.go
- py/test_runner.py
- py/tf_job_client.py
- test/workflows/components/workflows.libsonnet
Fix several bugs with the job controller.
* A bug was introduced with getting the replica status in #344 which
switched to creating pods directly.
* Our presubmits/postsubmits were failing but this went unnoticed because
the git status check was improperly reported as succeeded.
* One bug is because we try to get the pod status by name but the name
doesn't include the random salt in the pod name.
* The code in question is a legacy of when we were using job controllers and
we first got the status of the job controller. We incorrectly changed that
code to get the pod. The correct thing is to just list pods by label; we
already do that in the code below so we just need to delete some code.
* A second bug is a problem with deleting resources.
* Once a job is marked for deletion we shouldn't …
> Fix bug with jobs not being marked as completed.

- pkg/apis/tensorflow/v1alpha2/types.go
- pkg/controller/controller.go
- pkg/controller/controller_pod.go
- pkg/controller/controller_test.go
Hi, this PR add the condition logic without UT.
@jlewi @gaocegege @yph152 @DjangoPeng @ddysher PTAL, thank!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/504)
> Add condition logic code

- pkg/trainer/replicas.go
- pkg/trainer/training.go
- py/test_runner.py
- test/workflows/components/workflows.libsonnet
* We originally did this to preserve the logs.
* But this ends up leaving pods running consuming resources.
* The fix is straightforward
* Transition to the cleanup phase before transitioning to the done phase.
* Update the E2E test to verify
* Events are recorded for the pod/service creations and we observe the correct number
* Pods are deleted when job is done (but not deleted)
Fix #128
Fix #317 Test for event recorder
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/512)
> Don't leave pods running when a job completes.

- hack/genjob/genjob.go
This command adds a new command genjob to hack/ directory. The command
generates TFJobs for testing purpose. Currently the generated jobs are
following the definitions of examples/tf_job.yaml and
examples/tf_job_gpu.yaml.
Example usage (generating 30 TFJobs):
```
$ ./genjob --kube-config-path ~/.kube/config --nr-tfjobs 30 --use-gpu --scheduler-name tfjob
```
I think the command is useful for testing tf-operator and kube-batchd. The remaining major todo is adding more realistic TFJob (especially distributed examples).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/509)
> RFC: Add a new command for generating example TFjobs

- pkg/trainer/replicas_test.go
Just had some minor confusion with this and wanted to prevent for others.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/511)
> Fix output on test failure

- .gcloudignore
Motivation for this is to not upload the entire vendor directory (or other potentially unecessary files) when building a container
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/510)
> Adds gcloudignore

- test/workflows/components/workflows.libsonnet
The code to disable the onExit handler should not have been committed
Fix #560
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/520)
> Reenable cluster teardown.

- developer_guide.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/528)
> developer_guide: Add instructions for v1alpha2

- pkg/trainer/training.go
The original code will let the controller keep creating new pdb for the job since the names are not the same. 
They only have the same prefix which is GenerateName: "tf-job-pdb-".
I try to fix it by assigning the name, "tf-job-pdb-" + j.job.ObjectMeta.Name, to the pdb in order to make controller only create pdb once.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/539)
> fix the bug of keeping creating new pdb

- pkg/trainer/replicas.go
- pkg/trainer/replicas_test.go
there is no reason to drop pod's labels and annotations from tfjob's PodTemplateSpec
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/542)
> copy labels and anotations to pod from pod template

- .travis.yml
- cmd/tf-operator.v2/app/options/options.go
- cmd/tf-operator.v2/app/server.go
- cmd/tf-operator.v2/main.go
- cmd/tf-operator/app/server.go
- linter_config.json
- pkg/controller.v2/controller.go
- pkg/controller.v2/controller_logger.go
- pkg/controller.v2/controller_pod.go
- pkg/controller.v2/controller_pod_test.go
- pkg/controller.v2/controller_ref_manager.go
- pkg/controller.v2/controller_service.go
- pkg/controller.v2/controller_service_test.go
- pkg/controller.v2/controller_tensorflow.go
- pkg/controller.v2/controller_test.go
- pkg/controller.v2/controller_utils.go
- version/version.go
/assign @ddysher @DjangoPeng @jlewi @mitake @ScorpioCPH 
This PR is the implementation of v1alpha2 and it is mainly contributed by @ScorpioCPH  and @gaocegege
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/526)
> v1alpha2: Add implementation

- pkg/trainer/training.go
- pkg/trainer/training_test.go
Hi, after fixing the name of ObjectMeta of PDB.
I think we could add the OwnerReferences to PDB too.
This enable the Kubernetes GC to automatically delete the PDB  when users delete the tfjob manually.
Thanks!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/565)
> add OwnerReferences to pdb

- py/release.py
In `py/release.py`, an info logging uses a placeholder, but no string matches that.
This PR completes that missing string.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/570)
> Fix missing string for logging placeholder

- developer_guide.md
Since we have changed from glide to dep, we should update the developer guide.
Thanks!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/572)
> replace glide with dep in the developer guide

- .travis.yml
> TravisBuddy will comment on pull requests in your public repository everytime a test failed in one of them. The comment will include only the part of the build log that applies to your testing framework, so your contributors won't have to enter Travis's website and search the long and annoying build log for the reason the tests failed. 
It will help us to know the failures of Travis builds in GitHub notification page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/579)
> .travis.yml: Add failure notification in GitHub

- test/e2e/dist-mnist/Dockerfile
- test/e2e/dist-mnist/README.md
- test/e2e/dist-mnist/dist_mnist.py
Hi, after v1alpha2 code merged, we need some e2e test for this new API.
This PR import distributed mnist model for e2e test, @gaocegege @jlewi PTAL, thanks!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/549)
> Add dist mnist model for e2e test

- .pylintrc
Fix test failures in #549 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/581)
> .pylinrc: Add dist_mnist

- .travis.yml
Fix the gometalinter support
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/587)
> Fix the gometalinter support

- py/release.py
By default, the release function will use gcloud to push the image. But the user not using gcloud command-tool cannot push the image to the registry. I think it's better to add an optional argument to allow user pushing the image with docker.
Add --push_with_docker argument for release.py. When using --push_with_docker, the release will use docker to push the image.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/595)
> Add a new command-line argument for release.py

- build/images/tf_operator/Dockerfile
- py/release.py
* We need to add the tf-operator.v2 to release.py so that we can start building Docker images containing the new controller.
Fix #600
/assign @gaocegege
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/601)
> Add tf-operator.v2 to release.py so that we build a Docker image containing the v1alph2 controller

- py/tf_job_client.py
* TFJob wait should run the request asyncronously so we don't end up blocking
forever.
Fix #606
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/607)
> TFJob client should not block forever trying to get the namespace object

- examples/crd/crd-v1alpha2.yaml
/assign @jlewi @ScorpioCPH 
The feature is restricted and I only add validation for replicas. This avoids the crash problem when replicas < 0.
related to: kubeflow/tf-operator#437
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/605)
> crd: Add validation using OpenAPI 3.0

- pkg/controller.v2/controller.go
- pkg/controller.v2/controller_pod.go
- pkg/controller.v2/controller_service.go
\assign @ScorpioCPH 
This PR is to refactor the code related to service as #548 does.
>
>- To make the controller more robust we don't want to assume that if there are N services and N replicas that everything is ok.
>- Instead what this PR is doing is for each replica index, checking all services corresponding to that replica (based on labels) and deciding whether services need to be created, deleted, or no action is needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/603)
> service: Refactor to the slice structure

- pkg/controller.v2/controller_helper.go
- pkg/controller.v2/controller_service.go
- pkg/controller.v2/controller_tensorflow.go
Close #574 
We use the DNS record instead of service name to do service discovery, and use headless to lower the overhead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/576)
> controller_service: Headless service

- pkg/apis/tensorflow/v1alpha2/constants.go
- pkg/apis/tensorflow/v1alpha2/defaults.go
- pkg/apis/tensorflow/v1alpha2/defaults_test.go
- pkg/controller.v2/controller.go
- pkg/controller.v2/controller_helper.go
- pkg/controller.v2/controller_pod.go
- pkg/controller.v2/controller_service.go
- pkg/controller.v2/controller_tensorflow.go
- pkg/controller.v2/controller_tfjob_test.go
- test/e2e/dist-mnist/tj_job_mnist.yaml
This PR is to close #532 
We have two hard coded name: tensorflow for container and tfjob-port for port name
We will set the default value for the port if we do not get it from the spec.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/621)
> pkg: Support customized port

- py/test_runner.py
Related https://github.com/kubeflow/kubeflow/issues/852
/assign @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/627)
> Use logging.exception to capture stack traces in logs

- py/test_runner.py
- py/tf_job_client.py
- test/workflows/components/simple_tfjob.jsonnet
* Update test_runner.py to track new fields in version v1alpha2 for TFJob
* Update simple_tfjob.jsonnet with new TFJob spec for v1alpha2
/assign @gaocegege 
Related https://github.com/kubeflow/kubeflow/issues/852
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/629)
> Updates to enable e2e test for v1alpha2

- pkg/apis/tensorflow/v1alpha2/types.go
- pkg/controller.v2/controller_pod.go
Recreate pods when the exit code is retryable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/638)
> pods: Add restart policy

- developer_guide.md
- examples/crd/crd-v1alpha2.yaml
- pkg/apis/tensorflow/v1alpha2/types.go
- pkg/controller.v2/controller_tensorflow.go
When using `Estimator` and `tf.estimator.train_and_evaluate` for distributed task,
the `evaluator` should not be included in the cluster spec.
> Example of evaluator node (evaluator is not part of training cluster):
>
> ``` python
>   cluster = {'chief': ['host0:2222'],
>              'ps': ['host1:2222', 'host2:2222'],
>              'worker': ['host3:2222', 'host4:2222', 'host5:2222']}
>   os.environ['TF_CONFIG'] = json.dumps(
>       {'cluster': cluster,
>        'task': {'type': 'evaluator', 'index': 0}})
>   config = RunConfig()
>   assert config.master == ''
>   assert config.evaluator_master == ''
>   assert config.task_id == 0
>   assert config.num_ps_replicas == 0
>   assert config.num_worker_replicas == 0
>   assert config.cluster_spec == {}
>   assert config.task_type == …
```
> [v1alpha2] Estimator support -  Do not include `evaluator` in cluster spec

- pkg/controller.v2/controller_pod.go
- pkg/controller.v2/controller_status.go
- pkg/controller.v2/controller_status_test.go
- pkg/controller.v2/controller_tfjob.go
- pkg/controller.v2/controller_tfjob_test.go
- Add test cases for chief worker and ps/worker status update.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/643)
> status: Add test cases for failure

- pkg/controller.v2/controller_pod.go
- pkg/controller.v2/controller_pod_test.go
- Submit an event when the user specifies the restartpolicy for pod template.
- Add ut for restart policy
/assign @jlewi 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/648)
> pod: Submit an event when the user specifies the restartpolicy for pod template

- pkg/controller.v2/controller_pod_test.go
- pkg/controller.v2/pod_control.go
Add a test to test if the pod will be deleted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/652)
> pod: Add test for exit code

- pkg/apis/tensorflow/v1alpha2/defaults.go
- pkg/apis/tensorflow/v1alpha2/defaults_test.go
Add a default function to rename types to the right types.
E.g. from ps to PS, from WORKER to Worker.
Close #668 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/669)
> defaults: Rename the type

- .travis.yml
- pkg/controller.v2/controller_pod.go
- pkg/controller.v2/controller_pod_test.go
- pkg/controller.v2/controller_service.go
- pkg/controller.v2/controller_service_test.go
- pkg/controller.v2/controller_status.go
- pkg/controller.v2/controller_status_test.go
- pkg/controller.v2/controller_tensorflow.go
- pkg/controller.v2/controller_test.go
- pkg/controller.v2/controller_tfjob.go
- pkg/controller.v2/controller_tfjob_test.go
- pkg/controller.v2/pod_control_test.go
- pkg/controller.v2/service_control_test.go
- pkg/controller.v2/service_ref_manager_test.go
- pkg/generator/generator.go
- pkg/generator/generator_test.go
- pkg/util/testutil/const.go
- pkg/util/testutil/pod.go
- pkg/util/testutil/service.go
- pkg/util/testutil/tfjob.go
- pkg/util/testutil/util.go
Move the util functions about test to a separate package.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/666)
> *: Move test util to separate package

- pkg/control/pod_control.go
- pkg/control/pod_control_test.go
- pkg/control/service_control.go
- pkg/control/service_control_test.go
- pkg/control/service_ref_manager.go
- pkg/control/service_ref_manager_test.go
- pkg/controller.v2/controller.go
- pkg/controller.v2/controller_pod.go
- pkg/controller.v2/controller_service.go
- pkg/controller.v2/controller_test.go
Close #665 
Move the PodControl and ServiceControl out of controller package.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/670)
> controller: Move control interface to control package

- pkg/controller.v2/informer.go
this is to fix: #641
func `tfJobFromUnstructured` may not recognize the spec area, `tfjob.Spec.TFReplicaSpecs` will be nil then, this logic should be considered to be err and stop sync.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/678)
> return err if the spec area is nil after unmashal for tfjob v1alpha2

- pkg/controller.v2/controller.go
- pkg/controller.v2/controller_pod.go
- pkg/controller.v2/controller_status.go
- pkg/controller.v2/controller_status_test.go
/cc @gaocegege @ddysher @DjangoPeng  
I have a submission for v1alpha2 status management
#562
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/625)
> [v1alpha2] Add distributed state management

- pkg/controller.v2/controller.go
- pkg/controller.v2/controller_status.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/683)
> and some safety check

- pkg/generator/generator.go
- pkg/generator/generator_test.go
- py/test_runner.py
* tf_job_name is consistent with v1alpha1; this desirable from a compatibility
perspective.
* tf_job_key isn't quite right because the job key includes namespace
but we are no longer using the namespace in the value
Related to #672
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/689)
> Use tf_job_name not tf_job_key as the label name.

- examples/tf_job_clean_policy.yaml
- pkg/apis/tensorflow/v1alpha1/types.go
- pkg/trainer/replicas.go
- pkg/trainer/training.go
- Add cleanupPodPolicy when the v1alpha1 TFJob is succeed or failed
- The cleanupPodPolicy contains:
- All: the default behavior which is the same with the current behavior. it will  delete all the resources related to the TFJob object
- Running: delete running pods and reserve succeed/failed pod for checking logs. Since non-running pod will not consume any GPU/CPU/Memory resource, while the important info always keeps in the log of succeed/failed pod 
- None: keep all the resources for further investigation
The motivation of doing this is it's we'd like to provide flexibility to the end user to handle the resources when TFJob is done. 
Signed-off-by: cheyang <cheyang@163.com>
--- …
> define cleanup policy

- pkg/control/service_control.go
fix #635 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/695)
> Use logrus instead of glog in service_control

- pkg/controller.v2/controller_pod_test.go
- pkg/controller.v2/controller_tensorflow.go
- pkg/generator/generator.go
Hi, this PR fix https://github.com/kubeflow/tf-operator/issues/703 when we change to headless service.
@gaocegege PTAL.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/704)
> Fix sub domain issue

- pkg/apis/tensorflow/validation/validation.go
- pkg/apis/tensorflow/validation/validation_test.go
fix #707 
/cc gaocegege
Signed-off-by: Pengyu Chen <chenpengyu@caicloud.io>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/711)
> [v1alpha2] Add more validation of TFJobSpec

- cmd/tf-operator.v2/app/options/options.go
- cmd/tf-operator.v2/app/server.go
- pkg/controller.v2/controller.go
- pkg/controller.v2/controller_pod_test.go
- pkg/controller.v2/controller_service_test.go
- pkg/controller.v2/controller_test.go
- pkg/controller.v2/controller_tfjob_test.go
fix #575 
Signed-off-by: Pengyu Chen <chenpengyu@caicloud.io>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/717)
> [v1alpha2] Add PDB of TFReplicaSet for gang scheduling by kube-arbitrator

- pkg/controller.v2/controller.go
- pkg/controller.v2/controller_tfjob.go
As title, we should also delete pdb when tfjob is terminated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/721)
> delete pdb when tfjob is terminated

- pkg/trainer/training.go
Info should be Infof
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/724)
> Fix a log function issue

- py/tf_job_client.py
Saw:
```
conditions = [c.get("type", "") for c in all_conditions]
TypeError: 'NoneType' object is not iterable
```
from e2e test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/735)
> test fix: None type check

- pkg/controller.v2/controller.go
this fix the issue in #727 
If the err is errNotExists, then we can simply print the information and return directly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/734)
> fix not proper log message

- pkg/apis/tensorflow/v1alpha2/types.go
- pkg/apis/tensorflow/v1alpha2/zz_generated.deepcopy.go
- pkg/controller.v2/controller.go
- pkg/controller.v2/controller_status.go
this implements #718
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/725)
> cleanup jobs after finished

- py/tf_job_client.py
* We observed conditions have a value of None in status. So explicitly
guard against that.
Fix #744 
/assign @richardsliu
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/745)
> Fix a test flake caused by conditions being None

- pkg/apis/tensorflow/v1alpha2/types.go
- pkg/apis/tensorflow/v1alpha2/zz_generated.deepcopy.go
- pkg/controller.v2/controller.go
- pkg/controller.v2/controller_status.go
This reverts commit 0b9d4227f4ed5f77c9eba3d2317892376fe22e67.
Discussion for why we are reverting in #718 [see comment](https://github.com/kubeflow/tf-operator/issues/718#issuecomment-406500117)
To summarize
1. Adding CleanPodDelay doesn't really solve the problem of garbage collecting old jobs
1. CleanPodDelay isn't really a great solution for preserving logs from pods; a better solution is cluster logging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/746)
> Revert "cleanup jobs after finished (#725)"

- pkg/apis/tensorflow/v1alpha2/types.go
- pkg/apis/tensorflow/v1alpha2/zz_generated.deepcopy.go
- pkg/controller.v2/controller.go
- pkg/controller.v2/controller_tfjob.go
- pkg/controller.v2/controller_tfjob_test.go
- pkg/util/testutil/tfjob.go
If the ttl is not set, the tf-job will not be cleaned up
This is a temporary solution before the ``cleanup controller'' is implemented
in kubernetes.
#718
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/753)
> Cleanup tf-job after a configured TTL

- cmd/tf-operator.v2/app/options/options.go
- pkg/controller.v2/controller.go
- pkg/controller.v2/controller_logger.go
- pkg/controller.v2/controller_pod.go
- pkg/controller.v2/controller_tfjob.go
- pkg/controller.v2/informer.go
* Use <namespace>.<name> as opposed to <namespace>/<name>; the former
is more consistent with K8s style.
* Add functions for constructing loggers for the pod and unstructured meta
information. This will allow us to appropriately tag a number of log
messages with meta information.
* Update a bunch of log messages which weren't logging info with
appropriate meta information.
* Make json log formatting the default; this was the case for v1.
json logging should be the default because otherwise we lose the meta
information in the logs. With json logs its always possible to filter/reformat
the log entries if you don't care about the metainformation.
Related to:
#24 Use logrus
#635
--- …
> Improve meta information in log messages to make it easier to debug jobs

- py/test_runner.py
- py/tf_job_client.py
- py/util.py
* Now that #673 is fixed wait_for_job for v1alpha2 should for condition Succeeded or failed.
* If there is a timeout waiting for the job to finish include the job spec
in the exception so we can print it out to see what the final status is.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/771)
> WaitForJob should use conditions for v1alpha2.

- pkg/apis/tensorflow/v1alpha2/openapi_generated.go
Signed-off-by: JetMuffin <mofeng.cj@alibaba-inc.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/769)
> OpenAPI: update openapi_generated.go to support TTLSecondsAfterFinished

- examples/tf_sample/Dockerfile
- examples/tf_sample/tf_smoke.py
- py/test_runner.py
- test/workflows/components/simple_tfjob_v1alpha2.jsonnet
Related to #778
Update the docker image used by the E2E test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/779)
> Add retries to deal with test flakes related to UnavailableError.

- cmd/tf-operator.v2/app/server.go
- pkg/controller.v2/tfcontroller/informer.go
- pkg/controller.v2/tfcontroller/pod.go
- pkg/controller.v2/tfcontroller/pod_test.go
- pkg/controller.v2/tfcontroller/service.go
- pkg/controller.v2/tfcontroller/service_test.go
- pkg/controller.v2/tfcontroller/status.go
- pkg/controller.v2/tfcontroller/tfcontroller.go
- pkg/controller.v2/tfcontroller/tfcontroller_test.go
- pkg/controller.v2/tfcontroller/tfjob.go
- pkg/controller.v2/tfcontroller/tfjob_test.go
TFJobController is renamed to TFController for consistency. 
From https://github.com/kubeflow/tf-operator/pull/776#issuecomment-412421051
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/777)
> Renaming TFJobController to TFController

- Gopkg.lock
- cmd/tf-operator.v2/app/options/options.go
- cmd/tf-operator.v2/app/server.go
- pkg/controller.v2/tfcontroller/informer.go
- pkg/controller.v2/tfcontroller/tfcontroller_test.go
Based on the KUBEFLOW_NAMESPACE, tf-operator will be scoped to a
particular namespace.
If `--namespace` flag is not set or left as empty, tf-operator will be
scoped to cluster-wide. If it is set to a namespace value, tf-operator
will only operate in the namespace
Fixes #759
/cc @gaocegege @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/789)
> Scope tf-operator to a namespace

- cmd/tf-operator.v2/app/options/options.go
- pkg/apis/tensorflow/v1alpha2/types.go
- pkg/controller.v2/tfcontroller/pod.go
We have enablingGangScheduling option, so we add schedulerName option to TFJobSpec.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/787)
> Add SchedulerName in V1alpha2

- cmd/tf-operator.v2/app/options/options.go
- pkg/controller.v2/jobcontroller/pod.go
- pkg/controller.v2/jobcontroller/service.go
- pkg/controller.v2/tfcontroller/pod.go
- pkg/controller.v2/tfcontroller/service.go
Moving common utility functions to the base
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/792)
> Restructing common utility functions

- pkg/controller.v2/tfcontroller/tfjob.go
Found that reconcileTFJobs continuously gets triggered even with no update.
This patch fixes that
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/796)
> reconcileTFJobs is always triggered even with no update

- pkg/apis/tensorflow/v1alpha2/openapi_generated.go
- pkg/apis/tensorflow/v1alpha2/types.go
The field name is ttlSecondsAfterFinished, but the 'json field' name is ttlSecondsAfterFinishing.
This patch makes them consistent to be ttlSecondsAfterFinished
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/799)
> Typo in TTLSecondsAfterFinished json field

- pkg/controller.v2/jobcontroller/pod.go
- In AddPod, it logs "This pod's job does not exist" even for non-TFJob pod. we only need to log for TFJob pod.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/798)
> Avoid logging for non-TFJob pod

- pkg/controller.v2/tfcontroller/tfjob.go
Close #800
This reverts commit 554d750962e73d8b1514b42c8d6cfa93c9762bbb.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/805)
> Revert "Avoid triggering reconcileTFJobs if no TFJob update (#796)"

- OWNERS
Since operator implementations are closely related, I will port required PRs to pytorch repo and vice versa.  
/assign @gaocegege @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/808)
> Adding to Owners

- pkg/apis/tensorflow/v1alpha2/defaults.go
- pkg/apis/tensorflow/v1alpha2/types.go
- pkg/apis/tensorflow/v1alpha2/util.go
- pkg/apis/tensorflow/v1alpha2/util_test.go
- pkg/apis/tensorflow/validation/validation.go
- pkg/apis/tensorflow/validation/validation_test.go
- pkg/controller.v2/tfcontroller/status.go
- pkg/controller.v2/tfcontroller/tfcontroller.go
- pkg/controller.v2/tfcontroller/util.go
Support Master spec similar to Chief
Close #794
/assign @johnugeorge @jlewi 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/809)
> tensorflow: Support old versions of estimator

- pkg/controller.v2/tfcontroller/pod.go
- pkg/controller.v2/tfcontroller/tfjob.go
- pkg/logger/logger.go
* I ran into these issues while trying to understand why my job was
marked as failed even though there was no useful informatin about
why the pod failed.
* Log events that indicate exit code of pods.
* In the json payload use the syntax namespace + "." + name not
namespace + "/" + name; use of a period is more consistent in K8s
* Don't log an event TFJob is terminated, deleting pods and services;
this event ends up being triggered repeatedly because of CleanPodPolicy
the number of completed pods is non zero so the event statement kept
getting called; the event is unnecessary because we will create
events corresponding to actual services/events deleted.
--- …
> Fix a bunch of issues with logging.

- cmd/tf-operator.v2/app/server.go
- pkg/controller.v2/jobcontroller/jobcontroller.go
- pkg/controller.v2/tensorflow/controller.go
- pkg/controller.v2/tensorflow/controller_test.go
- pkg/controller.v2/tensorflow/informer.go
- pkg/controller.v2/tensorflow/job.go
- pkg/controller.v2/tensorflow/job_test.go
- pkg/controller.v2/tensorflow/pod.go
- pkg/controller.v2/tensorflow/pod_test.go
- pkg/controller.v2/tensorflow/service.go
- pkg/controller.v2/tensorflow/service_test.go
- pkg/controller.v2/tensorflow/status.go
- pkg/controller.v2/tensorflow/status_test.go
- pkg/controller.v2/tensorflow/tensorflow.go
- pkg/controller.v2/tensorflow/util.go
- pkg/controller.v2/tensorflow/util_test.go
1. Renaming tfcontroller to tensorflow (it is already in controller folder). Naming is now consistent with the Pytorch repo
2. Removed GetTotalReplicas from Controller interface as it is not necessary for all operators.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/812)
> Minor restructuring

- cmd/tf-operator.v2/app/server.go
- pkg/controller.v2/jobcontroller/pod.go
One error log appears during the leader election at startup.  
`Could not construct reference to: '&v1.Endpoints{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"tf-job-operator", GenerateName:"", Namespace:"default", SelfLink:"/api/v1/namespaces/default/endpoints/tf-job-operator", UID:"feb0f9ab-6e64-11e8-bdd9-42010aa00072", ResourceVersion:"18879593", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:63664420868, loc:(*time.Location)(0x1b5df80)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string{"control-plane.alpha.kubernetes.io/leader":"{\"holderIdentity\":\"tf-job-operator-5864544fcb-d8c9m\",\"leaseDurationSeconds\":15,\"acquireTime\":\"2018-09-03T12:2 …
> Adding corev1 scheme to Events

- test/workflows/components/workflows.libsonnet
* Fix #816
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/817)
> Set artifacts dir so that the output of invalid-job test will be picked up.

- pkg/apis/tensorflow/v1alpha2/types.go
- pkg/controller.v2/tensorflow/pod.go
According to the discussion in #801 , we remove the schedulerName from tfjob spec to prevent confusing users.
Fixed #801
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/823)
> remove schedulerName from tfjob spec

- py/test_runner.py
- py/util.py
- test/test-server/Dockerfile
- test/test-server/test_app.py
- test/workflows/components/estimator_runconfig.jsonnet
- test/workflows/components/params.libsonnet
- test/workflows/components/workflows.libsonnet
Related to #762 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/814)
> Estimator e2etest

- pkg/util/k8sutil/k8sutil.go
The unused functions are removed. K8sutil package must contain only k8s utility functions and has to be independent of tf code. It can be then shared across operators
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/827)
> Cleanup unused functions

- dashboard/backend/main.go
the log always print `ERROR: logging before flag.Parse if `
this fix it 
Note: need add  flag  -logtostderr=true when  start  backend ,if you want  it to work like before
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/834)
> fix ERROR: logging before flag.Parse issue

- py/k8s_util.py
- py/ks_util.py
- py/test_invalid_job.py
- py/test_runner.py
- py/tf_job_client.py
This is part 1 of the work to refactor E2E tests and make them easier to write.
This part removes the common util methods from test_runner.py and places them in helper libraries.
- k8s_util for operations with k8s (e.g. services, pods)
- tf_job_client for interacting with the TFJob resource(including replicas)
- ks_util for operations with ksonnet
Next steps:
- Remove the v1alpha1 tests
- Refactor the methods specific to shutdown policy, runtime config, and clean pod policy to separate test runner classes
- Create a buildTestTemplate function in workflows.libsonnet.
The long term plan is each test should be in a self-contained python file that creates a tfjob, executes some commands, and verify results. Boiler plate code should be reduced to a minimum.
---
This change is [<img …
> Refactor E2E tests (part 1)

- py/test_runner.py
For tests like the minikube e2e test in kubeflow/kubeflow, it does not make sense to run every test in a suite. We should be able to skip the GPU tests, for example.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/853)
> Add the ability to skip a E2E test

- examples/distribution_strategy/Dockerfile
- examples/distribution_strategy/Makefile
- examples/distribution_strategy/README.md
- examples/distribution_strategy/distributed_tfjob.yaml
- examples/distribution_strategy/keras_model_to_estimator.py
Fixes #843
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/860)
> Add an example for TF distributed training

- py/distributed_training_tests.py
- test/workflows/components/distributed_training_v1alpha2.jsonnet
- test/workflows/components/params.libsonnet
- test/workflows/components/workflows.libsonnet
Fixes #842
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/862)
> Add an e2etest for running distributed training TFJob

- developer_guide.md
Notice there's a typo in develop guide, should be `_` rather than `-`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/878)
> Fix typo in developer_guide.md

- py/build_and_push_image.py
- py/cleanpod_policy_tests.py
- py/deploy.py
- py/distributed_training_tests.py
- py/estimator_runconfig_tests.py
- py/invalid_tfjob_tests.py
- py/k8s_util.py
- py/ks_util.py
- py/py_checks.py
- py/release.py
- py/release_test.py
- py/replica_restart_policy_tests.py
- py/shutdown_policy_tests.py
- py/simple_tfjob_tests.py
- py/test_runner.py
- py/tf_job_client.py
- py/util.py
- test/workflows/components/params.libsonnet
- test/workflows/components/replica_restart_policy_always_v1alpha2.jsonnet
- test/workflows/components/replica_restart_policy_always_v1beta1.jsonnet
- test/workflows/components/replica_restart_policy_exitcode_v1alpha2.jsonnet
- test/workflows/components/replica_restart_policy_exitcode_v1beta1.jsonnet
- test/workflows/components/replica_restart_policy_never_v1alpha2.jsonnet
- test/workflows/components/replica_restart_policy_never_v1beta1.jsonnet
- test/workflows/components/replica_restart_policy_onfailure_v1alpha2.jsonnet
- test/workflows/components/replica_restart_policy_onfailure_v1beta1.jsonnet
- test/workflows/components/workflows.libsonnet
Fixes #639
This PR does the following things:
1. add replicas restart policy test by comparing the start time of the container in the pod
2. fixed the pod_selector in py/tf_job_client.py by modifying
`labels["tf-replica-type"] = replica_type` to
`labels["tf-replica-type"] = str.lower(replica_type)`
3. wait a time interval before fetching the pods' phase in py/k8s_util.py
4. fixed bugs in clean pod policy test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/873)
> Add an e2etest for testing restart policy

- build/images/tf_operator/Dockerfile
Presubmits were failing due to Go installation error:
```
Step 2/15 : ENV GOLANG_VERSION 1.8.3
---> Running in b613b7584fbe
Removing intermediate container b613b7584fbe
---> 966d561c20b7
Step 3/15 : RUN yum -y install go && yum clean all
---> Running in 3e92d32ce757
Loaded plugins: fastestmirror, ovl
Determining fastest mirrors
* base: mirrors.ocf.berkeley.edu
* extras: mirrors.ocf.berkeley.edu
* updates: mirror.sjc02.svwh.net
No package go available.
Error: Nothing to do
The command '/bin/sh -c yum -y install go && yum clean all' returned a non-zero code: 1
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/docker" failed: exit status 1
```
Fix is to install Go (same version) manually. …
> Fix tf-operator presubmit failures by installing go manually

- examples/v1beta1/mnist_with_summaries/Dockerfile
- examples/v1beta1/mnist_with_summaries/README.md
- examples/v1beta1/mnist_with_summaries/mnist_with_summaries.py
- examples/v1beta1/mnist_with_summaries/tf_job_mnist.yaml
- examples/v1beta1/mnist_with_summaries/tfevent-volume/tfevent-pv.yaml
- examples/v1beta1/mnist_with_summaries/tfevent-volume/tfevent-pvc.yaml
Adding a simple example (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/tutorials/mnist/mnist_with_summaries.py) that uses MNIST model with TF summary. The summary is written to a persistent volume. This is to be used with components like katib.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/880)
> Add mnist example with TF summary

- .travis.yml
In the docker image, there are three binaries, but travis ci only builds two of them.
Adding the backend binary to travis ci to improve the ci build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/892)
> build backend in travis ci

- pkg/apis/tensorflow/v1beta1/util.go
- pkg/controller.v1beta1/tensorflow/controller.go
- pkg/controller.v1beta1/tensorflow/pod.go
New master role label is set in the pod which acts as master of the job.   In katib, this label is useful to track the master who is responsible for logging. 
Sets new label 'tf_job_role':'master' to the
1.  master pod if master pod is present
2. first worker pod if master pod is not present
Related: https://github.com/kubeflow/katib/issues/294
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/896)
> Adding master role label 

- pkg/apis/tensorflow/v1alpha2/util.go
- pkg/apis/tensorflow/v1beta1/util.go
- pkg/apis/tensorflow/validation/validation.go
- pkg/apis/tensorflow/validation/validation_test.go
Add validation for evaluator so that the number of evaluator
should no more than 1.
Close #894
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/895)
> Add validation for evaluator

- pkg/controller.v1beta1/tensorflow/controller.go
- pkg/controller.v1beta1/tensorflow/informer.go
- pkg/controller.v1beta1/tensorflow/job.go
Fix has been ported to v1beta1 code.
Initial PR: #890
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/899)
> Minor fixes

- .travis.yml
- cmd/tf-operator.v1beta1/app/server.go
- cmd/tf-operator.v2/app/server.go
- linter_config.json
- pkg/apis/tensorflow/v1alpha2/defaults.go
- pkg/apis/tensorflow/v1beta1/defaults.go
- pkg/apis/tensorflow/validation/validation.go
- pkg/control/service_control.go
- pkg/control/service_ref_manager_test.go
- pkg/controller.v1beta1/tensorflow/controller.go
- pkg/controller.v1beta1/tensorflow/informer.go
- pkg/controller.v1beta1/tensorflow/pod.go
- pkg/controller.v1beta1/tensorflow/service.go
- pkg/controller.v1beta1/tensorflow/util.go
- pkg/controller.v2/tensorflow/controller.go
- pkg/controller.v2/tensorflow/informer.go
- pkg/controller.v2/tensorflow/pod.go
- pkg/controller.v2/tensorflow/service.go
- pkg/controller.v2/tensorflow/util.go
- pkg/util/k8sutil/k8sutil.go
This PR addresses Travis CI build failure by fixing below items.
1. Upstream gometalinter removed gosimple [here](https://github.com/alecthomas/gometalinter/commit/96c7e2a871d86b852b5d76f76e365b3a63e7dcaa)
2. Removing support for go@1.8 Travis CI test.
3. Adding back gotype as it was removed in (#254) due to go@1.8 support.
4. Increased the deadline timeout to 500s as go@1.9 Travis CI test sometimes takes more than 300s.
5. Refactored code to align with staticcheck warnings.
Signed-off-by: Abhilash Pallerlamudi <stp.abhi@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/919)
> Remove gosimple, go 1.8 and add gotype

- dashboard/backend/handler/api_handler.go
- pkg/common/jobcontroller/jobcontroller.go
- pkg/common/util/v1beta1/testutil/util.go
- pkg/common/util/v1beta2/testutil/util.go
- pkg/controller.v1beta1/tensorflow/controller.go
- pkg/controller.v1beta1/tensorflow/controller_test.go
- pkg/controller.v1beta2/tensorflow/controller.go
- pkg/controller.v1beta2/tensorflow/controller_test.go
- py/kubeflow/tf_operator/tf_job_client.py
Related: https://github.com/kubeflow/pytorch-operator/issues/140
All labels are renamed to use hyphens instead of underscores.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/951)
> Renaming the labels to consistent format

- cmd/tf-operator.v1beta2/app/server.go
- pkg/common/util/v1beta2/unstructured/informer.go
CRD client requires cluster scope access. Hence it is removed. Instead, error is checked for List API access.
Fixes: #929 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/961)
> Remove usage of crd client for checking CRD existence

- build/images/tf_operator/Dockerfile
Update to newer and cleaner UBI image which is also unencumbered for community use
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/962)
> Update tf-operator base image

- pkg/apis/tensorflow/v1beta2/types.go
- pkg/controller.v1beta2/tensorflow/controller.go
- pkg/util/k8sutil/k8sutil.go
Minor doc and style changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/966)
> Minor changes

- pkg/controller.v1beta1/tensorflow/controller.go
- pkg/controller.v1beta2/tensorflow/controller.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/969)
> Skip status update if no changes

- pkg/apis/tensorflow/validation/validation.go
When I create a tfjob as below, tfjob status changes to `Failed` with message 'Failed to marshal the object to TFJob; the spec is invalid: failed to marshal the object to TFJob'. The message is too general for me to fix my manifest.
So enhance tfjob validation error message by this PR
```
apiVersion: "kubeflow.org/v1beta2"
kind: "TFJob"
metadata:
name: "dist-mnist-for-e2e-lhg"
spec:
tfReplicaSpecs:
PS:
replicas: 2
restartPolicy: Never
template:
spec:
containers:
- name: ps
image: liuhougangxa/tf-dist-mnist-test:1.0
resources:
requests:
memory: "64Mi"
cpu: "1"
Worker:
replicas: 3
restartPolicy: Never
template:
spec:
containers:
- name: worker
image: liuhougangxa/tf-dist-mnist-test:1.0
args: ["--train_steps=200000"]
resources:
requests:
memory: "64Mi"
cpu: "1
```
---
This change is [<img …
> enhance tfjob validation error message

- pkg/controller.v1beta2/tensorflow/controller.go
This should be pod group instead of pdb.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/978)
> Fix incorrect event message for PodGroup deletion

- pkg/controller.v1beta2/tensorflow/pod.go
`golangci-lint` throws error `ineffectual assignment to masterRole`. Removed unnecessary assignments here. Default for `bool` is `false` in Go anyways.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/974)
> Fix ineffassign error in masterRole assignment

- build/images/tf_operator/Dockerfile
Update Dockerfile to support power building. Thanks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/981)
> modify dockerfile for ppc64le

- pkg/controller.v1beta2/tensorflow/controller.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/979)
> Update func name to pastBackoffLimit in comment

- examples/distribution_strategy/distributed_tfjob.yaml
Came across these during yaml lint check.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/983)
> Remove trailing spaces in distributed_tfjob.yaml

- pkg/control/pod_control.go
- pkg/control/service_control.go
fix https://github.com/kubeflow/tf-operator/issues/997
/assign @gaocegege @richardsliu
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/998)
> fix repeat delete service and pod

- examples/crd/crd-v1.yaml
Minor fix due to https://github.com/kubernetes/apiextensions-apiserver/blob/master/pkg/apis/apiextensions/types.go#L40
@richardsliu @gaocegege PTAL.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1007)
> Remove deprecated field

- pkg/common/jobcontroller/pod.go
@richardsliu @gaocegege After testing v1 in our cluster, at some time when there are lots of tfjobs in cluster, and many pods/services  with running/error/complete state, will panic after restart tf-operator.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1006)
> Fix panic as pod is nil

- pkg/controller.v1/tensorflow/status.go
- pkg/controller.v1beta2/tensorflow/status.go
fix #1000
/assign @gaocegege @jlewi @richardsliu 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1001)
> fix set startTime logic

- pkg/common/jobcontroller/jobcontroller.go
- pkg/controller.v1/tensorflow/controller.go
- pkg/controller.v1beta2/tensorflow/controller.go
fix https://github.com/kubeflow/tf-operator/issues/1011
/assign @gaocegege @richardsliu
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1012)
> fix sync PodGroup logic

- cmd/tf-operator.v1/app/options/options.go
- cmd/tf-operator.v1/app/server.go
For now, the default value for `resyncPeriod` is 30s and it is too short and we do not rely on  the resync of reflector to sync our tfjob, So make the resyncPeriod  configurable and update the default value to 12 hour
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1013)
> make resyncPeriod configurable

- pkg/controller.v1/tensorflow/status.go
- pkg/controller.v1beta2/tensorflow/status.go
I think your suggestion is right, we should not update LastUpdateTime if the status does not changed. It is the convention in Kubernetes community. This PR is to remove dup code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1022)
> fix: Remove dup code

- pkg/controller.v1/tensorflow/pod.go
To allow the gang-scheduling with using kube-batch, we need to create podGroup and set the annotation `scheduling.k8s.io/group-name: $PODGROUP_NAME` to each pod.
When EnableGangScheduling is set to true tf-operator create the podGroup automatically but doesn't set the annotation.
This PR fixes the problem by setting the annotation when create the pods.
fix #1031
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1032)
> set annotation automatically when EnableGangScheduling is set to true

- test/test-app/vendor/kubeflow/core@f7a68336ad7a65c2cbba8462e89d24a10626687e/tf-job-operator.libsonnet
Configmaps are not used in operator anymore. Unnecessary rules are also removed
/hold
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1036)
> Removing unnecessary Rbac authorization

- e2e_testing.md
/hold
After the release, we can fix the link. 
Or do you think if we could accept this PR before the release?
@richardsliu 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1038)
> fix(docs): Fix link for simple_TFJob_test

- pkg/controller.v1/tensorflow/pod.go
- pkg/controller.v1beta2/tensorflow/pod.go
I want to delete `Running` PS pods automatically but leave `Completed` Worker pods as there are some logs for debugging, so i set `CleanPodPolicy`=`Running` but it will delete all pods after TFJob is  completed.
I check out the code and find the root cause: we set worker 0 completed if it's exit code is zero but kubelet maybe not set the phase to `Succeeded` immediately so it still in `Running` phase when call function `deletePodsAndServices`.
@richardsliu @gaocegege PTAL.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1042)
> Set worker 0 completed if pod's phase goto succeeded

- dashboard/frontend/src/components/AppBar.js
When I try to delete job through the dashboard, I notice that the message is always:
> Are you sure you want to delete TFJob "test" in namespace "test"?
So I replace "test" with real namespace and name of the job.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1044)
> fix(UI): show correct namespace and name when deleting job through dashboard

- developer_guide.md
It will be useful to a new go developer and also easy to detect the `GOPATH` in different go env.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1047)
> Easily detect the GOPATH in current development environment.

- py/kubeflow/tf_operator/release.py
After fix a small bug in release scripts, the git commit id can be set into GitSHA variable.
The GitSHA is not 'Not provided' anymore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1046)
> fix bug: When executing `tf-operator.v1 -version`, GitSHA is always 'not provided'

- cmd/tf-operator.v1/app/options/options.go
- cmd/tf-operator.v1beta2/app/options/options.go
Signed-off-by: yeya24 <yb532204897@gmail.com>
Enable defining kubeconfig path in flag.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1049)
> add flag kubeconfig

- docs/monitoring/README.md
- pkg/controller.v1/tensorflow/controller.go
- pkg/controller.v1/tensorflow/job.go
- pkg/controller.v1/tensorflow/status.go
- pkg/controller.v1beta2/tensorflow/job.go
Signed-off-by: yeya24 <yb532204897@gmail.com>
I am wondering if this pr will cause compatibility problem. But I think we should follow the [metrics naming](https://prometheus.io/docs/practices/naming/) . All counter metrics need add suffix `total`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1055)
> add total suffix in counter metrics

- pkg/controller.v1/tensorflow/controller.go
- pkg/controller.v1/tensorflow/status.go
- pkg/controller.v1beta2/tensorflow/controller.go
- pkg/controller.v1beta2/tensorflow/status.go
Updating status is unnecessary when the tfjob is done and no status is updated indeed. But it will introduce overhead by writing etcd. The commit is to avoid such operation.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1051)
> Avoid unnecessary update when tfjob is complete

- cmd/tf-operator.v1/app/options/options.go
- cmd/tf-operator.v1/app/server.go
- cmd/tf-operator.v1beta2/app/options/options.go
- cmd/tf-operator.v1beta2/app/server.go
When many jobs created as the same time, pods are created slowly, increase qps and burst of kube client will bring effective improvements.
@gaocegege @richardsliu @johnugeorge PTAL.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1063)
> Add qps and burst options

- dashboard/backend/handler/api_handler.go
- pkg/common/jobcontroller/jobcontroller.go
- pkg/common/util/v1/testutil/util.go
- pkg/common/util/v1beta2/testutil/util.go
- pkg/controller.v1/tensorflow/controller.go
- pkg/controller.v1/tensorflow/controller_test.go
- pkg/controller.v1/tensorflow/pod.go
- pkg/controller.v1/tensorflow/util_test.go
- pkg/controller.v1beta2/tensorflow/controller.go
- pkg/controller.v1beta2/tensorflow/controller_test.go
- pkg/controller.v1beta2/tensorflow/pod.go
- pkg/controller.v1beta2/tensorflow/util_test.go
- py/kubeflow/tf_operator/tf_job_client.py
Labels are renamed to remove operator specific prefixes. 
`tf-job-name` is renamed to `job-name`
`tf-job-role` is renamed to `job-role`
For backwards compatibility, earlier labels are retained which will be removed after next release.
This matches the naming conventions used in Kubeflow/common. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1064)
> Renaming labels to common types

- pkg/common/util/v1/testutil/tfjob.go
- pkg/common/util/v1beta2/testutil/tfjob.go
When creating a tfjob object for testing, the default values should also be filled in using the same defaulter function in the scheme.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1071)
> Set tfjob defaults in test utils

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1070)
> Add verify-codegen in travis CI

- cmd/tf-operator.v1/app/options/options.go
- cmd/tf-operator.v1beta2/app/options/options.go
- pkg/common/jobcontroller/jobcontroller.go
- pkg/controller.v1/tensorflow/controller.go
- pkg/controller.v1/tensorflow/controller_test.go
- pkg/controller.v1/tensorflow/pod.go
- pkg/controller.v1beta2/tensorflow/controller.go
- pkg/controller.v1beta2/tensorflow/controller_test.go
- pkg/controller.v1beta2/tensorflow/pod.go
/cc @k82cn 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1050)
> feat(pod): Support custom gang scheduler via CLI argument

- pkg/controller.v1/tensorflow/pod.go
- pkg/controller.v1/tensorflow/pod_test.go
Close #1078 
/assign @johnugeorge @richardsliu 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1080)
> feat: Do not set TF_CONFIG for local training

- examples/v1/dist-mnist/Dockerfile.ppc64le
- examples/v1/dist-mnist/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1084)
> add ppc64le support for the example dist-mnist

- py/kubeflow/tf_operator/util.py
fix the problem for support power ppc64le
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1082)
> Support for ppc64le

- README.md
- docs/adopters.md
Ref https://github.com/kubeflow/tf-operator/issues/1076
This is the PR to add adopters section in README.
/assign @johnugeorge @richardsliu 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1092)
> feat: Add adopters in README

- py/kubeflow/tf_operator/util.py
Signed-off-by: Henry Wang <<henry.wang@arm.com>>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1098)
> Add support for aarch64

- cmd/tf-operator.v1/app/options/options.go
- cmd/tf-operator.v1/main.go
Reuse the Prometheus metrics port to expose golang pprof info.
/assign @johnugeorge @hougangliu 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1102)
> feat: Support pprof when monitoring is specified

- pkg/controller.v1/tensorflow/controller.go
If the tfjob has already terminated, we don't need to check activedeadline and backofflimit.
Originally, even the job has terminated it still checks the Activedeadline and appends the event to it.
So the event that shows the job failed after it succeeded might happen as follow, 
the log of tf-operator will also keep showing the failure massage of past Activedeadline
```
Events:
Type    Reason                   Age                  From         Message
----    ------                   ----                 ----         -------
Normal  SuccessfulCreatePod      27m                  tf-operator  Created pod: dist-mnist-for-e2e-test-worker-0
Normal  SuccessfulCreateService  27m                  tf-operator  Created service: dist-mnist-for-e2e-test-worker-0
Normal  ExitedWithCode           27m …
```
> fix the reconcile flow 

- prow_config.yaml
- sdk/python/README.md
- sdk/python/docs/TFJobClient.md
- sdk/python/examples/kubeflow-tfjob-sdk.ipynb
- sdk/python/kubeflow/tfjob/api/tf_job_client.py
- sdk/python/kubeflow/tfjob/constants/constants.py
- sdk/python/setup.py
- sdk/python/test/test_e2e.py
From feedback of the `kubeflow-tfjob` SDK, add more APIs (some of them are ehanced from `py/kubeflow/tf_operator/tf_job_client.py`):
- `wait_for_job`: Wait for the specified job to finish 
- `wait_for_condition`: Waits until any of the specified conditions occur
- `get_job_status`: Quick way to get the TFJob status
- `if_job_running`: Quick way to check if the TFJob running
- `if_job_succeeded`:  Quick way to check if the TFJob Succeeded
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1116)
> Add more APIs for TFJob done

- sdk/python/README.md
- sdk/python/docs/TFJobClient.md
- sdk/python/examples/kubeflow-tfjob-sdk.ipynb
- sdk/python/kubeflow/tfjob/api/tf_job_client.py
- sdk/python/test/test_e2e.py
As @johnugeorge commented in https://github.com/kubeflow/pytorch-operator/pull/240, the PR is update the API name as well for tfjob python client. Thanks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1117)
> Update checking status API name

- build/images/tf_operator/Dockerfile
- test/test-app/vendor/kubeflow/core@f7a68336ad7a65c2cbba8462e89d24a10626687e/tf-job-operator.libsonnet
Relates to: kubeflow/kubeflow#4590
tf_smoke.py removed
Golang updated to 1.13.5
/hold
/cc @swiftdiaries @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1124)
> Distroless image for TF operator

- Gopkg.lock
- pkg/apis/tensorflow/v1/openapi_generated.go
- pkg/apis/tensorflow/v1/types.go
This PR fix some comments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1137)
> fix comment, add +optional flag to comment. 

- pkg/controller.v1/tensorflow/controller.go
If calculating satisfied with '||',  it only guarantee some replicaTypes not all replicaTypes are satisfied. There will be some problems. So it should be changed to '&&'.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1120)
> fix(controller): calculate satisfied with && instead of ||

- sdk/python/requirements.txt
- sdk/python/setup.py
The PR is going to debug and fix the SDK CI tests problem below.
```
obj_dict = {obj.attribute_map[attr]: getattr(obj, attr)
>                       for attr, _ in six.iteritems(obj.openapi_types)
if getattr(obj, attr) is not None}
E           AttributeError: 'V1TFJob' object has no attribute 'openapi_types'
/usr/local/lib/python3.5/dist-packages/kubernetes/client/api_client.py:230: AttributeError
```
This is caused by kubernetes Client bug: https://github.com/kubernetes-client/python/issues/1112
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1143)
> Fix sdk test issue that's caused by kubenertes Client bug.

- test/workflows/components/simple_tfjob_v1.jsonnet
Unblocks https://github.com/kubeflow/kfctl/pull/131, because kfctl uses tf-operator head for presubmit test.
After enabling istio sidecar injection in `kubeflow` namespace, tfjob-smoke-test is the only test timing out.
I haven't been able to look at pod log/info because there were permission issues, but I've found other people mentioning tfjob cannot work with istio sidecar: https://github.com/kubeflow/kubeflow/issues/3935
/cc @jlewi 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/tf-operator/1148)
> Disable istio sidecar injection in simple tfjob test

- pkg/controller.v1/tensorflow/controller.go
If job stays in `Created` and all its controlled pods waits in `Pending` state, util it exceed its ActiveDeadline(if `job.spec.ActiveDeadlineSeconds` has been set), this job will be reconciled as past active deadline and be cleaned up, however, `job.status.completionTime` remains a nil pointer, and it will absolutely panic in `JobController.cleanupJob` func.
> Set completion time when job exceed specified deadline.

- build/images/tf_operator/Dockerfile
As tf_operator uses distroless image as base image now, running container image after `docker build` on arm64 will lead to error:
`standard_init_linux.go:211: exec user process caused "no such file or directory"`.
Using static compilation will fix this error.
Signed-off-by: Henry Wang <Henry.Wang@arm.com>
> Make tf_operator use static compilation in container

- hack/python-sdk/gen-sdk.sh
fixes: #1166 
```
[root@jinchi1 ~]# wget http://central.maven.org/maven2/io/swagger/swagger-codegen-cli/2.4.6/swagger-codegen-cli-2.4.6.jar
--2020-06-14 19:39:27--  http://central.maven.org/maven2/io/swagger/swagger-codegen-cli/2.4.6/swagger-codegen-cli-2.4.6.jar
Resolving central.maven.org (central.maven.org)... failed: Name or service not known.
wget: unable to resolve host address 'central.maven.org'
[root@jinchi1 ~]# wget http://search.maven.org/maven2/io/swagger/swagger-codegen-cli/2.4.6/swagger-codegen-cli-2.4.6.jar
--2020-06-14 20:03:53--  http://search.maven.org/maven2/io/swagger/swagger-codegen-cli/2.4.6/swagger-codegen-cli-2.4.6.jar
Resolving search.maven.org (search.maven.org)... 18.234.11.249, 3.227.158.232
Connecting to search.maven.org (search.maven.org)|18.234.11.249|:80... …
```
> Update swagger-codegen-cli URL

- examples/v1/distribution_strategy/keras-API/multi_worker_strategy-with-keras.py
- prow_config.yaml
- py/kubeflow/tf_operator/deploy.py
The PR is going to fix below two problems:
1. `No Major.Minor.Patch elements found` in set up kubeflow steps of CI tests.
```
INFO:root:Using ksonnet cmd: ks-13
INFO:root:Running: ks-13 env add e2e-0806-0218-abe0
cwd=/mnt/test-data-volume/kubeflow-tf-operator-presubmit-v1-1171-232e11d-7216-b6d9/src/kubeflow/tf-operator/test/test-app
INFO:root:Subprocess output:
INFO:root:level=info msg="Using context \"gke_kubeflow-ci_us-east1-d_ztor-presubmit-v1-1171-232e11d-7216-b6d9\" from kubeconfig file \"/m
nt/test-data-volume/kubeflow-tf-operator-presubmit-v1-1171-232e11d-7216-b6d9/.kube/kubeconfig\""
INFO:root:level=info msg="Creating environment \"e2e-0806-0218-abe0\" with namespace \"default\", pointing to \"version:v1.15.12\" cluste
r at address \"https://35.185.20.182\""
INFO:root:level=error …
```
> Fix setup cluster issue and Pylint issue in CI tests

- pkg/controller.v1/tensorflow/tensorflow.go
Fix the typo in `pkg/controller.v1/tensorflow/tensorflow.go`
> Fix the typo

- examples/v1/distribution_strategy/keras-API/multi_worker_strategy-with-keras.py
Bugfix: `TypeError: on_epoch_end() takes 2 positional arguments but 3 were given` will be occured when run this demo in TF2.x
You can see the details at  
https://github.com/tensorflow/tensorflow/blob/9697081dac25ef5c3e95b98b6e1113261611a4b9/tensorflow/python/keras/callbacks.py#L414
> bugfix for multi_worker_strategy-with-keras.py

- .github/workflows/publish.yaml
> feat: Add CD using GitHub Actions

- pkg/controller.v1/tensorflow/status.go
- py/kubeflow/tf_operator/tf_job_client.py
- vendor/github.com/kubeflow/common/pkg/util/logger.go
> fix: Fix the log message

- cmd/tf-operator.v1/app/server.go
when k8s cluster is not connected (may be any network issue), log message like this
{"filename":"app/server.go:219","level":"error","msg":"Get "https://10.107.104.120:6443/apis/kubeflow.org/v1/tfjobs\": dial tcp 10.107.104.120:6443: i/o timeout","time":"2020-12-30T16:35:14+08:00"}
checkCRDExists will return true , that is not the right way
> checkCRDExists func return true when k8s cluster is not connected

- pkg/controller.v1/tensorflow/controller.go
- pkg/controller.v1/tensorflow/job.go
Now we do not have such an expectation key for tfjob, thus we can remove the comment.
/assign @ChanYiLin 
> chore: Remove useless expectation

- pkg/controller.v1/tensorflow/status.go
Follow up to issue: https://github.com/kubeflow/tf-operator/issues/1223, where failed job completion timestamp was not properly configured before.
> Fix completion time setting bug

- pkg/controller.v1/tensorflow/status.go
> feat: Change the message for running condition

- manifests/crd.yaml
- manifests/deployment.yaml
- manifests/kustomization.yaml
- manifests/namespace.yaml
- manifests/podgroup.yaml
- manifests/rbac.yaml
- manifests/service.yaml
- pkg/controller.v1/tensorflow/job.go
- py/kubeflow/tf_operator/cleanpod_policy_tests.py
- py/kubeflow/tf_operator/deploy.py
- py/kubeflow/tf_operator/distributed_training_tests.py
- py/kubeflow/tf_operator/estimator_runconfig_tests.py
- py/kubeflow/tf_operator/invalid_tfjob_tests.py
- py/kubeflow/tf_operator/pod_names_validation_tests.py
- py/kubeflow/tf_operator/replica_restart_policy_tests.py
- py/kubeflow/tf_operator/shutdown_policy_tests.py
- py/kubeflow/tf_operator/simple_tfjob_tests.py
- py/kubeflow/tf_operator/test_runner.py
- py/kubeflow/tf_operator/tf_job_client.py
- py/kubeflow/tf_operator/util.py
- scripts/copy-to-gopath.sh
- scripts/setup-tf-operator.sh
- sdk/python/test/test_e2e.py
- test/workflows/components/workflows.libsonnet
This PR moves TF Operator e2e tests to AWS
- remove GCP related credentials, volume and command
- add AWS credentials and registry
- use Kaniko to build image
- change the way of setup-cluster and tear-down-cluster
> Move TF Operator e2e tests to AWS Prow

- README.md
- developer_guide.md
> feat: Update developers guide and readme

- README.md
- docs/api/autogen/config.yaml
- docs/api/autogen/templates/gv_details.tpl
- docs/api/autogen/templates/gv_list.tpl
- docs/api/autogen/templates/type.tpl
- docs/api/autogen/templates/type_members.tpl
- docs/api/generated.asciidoc
- hack/generate-apidoc.sh
API Doc Preview: https://github.com/gaocegege/tf-operator/blob/e0f52ba0e25f9831daa5364de7b27432323ebd75/docs/api/generated.asciidoc
> feat: Add API Documentation WIP

- manifests/tf-job-crds/base/crd.yaml
- manifests/tf-job-crds/base/kustomization.yaml
- manifests/tf-job-crds/overlays/application/application.yaml
- manifests/tf-job-crds/overlays/application/kustomization.yaml
- manifests/tf-job-operator/base/cluster-role-binding.yaml
- manifests/tf-job-operator/base/cluster-role.yaml
- manifests/tf-job-operator/base/deployment.yaml
- manifests/tf-job-operator/base/kustomization.yaml
- manifests/tf-job-operator/base/params.env
- manifests/tf-job-operator/base/service-account.yaml
- manifests/tf-job-operator/base/service.yaml
- manifests/tf-job-operator/overlays/application/application.yaml
- manifests/tf-job-operator/overlays/application/kustomization.yaml
Resolves: https://github.com/kubeflow/tf-operator/issues/1246
Umbrella issue: https://github.com/kubeflow/manifests/issues/1740
As part of the work of wg-manifests for 1.3
(https://github.com/kubeflow/manifests/issues/1735), we are moving manifests
development in upstream repos. This gives the application developers full
ownership of their manifests, tracked in a single place.
This PR copies the manifests for application `TFJob Operator`
from path `apps/tf-training/upstream` of kubeflow/manifests to path
`deploy/v1` of the upstream repo (https://github.com/kubeflow/tf-operator).
cc @kubeflow/wg-training-leads
> TFJob Operator: Move manifests development upstream

- manifests/base/deployment.yaml
- manifests/base/kustomization.yaml
- manifests/overlays/standalone/kustomization.yaml
- prow_config.yaml
- scripts/setup-tf-operator.sh
- test/workflows/components/workflows.libsonnet
Resolves https://github.com/kubeflow/tf-operator/issues/1205
~~It's still WIP, not familiar with jsonnet syntax, and it's has been deprecated years...~~
There's requirement to migrate from jsonnet-generated workflow to python-generated workflow, otherwise, it's difficult to maintain. 
/hold
Hold until test succeed
> Migrate to public ECR

- manifests/overlays/kubeflow/kustomization.yaml
- manifests/overlays/standalone/kustomization.yaml
- prow_config.yaml
This is the final fix for tf-operator manifests, the tf-operator has already onboarded public ECR.
E2E test passes with CI pushing to private ECR, CD pushing to public ECR.
Tf-operator is ready for manifest sync 
/cc @yanniszark 
Let me know if any other issue
> Fix kubeflow overlay

- sdk/python/kubeflow/tfjob/api/tf_job_client.py
IMO, the `follow` parameter of `TFJobClient.get_logs` method should continually fetch and print the log stream of every listening pods. But the actual behavior is we can only get the log after pod's execution is finished.
As the discussion of this https://github.com/kubernetes-client/python/issues/199 the correct way to get the stream is to call `read_namespaced_pod_log` with `watch.Watch`.
This PR is an approach to fix this issue.
The output of `watch.stream` is a generator, so we could iterate over every pods's stream, group log lines and print them.
> Fix: the "follow" of TFJobClient.get_logs

- manifests/base/cluster-role.yaml
Signed-off-by: huone1 <huwanxing@huawei.com>
> add podgroups rule in cluster-role.yaml

- pkg/apis/tensorflow/v1/openapi_generated.go
- pkg/apis/tensorflow/v1/types.go
/assign @ChanYiLin @terrytangyuan 
> fix: Remove the dup comment tag

- README.md
This doesn't require cloning the repo, making one-line installation possible.
> Use remote Kustomize build option in standalone installation instructions

- sdk/python/kubeflow/tfjob/api/tf_job_client.py
fix https://github.com/kubeflow/tf-operator/issues/1275
This issue is mainly caused by the API upgrade in https://github.com/kubernetes-client/python/pull/1141
Related code is here https://github.com/kubernetes-client/python/blob/c206745dcd491d64b63260c6b6f46e3a3a81b101/kubernetes/client/api/custom_objects_api.py#L559
This commit drops the args `name` and `body`, then recover the `name` args in the following commits.
Now this API's `body` argument is handled by kwargs.
If user install kubernetes python client's version >= v11.0.0 will run into this error.
The temporary solution is to downgrade kubernetes client to v10.1.0
And a possible fixing is to use keyword arguments instead of positional arguments.
> fix calling custom_api.delete_namespaced_custom_object args error

- pkg/controller.v1/tensorflow/controller.go
- pkg/controller.v1/tensorflow/job.go
- pkg/controller.v1/tensorflow/pod.go
- pkg/controller.v1/tensorflow/status.go
This PR adds the job's namespace as a label to Prometheus metrics reported by the operator, making it possible to filter metrics per-namespaces as opposed to global counters.
> Add job namespace to `tf_operator_jobs_*` counters

- sdk/python/kubeflow/tfjob/api/tf_job_client.py
There are 2 issues in current code.
1. `pod_names` is not subscriptable
The return value of method self.get_pod_names is a "set" type, so that the following code pod_names[index] for getting the pod's name with index number will raise an exception `TypeError: 'set' object is not subscriptable`, so we should convert `pod_names` to list.
2. iterate over multiple generators(the return value of watch.stream()) may be blocked on one generator
We iterate over these streams, but when one pod not to produce new log, the iteration process will block on this stream and cannot continue to read other pods' stream. To fix this, we should create queues for every stream and start one thread for every stream for decoupling the logs' producing and consuming, so that we can implement non-blocking …
> fix get_logs pod_names type and iteration blocking

- pkg/controller.v1/tensorflow/controller.go
- py/kubeflow/tf_operator/test_runner.py
- py/kubeflow/tf_operator/util.py
TFJob object is nil once reconcile is called when object is deleted. Added extra check to handle it
Fixes: #1284
> Fix invalid pointer when tfjob is deleted

- cmd/tf-operator.v1/app/server.go
- pkg/common/util/v1/unstructured/informer.go
- pkg/controller.v1/tensorflow/controller.go
- pkg/controller.v1/tensorflow/job.go
- pkg/controller.v1/tensorflow/status.go
Address https://github.com/kubeflow/tf-operator/issues/1289
This is a follow up PR of #1290
/cc @terrytangyuan @zw0610 
Signed-off-by: Jiaxin Shan <seedjeffwan@gmail.com>
> Fix all client request that needs contexts

- manifests/overlays/kubeflow/kustomization.yaml
- manifests/overlays/standalone/kustomization.yaml
Resolve part of #1321 
/cc @terrytangyuan @PatrickXYS 
This image comes from latest master commit and it is built from CI 
```
commit 47a74b738920edbf4207160cec7e1dff9cdab3f2 (upstream/master, master)
Author: jazzsir <jazzsir@gmail.com>
Date:   Tue Jul 20 16:10:15 2021 +0900
add a specific version of tensorflow_datasets (#1305)
re-push with signed email
```
> Update container image for v1.1.1

- scripts/setup-tf-operator.sh
Fix https://github.com/kubeflow/tf-operator/issues/1329
Previously we use $PULL_BASE_SHA for image tag, and now we use $PULL_PULL_SHA
> Use PULL_PULL_SHA for image

- prow_config.yaml
- scripts/setup-tf-operator.sh
- scripts/setup-training-operator.sh
- test/workflows/components/workflows.libsonnet
Address #1343 
We change to use PULL_PULL_SHA in earlier PR but post-submit doesn't have PULL_PULL_SHA which will fail the pipeline. 
presubmit and postsubmit share the same pipeline. This PR changes to use PULL_PULL_SHA as preferred option and it will fall back to PULL_BASE_SHA in post-submit jobs. 
/cc @PatrickXYS @terrytangyuan
> Fix postsubmit job using PULL_BASE_SHA

- README.md
Since Kubernetes v1.14, kustomize became a subcommand in kubectl so we can just use `kubectl` instead.
> docs: Update to use kubectl kustomize in instructions

- pkg/apis/xgboost/validation/validation.go
I fixed name in XGBoostJob validation.
Btw, is it fine that we don't run this validation before Job submission ?
As I can see, user can detect that Job is not valid only from the controller logs, even if YAML is incorrect: https://github.com/kubeflow/tf-operator/blob/master/pkg/controller.v1/xgboost/xgboostjob_controller.go#L146-L148.
Do we have any method to detect that YAML is valid other than validation webhook ?
cc @kubeflow/wg-training-leads
> Fix XGBoost container name in log message

- pkg/controller.v1/pytorch/pytorch.go
- pkg/controller.v1/pytorch/pytorchjob_controller.go
Address #1358 
PR concludes two changes
1. Apply `strings.ToLower()` on ReplicaType before string comparison. This is definitely a bug when we migrate PyTorch to kubelfow/common fashion. 
https://github.com/kubeflow/tf-operator/blob/52cddeceba1e31e54a2e34551f486675fafabda2/pkg/controller.v1/pytorch/pytorch.go#L32-L33
2. Update incorrect logs names. I think @zw0610 may forget to clean them up in last PR https://github.com/kubeflow/tf-operator/pull/1294
/cc @andreyvelich  @zw0610  @kubeflow/wg-training-leads
> fix incorrect torch env population

- manifests/overlays/kubeflow/kustomization.yaml
- manifests/overlays/standalone/kustomization.yaml
Post submit job has been fixed. 
fb013e4faf6e8c2741829bf6941b99697f219a30 is the last commit.  
This image includes two bug fixes and we can release a new alpha version later
> chore: Update manifest image tag

- prow_config.yaml
Related: https://github.com/kubeflow/tf-operator/issues/1323.
In order to trigger the CI AWS Pipeline we should update `include_dirs` with the latest folder structure.
cc @kubeflow/wg-training-leads @deepak-muley
> Update include dirs in prow config

- examples/pytorch/simple.yaml
- examples/tensorflow/simple.yaml
Add for operator verification. These jobs are simple and ready to run. No volumes, no GPUs and they are just used for manual testing.
> Add simple verification jobs

- examples/tensorflow/distribution_strategy/estimator-API/distributed_tfjob.yaml
- examples/tensorflow/distribution_strategy/keras-API/multi_worker_tfjob.yaml
- examples/tensorflow/mnist_with_summaries/tf_job_mnist.yaml
Since we move "cleanPodPolicy" to `runPolicy` umbrella and enable CRD validation. some examples can not be submitted. 
This PR helps update the examples still using the old pattern.
```
kubectl apply -f tf_job_mnist.yaml
error: error validating "tf_job_mnist.yaml": error validating data: ValidationError(TFJob.spec): unknown field "cleanPodPolicy" in org.kubeflow.v1.TFJob.spec; if you choose to ignore these errors, turn validation off with --validate=false
```
> fix: runPolicy validation error in the examples

- manifests/base/deployment.yaml
- manifests/base/service.yaml
ref: https://github.com/kubeflow/manifests/issues/2010 
training-operator exposes 8080 per logs
2021-09-14T19:31:49.294Z	INFO	controller-runtime.metrics	metrics server is starting to listen	{"addr": ":8080"}
hence when we do local testing, it works fine
but when we expose it using make deploy then inside k8s, its not exposed
Steps:
- make deploy
- kubectl port-forward -n kubeflow svc/training-operator 8080:8080
> 2010: fix to expose correct monitoring port 

- manifests/base/service.yaml
ref: #1399
Testing Details:
<pre>
k -n kubeflow get pod -o wide
...
training-operator-749dfc7446-ktmjk                           1/1     Running   0          65s   172.20.16.63    karbon-dm-demo-3-9b4ea8-k8s-worker-1   <none>           <none>
...
</pre>
<pre>
k -n kubeflow describe service training-operator
...
Name:              training-operator
Namespace:         kubeflow
Labels:            app=training-operator
Annotations:       prometheus.io/path: /metrics
prometheus.io/port: 8443
prometheus.io/scrape: true
Selector:          control-plane=kubeflow-training-operator
Type:              ClusterIP
IP Families:       <none>
IP:                172.19.137.178
IPs:               <none>
Port:              monitoring-port  8443/TCP
TargetPort:        8443/TCP
Endpoints: …
> Fix 1399: added pod matching label in service selector

- docs/adopters.md
These are from all the operator repos (mostly just merging the ones from MPI Operator and TF Operator).
@kubeflow/wg-training-leads 
Signed-off-by: Yuan Tang <terrytangyuan@gmail.com>
> docs: Migrate adopters of all operators to this repo

- README.md
> Add acknowledgement section in README to credit all contributors

- README.md
hyperlinks now point to the latest api reference files.
issue - https://github.com/kubeflow/tf-operator/issues/1411
> fix hyperlinks in the 'overview' section

- manifests/overlays/kubeflow/kustomization.yaml
- manifests/overlays/standalone/kustomization.yaml
Due to workflow failure https://argo.kubeflow-testing.com/workflows/kubeflow-test-infra/kubeflow-tf-operator-postsubmit-v1-e0b872e-2128-8fc4
I use corresponding master commit https://github.com/kubeflow/tf-operator/commit/557ba80eb03a7cd72c482bc9f4061fd7c72cabde
> Note: there's no code different between these two branches. In the future. we should fix https://github.com/kubeflow/tf-operator/issues/1429 and then we can alway get a image to use even there's flaky tests.
> Update training-operator image tag

- manifests/overlays/kubeflow/kustomization.yaml
- manifests/overlays/standalone/kustomization.yaml
Update image tag from v1.3-branch commit 
https://github.com/kubeflow/tf-operator/commit/760ac1171dd30039a7363ffa03c77454bd714da5
> chore: Update training-operator image tag

- pkg/common/util/util.go
- pkg/controller.v1/tensorflow/tfjob_controller.go
Signed-off-by: bert.li <qiankun.li@qq.com>
fix issue #1447
> Fix set scheduler error

- .gitattributes
Jsonnet is recognized as the main language of this repo but it's only for testing and shouldn't be included as part of the classification.
Reference: https://github.com/github/linguist/blob/master/docs/overrides.md#generated-code
Signed-off-by: terrytangyuan <terrytangyuan@gmail.com>
> chore: Add .gitattributes to ignore Jsonnet test code for linguist

- .github/PULL_REQUEST_TEMPLATE.md
As we discussed on the WG meeting, it is better to add the doc checklist to our PR template.
Once our contributors submit the new PR with feature request, they have to update the [Kubeflow docs](https://www.kubeflow.org/docs/components/training/).
> Add PR template with doc checklist

- pkg/controller.v1/tensorflow/tfjob_controller.go
Because the tf-controller overrides the `ReconcilePods` function, the updated labels with `training.kubeflow.org` prefix are not added to the metainfo of tf pod generated. However, for the selector in tf service, because tf-controller does not overrides the `ReconcilePods`, labels with `training.kubeflow.org` prefix are included.
**Checklist:**
> update label for tf-controller

- build/images/training-operator/Dockerfile
Currently, Go version is unmatched between gomod and base image of Dockerfile for training operator. So, this PR upgrade Go version of base image.
Fixes #
**Checklist:**
> Set Go version of base image to 1.17

- README.md
- docs/api/mpi_generated.asciidoc
- hack/generate-apidoc.sh
While the mpijob api and controller are merged, the document is still missing.
> add mpi doc

- pkg/common/util/v1/testutil/tfjob.go
Fix misspell in tfjob.
Fixes #
> chore: Fix missspell in tfjob

- manifests/base/cluster-role.yaml
- pkg/apis/mpi/v1/constants.go
- pkg/apis/mpi/validation/validation.go
- pkg/apis/mpi/validation/validation_test.go
- pkg/controller.v1/mpi/mpijob_controller.go
fix comments for mpi-controller
> fix comments for mpi-controller

- cmd/training-operator.v1/main.go
- go.mod
- pkg/config/config.go
- pkg/controller.v1/pytorch/elastic.go
- pkg/controller.v1/pytorch/envvar.go
- pkg/controller.v1/pytorch/initcontainer.go
- pkg/controller.v1/pytorch/initcontainer_test.go
- pkg/controller.v1/pytorch/master.go
- pkg/controller.v1/pytorch/pytorchjob_controller.go
- pkg/controller.v1/pytorch/pytorchjob_controller_suite_test.go
This PR is to add the init container, which checks if the master is already running.
Fixes #1482
> feat(pytorch): Add init container config to avoid DNS lookup failure

- pkg/common/util/reconciler.go
- pkg/common/util/reconciler_generic.go
- pkg/controller.v1/mpi/mpijob_controller.go
fix issues related to controller logic from comment https://github.com/kubeflow/training-operator/pull/1457#pullrequestreview-812920623
> add expectation-related functions for other resources used in mpi-controller

- cmd/training-operator.v1/main.go
- go.mod
the same problem as: https://github.com/kubernetes-sigs/kubebuilder/issues/1593
> add StacktraceLevel for zapr

- OWNERS
I am removing myself from training-operator approvers and also wg-training-leads.
Thanks for @kubeflow/wg-training-leads  help during the time, especially thanks to @gaocegege !
> remove ChanYiLin from approvers

- pkg/common/util/v1/testutil/pod.go
- pkg/common/util/v1/testutil/service.go
- pkg/common/util/v1/testutil/tfjob.go
- pkg/common/util/v1/testutil/util.go
- pkg/controller.v1/tensorflow/job_test.go
- pkg/controller.v1/tensorflow/pod_test.go
- pkg/controller.v1/tensorflow/status_test.go
- pkg/controller.v1/tensorflow/suite_test.go
- pkg/controller.v1/tensorflow/tfjob_controller_test.go
- pkg/controller.v1/tensorflow/util_test.go
This pr convert the unit test for previous tf-operator (tag: v1.1.0) to tf-controller in training-operator.
Fixes #1497 
**Checklist:**
> controller_test.go
> job_test.go
~~- [ ] TestCleanupTFJob~~ (removed in v1.1.0)
> pod_test.go
> status_test.go
> tensorflow_test.go
> util_test.go
~~- [ ] TestConvertTFJobToUnstructured~~ (no longer appliable)
> add unit tests for tensorflow controller

- cmd/training-operator.v1/main.go
Restore the launch argument `--namespace` to allow user to specify namespace to monitor
Fixes #1522
**Checklist:**
> restore option namespace in launch arguments

- cmd/training-operator.v1/main.go
- pkg/config/config.go
- pkg/controller.v1/mpi/mpijob.go
- pkg/controller.v1/mpi/mpijob_controller.go
- pkg/controller.v1/mpi/suite_test.go
In mpi-operator, user can specify which kubectl-delivery image to use in launch argument. Such feature is missing in training-operator. This pr follows the pytorch init container image option style and adds `mpi-kubectl-delivery-image` to launch options.
Fixes #
**Checklist:**
> add option for mpi kubectl delivery

- sdk/python/kubeflow/__init__.py
Correctly extends path in SDK `__init__.py` so `training-operator` does not break other Kubeflow python SDK imports.
Fixes #1471
**Checklist:**
> extends path in __init__.py for SDK correctly

- pkg/controller.v1/mxnet/mxjob_controller.go
- pkg/controller.v1/pytorch/pytorchjob_controller.go
- pkg/controller.v1/xgboost/xgboostjob_controller.go
If two jobs are created with the same name and different namespaces, pods/services are not created for the later one since some controllers get pods for jobs only by name and not by namespace.
Please refer #1543 for the problem.
Fixes #1543 
**Checklist:**
> fix: add namespace filtering when getting pods/services for jobs

- pkg/controller.v1/mpi/mpijob_controller.go
- pkg/controller.v1/mxnet/mxjob_controller.go
- pkg/controller.v1/pytorch/pytorchjob_controller.go
- pkg/controller.v1/tensorflow/tfjob_controller.go
- pkg/controller.v1/xgboost/xgboostjob_controller.go
When [`--enable-gang-scheduling` is enabled](https://github.com/kubeflow/common/blob/master/pkg/controller.v1/common/job.go#L214), for jobs with PodGroup in pending phase, the operator will update the JobStatus with [only its `LastReconcileTime` being changed](https://github.com/kubeflow/common/blob/master/pkg/controller.v1/common/job.go#L267). That means the `jobStatus.replicaStatues` could be nil when being pushed to the APIServer, triggering an error message.
This PR add a fix procedure for all controllers to give an empty value for `jobStatus.replicaStatues` if nil.
> fix UpdateJobStatusInApiServer when gang-scheduling is enabled

- pkg/apis/mpi/v1/default.go
Current mpiController only give spec.CleanPodPolicy a default value none. However, all xjobs in training-operator use spec.RunPolicy.CleanPodPolicy when jobContoller does DeletePodsAndServices in kubeflow common package. If this field is not set by default so do users, it will trigger a nil pointer when jobController deference RunPolicy at DeletePodAndServices(). https://github.com/kubeflow/common/blob/master/pkg/controller.v1/common/job.go#L28. So we have to give MPIJob runPolicy field a default value.
Fixes #
**Checklist:**
> fix: set mpijob runPolicy.cleanPodPolicy to default none

- pkg/apis/mpi/v1/default.go
- pkg/controller.v1/mpi/mpijob_controller_test.go
This pr update mpijob unit tests: in the past, unit tests uses spec.cleanPodPolicy to test gc logic, but now in training-operator framework, spec.runPolicy.CleanPodPolicy is the standard, so it is more suit to use this field in unit tests as well.
Fixes #1555
**Checklist:**
> Update MPIJob unit tests to use spec.runPolicy.cleanPodPolicy

- pkg/controller.v1/mpi/mpijob_controller.go
Thanks for @zw0610 pointing out, the mpijob-operator logic where if gang-scheduler is set is totally opposite. Currently, if gang-scheduler name is not set, then throws an error and directly use default-scheduler instead. However, the correct logic should be if `util.IsGangSchedulerSet` is true, then throw error and use user's indicated scheduler; else the mpijob-operator should render a default `volcano` for schedulerName field. So this pr remove ! when check if gang scheduler is set or not
Fixes #1548 
**Checklist:**
> fix: MPIJob cannot use gang-scheduling when --enable-gang-scheduling is set

- examples/mpi/tensorflow-mnist.yaml
- pkg/apis/mpi/v1/default.go
- pkg/common/util/util.go
- pkg/controller.v1/mpi/mpijob.go
- pkg/controller.v1/mpi/mpijob_controller.go
Multiple issues are fixed in this pull request because simply fixing one of them fails the tests.
-----
**1. Duplicated CleanPodPolicy in MPIJob**
There exists two field for CleanPolicy in MPIJob:
- `Spec.CleanPodPolicy`
- `Spec.RunPolicy.CleanPodPolicy`
It is a legacy issue and exists before mpi-controller is migrated to training-operator: https://github.com/kubeflow/mpi-operator/blob/master/pkg/apis/kubeflow/v1/types.go#L49
To keep API compatibility, we did not change the API (by removing `Spec.CleanPodPolicy`) during the migration phase.
**Solution**
> 1. Update `Validate` function to rule out the case when both fields of `CleanPodPolicy` are specified but the values are not identical
> 2. Update `Default` function to fill both fields of …
> fix label and CleanPodPolicy for mpi-controller

- manifests/overlays/kubeflow/kubeflow-training-roles.yaml
mpijob resource is missing in kubeflow training role.
> fix: add mpijobs to kubeflow training role

- pkg/controller.v1/pytorch/pytorchjob_controller.go
- pkg/controller.v1/xgboost/xgboostjob_controller.go
As indicated in issue 1566, xgboostjob and pytorchjob forgot to update status.startTime. We should add them to jobStatus.
Fixes #1566
**Checklist:**
> update status.startTime for pytorchjob and xgboostjob

- manifests/base/deployment.yaml
This should be related to https://github.com/kubeflow/training-operator/issues/1559
In my cluster, the default `timeoutSeconds: 1` is not enough and change to `3` is fine.
My cluster is `1.21` with training-operator `1.4.0`
> Increase success threshold

- sdk/python/kubeflow/training/api/py_torch_job_watch.py
- sdk/python/kubeflow/training/api/tf_job_watch.py
- sdk/python/kubeflow/training/utils/utils.py
- sdk/python/requirements.txt
**What this PR does / why we need it**: This removes the dependency on `table-logger`. None of the various alternatives mentioned in that issues were drop-in replacements, so given the simplicity of the use case here the dependency is replaced with a small class utilizing `str.format`. Note that the class was written without referring to the `table-logger` source at all, which would be a license violation.
I confirmed that you can now run the sample notebook
https://github.com/kubeflow/training-operator/blob/6523d8d2b7a27f1140a05971843cc4da7523694f/sdk/python/examples/kubeflow-tfjob-sdk.ipynb
in modern IPython.
Fixes #1446 
**Checklist:**
> Remove `table-logger` dependency

- pkg/controller.v1/mpi/mpijob_controller.go
mpi-controller's `DeletePodsAndServices()` is a dead code which is never called, very confusing and very misleading. All of controllers use the base job-controller to reconcile and the base will call `jc.DeletePodsAndServices()` without using subclass's(such as mpijob, pytorchjob, .etc). It is better to remove it.
Fixes #
**Checklist:**
> Remove uncalled mpi-controller DeletePodsAndServices()

- .github/workflows/test-go.yaml
Currently, github action won't stop even though there is an error during make step. Adding a `&&` to make sure github action abort on first fail.
Fixes #
**Checklist:**
> chore: stop action on first fail

- sdk/python/kubeflow/training/constants/constants.py
**What this PR does / why we need it**: Currently certain operations like tailing logs from the Python sdk fail against the latest version of the training operator due to a label mismatch; fix that. With this patch I can now tail the logs of a TFJob with the training operator deployed from 1.4 and from master.
**Which issue(s) this PR fixes:**
Fixes #1587.
**Checklist:**
> Look for fully-qualified job role label in Python sdk

- pkg/controller.v1/pytorch/pytorchjob_controller.go
There can be pod level failures caused by the system, which would previously caused the entire job to fail on all policies except ExitCode. See also #1570 
Works together with https://github.com/kubeflow/common/pull/189
Fixes #1570
**Checklist:**
> Restart job on failure for Always,OnFailure Policy

- pkg/controller.v1/pytorch/pytorchjob_controller.go
> fix Pytorjob status inaccuracy when task replica scale down

- pkg/common/util/util.go
- pkg/common/util/util_test.go
- pkg/controller.v1/mpi/mpijob_controller.go
- pkg/controller.v1/mxnet/mxjob_controller.go
- pkg/controller.v1/pytorch/pytorchjob_controller.go
- pkg/controller.v1/tensorflow/job_test.go
- pkg/controller.v1/tensorflow/tfjob_controller.go
- pkg/controller.v1/xgboost/xgboostjob_controller.go
Signed-off-by: Garrybest <garrybest@foxmail.com>
When reconciling jobs, if expire time is not up yet, the `common.JobController` would [requeue](https://github.com/kubeflow/common/blob/21f5ba8833a2e21df17601497a08396c9bae9ab2/pkg/controller.v1/common/job.go#L346-L352) the object into a `FakeWorkQueue`, which does not work in Reconcilers.
I would like to check TTL after finished and requeue the object until expire time is up if necessary.
Fixes #1533
**Checklist:**
> fix: requeue when expire time is not up yet

- pkg/controller.v1/mpi/mpijob_controller.go
Before migrate v1 MPI operator to training-operator，only when all the workers of MPIJob are ready and the launcher of MPIJob is running，the state of MPIJob can change from Created to Running. So It is more reasonable to keep the STATE of MPIJob  as created when NotEnoughResources.
Fixes #1617
**Checklist:**
> fix: MPIJob worker still running when NotEnoughResources

- pkg/controller.v1/tensorflow/tfjob_controller.go
As describe in issues linked below, the tfjob with restartPolicy=ExitCode won’t work. If workers/evaluators got exited, the whole job will be set to failed instead of restarting, which is not expected.
Need for more comments! Thank you in advance! :D
Fixes #1560, https://github.com/kubeflow/common/issues/186
**Checklist:**
> fix: tfjob with restartPolicy=ExitCode not work

- cmd/training-operator.v1/main.go
This PR fixes the default leader election ID which has an invalid format. If one enables leader election through `leader-elect=true`, the operator fails to start with the following error:
**Before:**
```
> go run ./cmd/training-operator.v1/main.go -leader-elect=true --namespace kubeflow
1.6589798403535447e+09  INFO    controller-runtime.metrics      Metrics server is starting to listen    {"addr": ":8080"}
1.6589798403555276e+09  INFO    setup   starting manager
1.6589798403558226e+09  INFO    Starting server {"path": "/metrics", "kind": "metrics", "addr": "[::]:8080"}
1.6589798403558557e+09  INFO    Starting server {"kind": "health probe", "addr": "[::]:8081"}
I0727 20:44:00.356108 1889297 leaderelection.go:248] attempting to acquire leader lease …
```
> Fix the default LeaderElectionID and make it an argument

- pkg/controller.v1/mxnet/mxjob_controller.go
> fix: fix mxnet failed to update StartTime and CompletionTime

- manifests/base/cluster-role.yaml
Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>
This error can be presented if finalizers are not added to the cluster-role
```bash
2022-08-04T14:45:50.154Z        ERROR   controller-runtime.manager.controller.pytorchjob-controller     Reconciler error        {"name": "pytorch-simple", "namespace": "kubeflow", "error": "Operation cannot be fulfilled on pytorchjobs.kub
eflow.org \"pytorch-simple\": the object has been modified; please apply your changes to the latest version and try again"}                                                                                                                   
github.com/go-logr/zapr.(*zapLogger).Error …
```
> Add finalizers to cluster-role

- pkg/controller.v1/mxnet/mxjob_controller.go
> fix: support MxNet single host training when update mxJob status

- .github/workflows/integration-tests.yaml
- .github/workflows/unittests.yaml
- Makefile
Signed-off-by: tenzen-y <yuki.iwai.tz@gmail.com>
I upgraded the Kubernetes version for tests.
Fixes #1665 
**Checklist:**
> Upgrade kubernetes versoin for test

- sdk/python/kubeflow/training/constants/constants.py
I think, we should remove Final keyword from our constants in Python SDK.
Final is available only in >= Python 3.8 version: https://peps.python.org/pep-0591/
Currently, we say that [Training Operator SDK is supported in Python 3 and 3.7](https://github.com/kubeflow/training-operator/blob/master/sdk/python/setup.py#L45-L47).
Also, it's better to be compatible with other Kubeflow components SDKs, [e.g. with Kubeflow Pipelines](https://github.com/kubeflow/pipelines/blob/master/sdk/python/setup.py#L85-L87).
We can think about Python upgrade in the future releases/versions across various Kubeflow components.
cc @johnugeorge @tenzen-y @anencore94
> [SDK] Remove Final Keyword from constants

- .github/workflows/integration-tests.yaml
- .github/workflows/publish-images.yaml
- .github/workflows/template-publish-image/action.yaml
- .github/workflows/test-go.yaml
- .github/workflows/unittests.yaml
Signed-off-by: tenzen-y <yuki.iwai.tz@gmail.com>
To resolve the following warning, I upgraded the following actions:
- `actions/checkout` -> v3
- `docker/metadata-action` -> v4
- `docker/setup-buildx-action` -> v2
- `docker/login-action` -> v2
- `docker/build-push-action` -> v3
```shell
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, docker/setup-buildx-action, docker/login-action, docker/metadata-action, docker/build-push-action, docker/build-push-action, docker/login-action, docker/setup-buildx-action, actions/checkout
```
**Which issue(s) this PR …
> [chore] Upgrade some actions version

- pkg/common/util/reconciler.go
- pkg/common/util/reconciler_test.go
- pkg/controller.v1/mxnet/mxjob_controller.go
- pkg/controller.v1/pytorch/pytorchjob_controller.go
- pkg/controller.v1/tensorflow/tfjob_controller.go
- pkg/controller.v1/xgboost/xgboostjob_controller.go
Signed-off-by: Peng Gao <peng.gao.dut@gmail.com>
Make a temporary logger for generic object instead of being nil.
Fixes  #1679 #1678
**Checklist:**
> Make a generic logger instead of the nil logger on dependent update

- .github/workflows/template-publish-image/action.yaml
I have added support for Linux/ppc64le architecture in GitHub actions. using QEMU. It enables the CI for Linux/ppc64le. Please review and merge.
Fixes #1664 
**Checklist:**
> Adding support for linux/ppc64le in github actions for training-operator

- pkg/controller.v1/mpi/mpijob_controller.go
common package uses jobStatus to update job. This
fix makes up the loss of start and completion time of status.
Signed-off-by: Peng Gao <peng.gao.dut@gmail.com>
Fixes #
**Checklist:**
> Fix status lost

- examples/tensorflow/distribution_strategy/keras-API/Dockerfile
The TF image does not work on Mac M1. Switching to use Python base image and install TF from there. Also bumped TF versions.
Verified that the example works.
> fix: Mac M1 compatible Dockerfile and bump TF version

- cmd/training-operator.v1/main.go
- pkg/controller.v1/mpi/mpijob_controller.go
- pkg/controller.v1/mpi/suite_test.go
- pkg/controller.v1/mxnet/mxjob_controller.go
- pkg/controller.v1/paddlepaddle/paddlepaddle_controller.go
- pkg/controller.v1/paddlepaddle/paddlepaddle_controller_suite_test.go
- pkg/controller.v1/pytorch/pytorchjob_controller.go
- pkg/controller.v1/pytorch/pytorchjob_controller_suite_test.go
- pkg/controller.v1/register_controller.go
- pkg/controller.v1/tensorflow/suite_test.go
- pkg/controller.v1/tensorflow/tfjob_controller.go
- pkg/controller.v1/xgboost/xgboostjob_controller.go
**Which issue(s) this PR fixes** : https://github.com/kubeflow/training-operator/issues/1706
**Checklist:**
> fix https://github.com/kubeflow/training-operator/issues/1706

- examples/tensorflow/distribution_strategy/keras-API/multi_worker_strategy-with-keras.py
The current implementation is experimental and deprecated.
```
_CollectiveAllReduceStrategyExperimental.__init__ (from tensorflow.python.distribute.collective_all_reduce_strategy) is deprecated and will be removed in a future version.
Instructions for updating:
use distribute.MultiWorkerMirroredStrategy instead
```
> chore: Update the use of MultiWorkerMirroredStrategy in TF

- examples/tensorflow/simple.yaml
I fixed indents on examples for tensorflow.
Fixes #
**Checklist:**
> Fix indents on examples for tensorflow

- pkg/controller.v1/paddlepaddle/paddlepaddle_controller.go
I fixed predicates of the paddlepaddle-controller for scheduling.volcano.sh/v1beta1 PodGroup.
Fixes #1729 
**Checklist:**
> Fix predicates of paddlepaddle-controller for scheduling.volcano.sh/v1beta1 PodGroup

- examples/pytorch/elastic/echo/Dockerfile
I upgraded PyTorch version to v1.13.1 to fix the scaledown error in echo example.
Fixes #1504 
**Checklist:**
> To fix scaledown error, upgrade PyTorch version to v1.13.1 in echo example

- Makefile
- manifests/base/crds/kubeflow.org_mpijobs.yaml
- manifests/base/crds/kubeflow.org_mxjobs.yaml
- manifests/base/crds/kubeflow.org_paddlejobs.yaml
- manifests/base/crds/kubeflow.org_pytorchjobs.yaml
- manifests/base/crds/kubeflow.org_tfjobs.yaml
- manifests/base/crds/kubeflow.org_xgboostjobs.yaml
Trim down CRD descriptions to avoid the following apply errors:
```shell
The CustomResourceDefinition "pytorchjobs.kubeflow.org" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```
Fixes #
**Checklist:**
> Trim down CRD descriptions

- pkg/controller.v1/xgboost/xgboostjob_controller.go
Currently, the xgboostjob-controller adds a `Running` condition to the `status.conditions` field of XGBoostJob when some containers have not been scheduled to Nodes, yet. 
Although, other controllers (e.g., [mxjob-controller](https://github.com/kubeflow/training-operator/blob/0126d96864bd75d13e63cffcf82d91b89140d986/pkg/controller.v1/mxnet/mxjob_controller.go#L353-L444) and [pytorchjob-controller](https://github.com/kubeflow/training-operator/blob/0126d96864bd75d13e63cffcf82d91b89140d986/pkg/controller.v1/pytorch/pytorchjob_controller.go#L363-L490)) do not add `Running` condition to the `status.condition` of CustomJob in that situation.
For example, when we deploy XGBoostJob with coscheduling to …
> Fix XGBoost conditions bug

- .github/workflows/integration-tests.yaml
- pkg/controller.v1/mxnet/mxjob_controller.go
- scripts/gha/setup-training-operator.sh
- sdk/python/kubeflow/training/api/training_client.py
- sdk/python/kubeflow/training/constants/constants.py
- sdk/python/kubeflow/training/utils/utils.py
- sdk/python/test/e2e/constants.py
- sdk/python/test/e2e/test_e2e_mpijob.py
- sdk/python/test/e2e/test_e2e_mxjob.py
- sdk/python/test/e2e/test_e2e_paddlejob.py
- sdk/python/test/e2e/test_e2e_pytorchjob.py
- sdk/python/test/e2e/test_e2e_tfjob.py
- sdk/python/test/e2e/test_e2e_xgboostjob.py
- sdk/python/test/e2e/utils.py
I added the E2E test for gang-scheduling.
Also, I added functions to apply patches to CustomJob resources to Python SDK.
Follow up on #1724.
**Checklist:**
> Add E2E test for gang-scheduling

- sdk/python/kubeflow/training/api/training_client.py
This change will allow user to create `TrainingClient` without kube config using Client Configuration and Bearer Token.
It is useful for remote-like and enterprise usage of our SDK.
Similar to this example: https://github.com/kubernetes-client/python/blob/67f9c7a97081b4526470cad53576bc3b71fa6fcc/examples/remote_cluster.py#L31
/assign @kubeflow/wg-training-leads @tenzen-y @anencore94
> [SDK] Use Training Client without Kube Config

- pkg/apis/kubeflow.org/v1/mxnet_validation.go
- pkg/apis/kubeflow.org/v1/mxnet_validation_test.go
- pkg/apis/kubeflow.org/v1/paddlepaddle_validation.go
- pkg/apis/kubeflow.org/v1/paddlepaddle_validation_test.go
- pkg/apis/kubeflow.org/v1/pytorch_validation.go
- pkg/apis/kubeflow.org/v1/pytorch_validation_test.go
- pkg/apis/kubeflow.org/v1/tensorflow_validation.go
- pkg/apis/kubeflow.org/v1/tensorflow_validation_test.go
- pkg/apis/kubeflow.org/v1/xgboost_validation.go
- pkg/apis/kubeflow.org/v1/xgboost_validation_test.go
- pkg/controller.v1/mxnet/mxjob_controller.go
- pkg/controller.v1/paddlepaddle/paddlepaddle_controller.go
- pkg/controller.v1/pytorch/pytorchjob_controller.go
- pkg/controller.v1/tensorflow/tfjob_controller.go
- pkg/controller.v1/xgboost/xgboostjob_controller.go
I added validation for verifying that the CustomJob (e.g., TFJob) name meets DNS1035.
Also, I refactored unit tests for validation.
Fixes #1745
**Checklist:**
> Add validation for verifying that the CustomJob (e.g., TFJob) name meets DNS1035

- pkg/controller.v1/pytorch/pytorchjob_controller.go
Signed-off-by: Syulin7 <735122171@qq.com>
Fixes #1751 
**Checklist:**
> Fix the success condition of the job in PyTorchJob's Elastic mode.

- pkg/apis/kubeflow.org/v1/defaulting_utils.go
- pkg/apis/kubeflow.org/v1/mxnet_defaults.go
- pkg/apis/kubeflow.org/v1/mxnet_defaults_test.go
- pkg/apis/kubeflow.org/v1/tensorflow_defaults.go
- pkg/apis/kubeflow.org/v1/tensorflow_defaults_test.go
- pkg/apis/kubeflow.org/v1/xgboost_defaults.go
- pkg/apis/kubeflow.org/v1/xgboost_defaults_test.go
Set the default value of CleanPodPolicy to None.
Fixes #1753 
**Checklist:**
> Set the default value of CleanPodPolicy to None

- pkg/apis/kubeflow.org/v1/defaulting_utils.go
- pkg/apis/kubeflow.org/v1/mxnet_defaults.go
- pkg/apis/kubeflow.org/v1/mxnet_defaults_test.go
- pkg/apis/kubeflow.org/v1/mxnet_validation.go
- pkg/apis/kubeflow.org/v1/mxnet_validation_test.go
- pkg/apis/kubeflow.org/v1/paddlepaddle_validation.go
- pkg/apis/kubeflow.org/v1/paddlepaddle_validation_test.go
- pkg/apis/kubeflow.org/v1/pytorch_validation.go
- pkg/apis/kubeflow.org/v1/pytorch_validation_test.go
- pkg/apis/kubeflow.org/v1/tensorflow_defaults.go
- pkg/apis/kubeflow.org/v1/tensorflow_defaults_test.go
- pkg/apis/kubeflow.org/v1/tensorflow_validation.go
- pkg/apis/kubeflow.org/v1/tensorflow_validation_test.go
- pkg/apis/kubeflow.org/v1/xgboost_defaults.go
- pkg/apis/kubeflow.org/v1/xgboost_defaults_test.go
- pkg/apis/kubeflow.org/v1/xgboost_validation.go
- pkg/apis/kubeflow.org/v1/xgboost_validation_test.go
- pkg/controller.v1/mpi/mpijob_controller.go
- pkg/controller.v1/mxnet/mxjob_controller.go
- pkg/controller.v1/paddlepaddle/paddlepaddle_controller.go
- pkg/controller.v1/pytorch/pytorchjob_controller.go
- pkg/controller.v1/tensorflow/tfjob_controller.go
- pkg/controller.v1/xgboost/xgboostjob_controller.go
Cherry pick commits from master to release 1.6 branch
/hold
> Cherry pick commits 

- .github/workflows/integration-tests.yaml
This PR fixes the following error in CI:
```shell
[integration-test (v1.25.2, none, 3.8)](https://github.com/kubeflow/training-operator/actions/runs/4166979917/jobs/7211993949#step:3:9)
The `python-version` input is not set. The version of Python currently in `PATH` will be used.
```
https://github.com/kubeflow/training-operator/actions/runs/4166979917
Fixes #
**Checklist:**
> Fix Python installation in CI

- cmd/training-operator.v1/main.go
- pkg/config/config.go
- pkg/controller.v1/pytorch/initcontainer.go
- pkg/controller.v1/pytorch/initcontainer_test.go
Replace infinite loop in `init-pytorch` container with a finite loop.
Fixes #1734
**Checklist:**
> fix infinite loop in init-pytorch container

- scripts/gha/setup-training-operator.sh
I pinned the scheduler-plugins version to fix CI errors.
Ref #1769 
**Checklist:**
> Pin the scheduler-plugins version

- .github/workflows/integration-tests.yaml
- hack/python-sdk/gen-sdk.sh
- sdk/python/test/conftest.py
- sdk/python/test/e2e/conftest.py
- sdk/python/test/e2e/test_e2e_mpijob.py
- sdk/python/test/e2e/test_e2e_mxjob.py
- sdk/python/test/e2e/test_e2e_paddlejob.py
- sdk/python/test/e2e/test_e2e_pytorchjob.py
- sdk/python/test/e2e/test_e2e_tfjob.py
- sdk/python/test/e2e/test_e2e_xgboostjob.py
* Currently, the `JOB_NAMESPACE` is hardcoded in e2e test files. This limits a user to run these tests in the `default` namespace. A user might want to run these tests in a different namespace instead of the default namespace. One use case is using these tests in Kubeflow mode for training-operator conformance tests (or some other testing). As per the [design doc of the conformance test](https://docs.google.com/document/d/1TRUKUY1zCCMdgF-nJ7QtzRwifsoQop0V8UnRo-GWlpI/edit#heading=h.tubso4j7bqvw), it seems we want to run these tests in `kf-conformance` namespace.
* Currently, the training client initialization code looks for Kube config which may not be present if these tests are running inside k8s cluster. Fix training client initialization code to …
> E2e test in k8s cluster and Namespace option

- sdk/python/kubeflow/training/constants/constants.py
- sdk/python/kubeflow/training/utils/utils.py
- sdk/python/test/e2e/test_e2e_mpijob.py
- sdk/python/test/e2e/test_e2e_mxjob.py
- sdk/python/test/e2e/test_e2e_paddlejob.py
- sdk/python/test/e2e/test_e2e_pytorchjob.py
- sdk/python/test/e2e/test_e2e_tfjob.py
- sdk/python/test/e2e/test_e2e_xgboostjob.py
**What this PR does / why we need it**: 
* Currently none of the e2e tests run successfully in `istio-enabled` namespaces. All training jobs (created by tests) get stuck in `Running` state and eventually these tests fail after timeout. I think it's because istio sidecar keeps running even after the main containers runs successfully.
* This is required as we want to run these tests as part of the training operator conformance test. As per the [design doc of training operator conformance test](https://docs.google.com/document/d/1TRUKUY1zCCMdgF-nJ7QtzRwifsoQop0V8UnRo-GWlpI/edit#heading=h.tubso4j7bqvw), all these tests will run in the namespace created by the Kubeflow profile resource which is istio-enabled by default.
* Disable Istio sidecar injection for training job containers.
* Testing: …
> Disable istio-sidecar injection

- .github/workflows/publish-conformance-images.yaml
- sdk/python/Dockerfile.conformance
- sdk/python/README.md
- sdk/python/conformance/run.sh
- sdk/python/test/e2e/test_e2e_mpijob.py
- sdk/python/test/e2e/test_e2e_mxjob.py
- sdk/python/test/e2e/test_e2e_paddlejob.py
- sdk/python/test/e2e/test_e2e_pytorchjob.py
- sdk/python/test/e2e/test_e2e_tfjob.py
- sdk/python/test/e2e/test_e2e_xgboostjob.py
* This PR contains the changes required for [training operator conformance test](https://docs.google.com/document/d/1TRUKUY1zCCMdgF-nJ7QtzRwifsoQop0V8UnRo-GWlpI/edit#heading=h.qkn0t2llzyaq).
* Added `Dockerfile.conformance` docker file to build container which contains test required for conformance.
* Added `publish-conformance-images.yaml` github action to publish conformance test docker image as part of CI.
* pass `resources` parameter to each container as it is required if the containers running in the namespace have `resourceQuotaSpec` specified. For conformance namespace, we're specifying `resourceQuotaSpec`
https://github.com/kubeflow/kubeflow/blob/master/conformance/1.5/setup.yaml#L24-L28
* Testing:
- Tested updated test on local.
- Created …
> Containerize e2e tests for training operator conformance

- hack/update-codegen.sh
Unify the access to $(go env GOPATH) when generating code.
Fixes #1783
**Checklist:**
> Find defaulter-gen in $(go env GOPATH) instead of ${GOPATH}

- sdk/python/test/e2e/test_e2e_pytorchjob.py
- sdk/python/test/e2e/utils.py
* Due to the resources (CPU) crunch in the GitHub actions VM, we have limited CPUs in e2e tests. As a result of this, the execution time of jobs has increased.
* Currently PyTorch test job is taking around 10 mins to complete. Because of this PyTorch test job fails sometimes. We have a timeout period of 10 mins in the `wait_for_job_conditions` functions.
* One approach is if we somehow reduce the running time of the PyTorch job. But for this, we will need to build a new image and push it on docker. This can create issues in CI because of the docker pull rate limit.
* In this PR, I have made `timeout` configurable from the e2e test and increased the timeout to 15 mins for PyTorch job.
**Checklist:**
> make timeout configurable from e2e tests

- go.mod
- pkg/controller.v1/xgboost/status.go
- pkg/controller.v1/xgboost/status_test.go
- pkg/controller.v1/xgboost/xgboostjob_controller.go
I fixed the reconciling error in XGBoost Job.
When XGBoostJob is completed (succeeded or failed) before the controller sets a `Running` condition, XGBoostJob finishes without a `Running` condition.
So, I modified the controller so that the controller can set a `Running` condition when the XGboostJob is completed and doesn't have a `Running` condition.
Part-of #1779
**Checklist:**
> Set a Running condition when the XGBoostJob is completed and doesn't have a Running condition

- pkg/controller.v1/tensorflow/tensorflow.go
Fixes # https://github.com/kubeflow/training-operator/issues/1795
Use Cluster instead of sparseCluster in TFJob DynamicWorker.
I will try to add an example for this feature later. Ref: https://github.com/kubeflow/training-operator/issues/1200
> Use Cluster instead of sparseCluster in TFJob DynamicWorker

- examples/xgboost/lightgbm-dist/xgboostjob_v1_lightgbm_dist_training.yaml
- examples/xgboost/smoke-dist/xgboostjob_v1_rabit_test.yaml
- examples/xgboost/smoke-dist/xgboostjob_v1alpha1_rabit_test.yaml
- examples/xgboost/xgboost-dist/xgboostjob_v1_iris_predict.yaml
- examples/xgboost/xgboost-dist/xgboostjob_v1_iris_train.yaml
- examples/xgboost/xgboost-dist/xgboostjob_v1alpha1_iris_predict.yaml
- examples/xgboost/xgboost-dist/xgboostjob_v1alpha1_iris_predict_local.yaml
- examples/xgboost/xgboost-dist/xgboostjob_v1alpha1_iris_train.yaml
- examples/xgboost/xgboost-dist/xgboostjob_v1alpha1_iris_train_local.yaml
> xgb yaml container name should be consistent with xgb job default container name

- sdk/python/test/e2e/utils.py
In E2E, after we created Jobs with unschedulable configurations, we verify the number of conditions is 1 when using scheduler plugins for gang scheduling.
But, the test seems flaky, as reported in #1779.
So, I modified the test to verify whether unschedulable Jobs have a `Created` condition and don't have a `Running` condition instead of the current way.
Fixes #1779 
**Checklist:**
> Improve E2E tests for the gang-scheduling

- pkg/common/util/util.go
- pkg/controller.v1/mpi/mpijob_controller.go
- pkg/controller.v1/mxnet/mxjob_controller.go
- pkg/controller.v1/paddlepaddle/paddlepaddle_controller.go
- pkg/controller.v1/pytorch/pytorchjob_controller.go
- pkg/controller.v1/tensorflow/tfjob_controller.go
- pkg/controller.v1/xgboost/xgboostjob_controller.go
If job is recreated using the deleted job name while the deleted job pods are stuck in `Terminating` state ,  the func `GetPodsForJob` maybe incorrect. 
**Checklist:**
> GetPodsForJob check the pod owner reference job uid

- pkg/controller.v1/tensorflow/job_test.go
I fixed the flaky test case, `[It] should delete job when expired time is up` for TFJob.
Fixes #1802
**Checklist:**
> Fix flaky test: [It] should delete job when expired time is up

- hack/update-codegen.sh
Current scripts to generate codes, such as for the client-go and openapi, deeply depend on the local environment.
So, to avoid that not good situation, I introduced `$(go list -m -f '{{.Dir}}' "${pkg_name}")"`.
Fixes #
**Checklist:**
> Avoid to depend on local env when installing the code-generators

- .github/workflows/integration-tests.yaml
- go.mod
- go.sum
- manifests/base/rbac/role.yaml
- pkg/controller.v1/mpi/mpijob_controller.go
- pkg/controller.v1/mxnet/mxjob_controller.go
- pkg/controller.v1/paddlepaddle/paddlepaddle_controller.go
- pkg/controller.v1/pytorch/pytorchjob_controller.go
- pkg/controller.v1/tensorflow/tfjob_controller.go
- pkg/controller.v1/xgboost/xgboostjob_controller.go
- scripts/gha/setup-training-operator.sh
> ⚠️ Breaking Changes: Upgrade Scheduler Plugins version to v0.25.7

- Makefile
run make test on darwin os
Fixes #
**Checklist:**
> support make test on darwin

- .github/workflows/integration-tests.yaml
- scripts/gha/setup-training-operator.sh
add e2e test of volcano gang-schedule
1. put patching gang-scheduler-name before installing gang-scheduler-plugin
2. split version of volcano.sh/apis without relationship of k8s
Fixes #1736
**Checklist:**
> e2e testing support volcano gang-scheduler

- sdk/python/test/e2e/utils.py
When enabling the gang-scheduling, we don't check whether jobs have been pending for a while in e2e.
So tests for the gang-scheduling will pass if jobs meet the `Created=true` and `Running=false` conditions for just a moment.
I added a check that jobs have been pending for a while.
Also, I fixed a test bug that `volcano` isn't set to jobs as a schedulerName when testing for volcano integration.
Note: I faced errors in https://github.com/kubeflow/training-operator/pull/1834.
Fixes #
**Checklist:**
> Add check pods are not scheduled when testing gang-scheduler integrations in e2e

- pkg/controller.v1/mpi/mpijob.go
- pkg/controller.v1/mpi/mpijob_controller.go
- pkg/controller.v1/mpi/mpijob_controller_test.go
When the container is equipped with Intel MPI, the end user has had to manually add Intel MPI specific env variables for the MPIJob. This modifies the operator to add the variables with default values, if there are no user defined variables.
> Add default Intel MPI env variables to MPIJob

- pkg/controller.v1/mpi/mpijob.go
- pkg/controller.v1/mpi/mpijob_controller.go
- pkg/controller.v1/tensorflow/tfjob_controller.go
/kind cleanup
add volcano task spec annotation already done in decorator
Fixes #
**Checklist:**
> remove duplicate code of add task spec annotation

- .github/workflows/integration-tests.yaml
get volcano scheduler log and describe podgroup when e2e test failed
Fixes #
**Checklist:**
> fetch volcano log when e2e failed

- pkg/controller.v1/mpi/mpijob_controller_test.go
- pkg/controller.v1/paddlepaddle/paddlepaddle_controller_test.go
- pkg/controller.v1/pytorch/pytorchjob_controller_test.go
- pkg/controller.v1/tensorflow/job_test.go
- pkg/controller.v1/tensorflow/pod_test.go
- pkg/controller.v1/tensorflow/status_test.go
- pkg/controller.v1/tensorflow/suite_test.go
- pkg/controller.v1/tensorflow/testutil/pod.go
- pkg/util/testutil/constants.go
I modified all Eventually tests to fix flaky tests:
1. Commonize `timeout` and `interval`.
2. Set `timeout` and `interval` to all Eventually tests
Fixes #1820
Fixes: #1822
Fixes: #1844
Related to #1816 
**Checklist:**
> Set timeout and interval to all Eventually tests

- pkg/common/interface.go
- pkg/controller.v1/common/pod.go
- pkg/controller.v1/mpi/mpijob_controller.go
- pkg/controller.v1/mxnet/mxjob_controller.go
- pkg/controller.v1/paddlepaddle/paddlepaddle_controller.go
- pkg/controller.v1/pytorch/pytorchjob_controller.go
- pkg/controller.v1/tensorflow/tfjob_controller.go
- pkg/controller.v1/xgboost/xgboostjob_controller.go
I modified the following items to consolidate tfjob-operator to training-operator fully:
1. Add the `GetFrameworkName` function to the `Controller` interface.
2. Remove the `ReconcilePods` from the tfjob-controller to stop overriding the method of the `JobController`.
3. Adopt `ReconcilePods` of the `JobController` to TFJob.
Fixes #1727 
**Checklist:**
> Fully consolidate tfjob-operator to training-operator

- pkg/controller.v1/common/job.go
- pkg/controller.v1/common/pod.go
- pkg/controller.v1/mpi/mpijob.go
- pkg/controller.v1/mpi/mpijob_controller.go
- pkg/controller.v1/mxnet/mxjob_controller.go
- pkg/controller.v1/paddlepaddle/paddlepaddle_controller.go
- pkg/controller.v1/pytorch/pytorchjob_controller.go
- pkg/controller.v1/tensorflow/job_test.go
- pkg/controller.v1/tensorflow/tfjob_controller.go
- pkg/controller.v1/tensorflow/tfjob_controller_test.go
- pkg/controller.v1/xgboost/status.go
- pkg/controller.v1/xgboost/status_test.go
- pkg/controller.v1/xgboost/xgboostjob_controller.go
- pkg/reconciler.v1/common/job.go
- pkg/util/status.go
Currently, jobs use different reasons for Condition and Event even if the situation is the same. (`JobCreated` vs `TFJobCreated`)
For example, the JobController uses `JobXXX` (XXX is the reason such as Failed), and the pytorchjob-controller uses `PyTorchJobXXX` like this:
https://github.com/kubeflow/training-operator/blob/fcdf9a3897bf601455867f1a4b3c831f014fb77a/pkg/controller.v1/common/job.go#L227
https://github.com/kubeflow/training-operator/blob/fcdf9a3897bf601455867f1a4b3c831f014fb77a/pkg/controller.v1/pytorch/pytorchjob_controller.go#L555
So I modified the reasons for Condition and Event so that the Jobs use consistently the same reason format `${KIND}${REASON}` like `PyTorchJobCreated`  in the same situation. …
> Use the same reasons for Condition and Event

- pkg/apis/kubeflow.org/v1/defaulting_utils.go
- pkg/apis/kubeflow.org/v1/mpi_defaults.go
- pkg/apis/kubeflow.org/v1/mpi_defaults_test.go
- pkg/apis/kubeflow.org/v1/mxnet_defaults.go
- pkg/apis/kubeflow.org/v1/mxnet_defaults_test.go
- pkg/apis/kubeflow.org/v1/paddlepaddle_defautls.go
- pkg/apis/kubeflow.org/v1/pytorch_defaults.go
- pkg/apis/kubeflow.org/v1/tensorflow_defaults.go
- pkg/apis/kubeflow.org/v1/tensorflow_defaults_test.go
- pkg/apis/kubeflow.org/v1/xgboost_defaults.go
- pkg/apis/kubeflow.org/v1/xgboost_defaults_test.go
- pkg/controller.v1/mpi/mpijob_controller_test.go
- pkg/controller.v1/tensorflow/testutil/tfjob.go
- test_job/apis/test_job/v1/defaults.go
I made the `cleanPodPolicyPointer` function global.
Fixes #
**Checklist:**
> Make the cleanPodPolicyPointer function global

- pkg/controller.v1/paddlepaddle/envvar.go
- pkg/controller.v1/pytorch/envvar.go
- pkg/controller.v1/xgboost/xgboost.go
As mentioned in the comment, set PYTHONUNBUFFERED to non zero value means to set python unbuffered, which is the desired state.
**Checklist:**
> set PYTHONUNBUFFERED to 1

- hack/python-sdk/swagger.json
- manifests/base/crds/kubeflow.org_mpijobs.yaml
- manifests/base/crds/kubeflow.org_mxjobs.yaml
- manifests/base/crds/kubeflow.org_paddlejobs.yaml
- manifests/base/crds/kubeflow.org_pytorchjobs.yaml
- manifests/base/crds/kubeflow.org_tfjobs.yaml
- manifests/base/crds/kubeflow.org_xgboostjobs.yaml
- pkg/apis/kubeflow.org/v1/common_types.go
- pkg/apis/kubeflow.org/v1/openapi_generated.go
- sdk/python/docs/KubeflowOrgV1JobStatus.md
- sdk/python/kubeflow/training/models/kubeflow_org_v1_job_status.py
- sdk/python/test/test_kubeflow_org_v1_job_status.py
I made `jobStatus.Condition` and `jobStatus.replicaStatus` optional. We shouldn't make those fields necessary since those fields can be null. 
Fixes #
**Checklist:**
> Make Condition and ReplicaStatus optional

- pkg/controller.v1/paddlepaddle/paddlepaddle_controller_test.go
I implemented integration test for PaddleJob related to suspend semantics.
Fixes #
**Checklist:**
> Implement integration test for PaddleJob related to suspend semantics

- pkg/controller.v1/mxnet/mxjob_controller_test.go
- pkg/controller.v1/mxnet/suite_test.go
I implemented integration test for MXJob related to suspend semantics.
Fixes #
**Checklist:**
> Implement integration test for MXJob related to suspend semantics

- pkg/controller.v1/common/job.go
- pkg/controller.v1/common/pod.go
- pkg/controller.v1/mpi/mpijob_controller.go
- pkg/controller.v1/mxnet/mxjob_controller.go
- pkg/controller.v1/paddlepaddle/paddlepaddle_controller.go
- pkg/controller.v1/pytorch/pytorchjob_controller.go
- pkg/controller.v1/tensorflow/job_test.go
- pkg/controller.v1/tensorflow/tfjob_controller.go
- pkg/controller.v1/xgboost/xgboostjob_controller.go
- pkg/reconciler.v1/common/job.go
- pkg/util/status.go
- pkg/util/status_test.go
Because the result of `commonutil.UpdateJobConditions()` is always nil, we shouldn't return an error.
Fixes #
**Checklist:**
> Fix error check that never occurs

- cmd/training-operator.v1/main.go
The training-operator has many controllers, and each controller needs access to the kube-apiserver while launching.
So, in the heavy load cluster, the training operator can not start by timeout period.
Related to: #1841
By this PR, the training operator starts the manager not to wait for completed to register all controllers.
Fixes #
**Checklist:**
> Set up controllers using goroutines to start the manager quickly

- Makefile
- build/images/training-operator/Dockerfile
- docs/development/developer_guide.md
- go.mod
- hack/swagger/go.mod
I upgraded Go version to v1.20.
Fixes #
**Checklist:**
> Upgrade Go version to v1.20

- pkg/apis/kubeflow.org/v1/pytorch_defaults.go
- pkg/apis/kubeflow.org/v1/pytorch_types.go
- pkg/apis/kubeflow.org/v1/pytorch_validation.go
- pkg/controller.v1/pytorch/envvar.go
- pkg/controller.v1/pytorch/hpa.go
- pkg/controller.v1/pytorch/initcontainer.go
- pkg/controller.v1/pytorch/pytorchjob_controller.go
- pkg/controller.v1/pytorch/pytorchjob_controller_test.go
- pkg/controller.v1/register_controller.go
I replaced `Pytoch` with `PyTorch`.
Fixes #
**Checklist:**
> Replace Pytorch with PyTorch

- pkg/controller.v1/mpi/mpijob_controller.go
- pkg/controller.v1/mpi/mpijob_controller_test.go
- pkg/controller.v1/xgboost/xgboostjob_controller_test.go
I implemented integration test for MPIJob v1 related to suspend semantics.
Fixes #
**Checklist:**
> Implement integration test for MPIJob v1 related to suspend semantics

- pkg/controller.v1/common/pod_test.go
I refactored core/pod tests to remove test_job dependencies.
Part-of #1816
**Checklist:**
> Refactor core/pod tests

- README.md
I added Training WG Community Call to our README.
cc @kubeflow/wg-training-leads @tenzen-y
> Add Training WG Community Call

- pkg/controller.v1/mpi/mpijob_controller.go
**What this PR does / why we need it**: If a MPI job is supposed to run with a certain K8s service account, then this service account can now be used. 
Fixes #1897 
**Checklist:**
> Creating service account where approriate for MPI Job

- .github/workflows/integration-tests.yaml
- sdk/python/test/e2e/test_e2e_xgboostjob.py
I replaced the image with community hosted one.
follow up: https://github.com/kubeflow/training-operator/pull/1913
Fixes #
**Checklist:**
> Replace XGBoost image for E2E with community hosted

- examples/mxnet/mxjob_dist_v1.yaml
- sdk/python/test/e2e/test_e2e_mxjob.py
I replaced the MXJob E2E image with a community-hosted image. Also, I fixed the bug in a MXJob example.
Fixes #
**Checklist:**
> Use a community hosted image in MXJob E2E

- cmd/training-operator.v1/main.go
The `monitoring-port` flag is wrongly used as the webhook server port. This PR renames the `monitoring-port` flag to `webook-server-port`. As this is a potentially breaking change (e.g. when used in Helm charts) this needs to be marked as such.
In the pre 0.16.x time of the `controller-runtime` the `Port` config is defined here:
https://github.com/kubernetes-sigs/controller-runtime/blob/v0.15.2/pkg/manager/manager.go#L287
**Checklist:**
/cc @tenzen-y
> ⚠️ Breaking Changes: Rename `monitoring-port` flag to `webook-server-port`

- cmd/training-operator.v1/main.go
> Check podGroup CRD for the volcano and the scheudler-plugins as default.

- .github/workflows/template-publish-image/action.yaml
To avoid "No space left on device" error, we need to free the root volume on the github runner.
> [Publish Image (mxnet-auto-tuning, examples/mxnet/tune/Dockerfile, examples/mxnet/tune) / Publish Image](https://github.com/kubeflow/training-operator/actions/runs/6470851389/job/17567949458)
System.IO.IOException: No space left on device : '/home/runner/runners/2.309.0/_diag/Worker_20231010-143538-utc.log'
at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
at System.Diagnostics.TextWriterTraceListener.Flush()
at …
> Increase the root volume size on the github runner when building container images

- OWNERS
I added myself to Training Operator approvers to make it easier to approve PRs and merge them.
/assign @tenzen-y @johnugeorge
> Add @andreyvelich to Approvers

- sdk/python/kubeflow/training/api/training_client.py
- sdk/python/kubeflow/training/utils/utils.py
This PR eliminates the code that was setting the log level to `INFO` globally, as documented in [this](https://github.com/kubeflow/training-operator/issues/1942) issue.
The `get_job_logs` implementation needs to be addressed before merging, but I figured it would be easier to talk about with a proper PR @johnugeorge.
Do you want it to not print to stdout by default and just return a data structure that looks like this?
```python
{
pod1: logs,
pod2: logs,
pod3: logs
}
```
Fixes # https://github.com/kubeflow/training-operator/issues/1942
> Avoid modifying log level globally

- pkg/controller.v1/pytorch/envvar.go
In PyTorchJob elastic mode, nproc env may not be set.
Fixes # https://github.com/kubeflow/training-operator/issues/1947
**Checklist:**
> fix nproc env in elastic mode for pytorchjob

- sdk/python/kubeflow/training/api/training_client.py
- sdk/python/kubeflow/training/constants/constants.py
- sdk/python/kubeflow/training/utils/utils.py
Changes needed for #1945 
Fixes #
1. The new Train api is dependent on 1 new function (utils.get_container_spec), and 2 existing functions with some changes (utils.get_pod_template_spec and utils.get_pytorchjob_template)
2. Train api sample is mentioned in the first comment.
3. Train api will be run in elastic mode, and for elastic mode currently it is assumed that there will be 1 master replica.
**Checklist:**
> utils changes needed to add train api

- sdk/python/kubeflow/storage_init_container/Dockerfile
- sdk/python/kubeflow/storage_init_container/abstract_model_provider.py
- sdk/python/kubeflow/storage_init_container/hugging_face.py
- sdk/python/kubeflow/storage_init_container/requirements.txt
- sdk/python/kubeflow/storage_init_container/storage.py
- sdk/python/kubeflow/training/constants/constants.py
- sdk/python/kubeflow/training/utils/utils.py
1. Adding a new folder for creating init container images with a docker file in it.
2. Adding hugging face as the model provider.
3. storage.py will start the download of models to the mount path.
4. changes require python 3.11
Partially Fixes #1945 
**Checklist:**
> Train api init container creation

- examples/pytorch/cpu-demo/Dockerfile
- examples/pytorch/cpu-demo/README.MD
- examples/pytorch/cpu-demo/demo.py
- examples/pytorch/cpu-demo/demo.yaml
Since many user may not find the proper way to run distributed training with `torchrun` with pytorch, here comes the demo.
This is a cpu version to make it easy to run.
**Checklist:**
> torchrun example with cpu version pytorch 

- pkg/controller.v1/pytorch/pytorchjob_controller.go
1. Correcting the function to check if the pod has a master role or not in case there is only 1 worker in the PyTorch job.
Fixes #1961 
**Checklist:**
> isMaster fix

- pkg/controller.v1/pytorch/pytorchjob_controller.go
We shouldn't convert replica type to lower in `IsMasterRole` function for PyTorchJob since the replica type that we send is equal to `Worker` or `Master` as `rtype`: https://github.com/kubeflow/training-operator/blob/master/pkg/controller.v1/common/pod.go#L319
We are doing the same for TFJob: https://github.com/kubeflow/training-operator/blob/master/pkg/controller.v1/tensorflow/tfjob_controller.go#L609.
/assign @johnugeorge @deepanker13 @tenzen-y
> Fix Master Label for PyTorchJob

- sdk/python/kubeflow/training/api/training_client.py
- sdk/python/kubeflow/training/utils/utils.py
Fixes: https://github.com/kubeflow/training-operator/issues/1946.
~~As we discussed, in the issue for `get_job_logs` API, user will see pod logs only if `follow=True` and we use `logger.info()` to print it.~~
If users want to see all messages from TrainingClient APIs, they can override the default logger config in their program:
```
log = logging.getLogger("kubeflow.training.api.training_client")
log.setLevel(logging.DEBUG)
```
Also, I fixed `get_pytorchjob_template` func, since we just need to check if `num_procs_per_worker` and `num_worker_replicas` is set before using it.
**UPDATE:** After discussion on this PR, we decided to use `print()` for the messages that users are required to see while using SDK.
/assign @droctothorpe @johnugeorge @tenzen-y @deepanker13
/hold for the review
> [SDK] Add information about TrainingClient logging

- pkg/controller.v1/common/job.go
> fix: volcano podgroup should has a non-empty queue name

- .flake8
- manifests/overlays/kubeflow/kubeflow-training-roles.yaml
- sdk/python/kubeflow/training/api/training_client.py
- sdk/python/kubeflow/training/constants/constants.py
- sdk/python/kubeflow/training/utils/utils.py
- sdk/python/setup.py
Fixes: https://github.com/kubeflow/training-operator/issues/1863.
This will allow users to get Kubernetes Events for Job and Job's pods via `get_job_logs` API and `verbose` parameter.
Initially, I didn't watch for the events similar to logs with `follow=True` parameter. This can be done later in the following PRs.
The events will be returned in this format:
```
{
"test-kubeflow-worker-0": [
"2024-01-05 22:58:20 Successfully assigned kubeflow-andrey/test-kubeflow-worker-0 to .....",
"2024-01-05 22:58:21 Container image \"docker.io/pytorch/pytorch:1.12.1-cuda11.3-cudnn8-runtime\" already present on machine",
"2024-01-05 22:58:21 Created container pytorch",
"2024-01-05 22:58:21 Started container pytorch"
],
"test-kubeflow-worker-1": [
"2024-01-05 22:58:20 Successfully assigned …
```
> [SDK] Get Kubernetes Events for Job

- .github/workflows/integration-tests.yaml
- sdk/python/kubeflow/training/api/training_client_test.py
- sdk/python/test/e2e/test_e2e_mpijob.py
- sdk/python/test/e2e/test_e2e_mxjob.py
- sdk/python/test/e2e/test_e2e_paddlejob.py
- sdk/python/test/e2e/test_e2e_pytorchjob.py
- sdk/python/test/e2e/test_e2e_tfjob.py
- sdk/python/test/e2e/test_e2e_xgboostjob.py
I added unit test to create PyTorchJob from function.
Also, modified logging level so we can see the E2E results in logs.
/assign @deepak-muley @johnugeorge @droctothorpe
> Add test to create PyTorchJob from func

- .github/workflows/test-python.yaml
- docs/proposals/train_api_proposal.md
- examples/sdk/create-pytorchjob-from-func.ipynb
- sdk/python/kubeflow/training/api/training_client.py
- sdk/python/kubeflow/training/api/training_client_test.py
- sdk/python/kubeflow/training/utils/utils.py
- sdk/python/test/e2e/test_e2e_pytorchjob.py
Currently, user has to set Master and Worker replica since we assign RANK and WORLD_SIZE only if Master is set: https://github.com/kubeflow/training-operator/blob/master/pkg/controller.v1/pytorch/envvar.go#L67.
Thus, I modified SDK to always set Master replicas.
Worker replicas is equal to `num_workers - 1` since we assign `RANK=0` to Master and it behaves like first Worker.
I added TODO in the SDK to track if we could create PyTorchJob without the Master, but it will require Controller changes.
Also, I renamed `num_worker_replicas` to `num_workers` to keep it consistent with `train` API.
/assign @tenzen-y @droctothorpe @johnugeorge @deepanker13
> [SDK] Fix Worker and Master templates for PyTorchJob

- sdk/python/kubeflow/training/api/training_client.py
- sdk/python/kubeflow/training/api/training_client_test.py
- sdk/python/kubeflow/training/constants/constants.py
- sdk/python/kubeflow/training/utils/utils.py
- sdk/python/test/e2e/test_e2e_pytorchjob.py
- sdk/python/test/e2e/utils.py
Blocked by: https://github.com/kubeflow/training-operator/pull/1988.
/hold
I added `resources_per_worker` parameter to `create_job` API.
Also, this has some refactoring for our SDK utils functions:
- I removed validation from `train` API for resource per worker. Let's add the validation in the future if that is required. We might have users who want to do fine-tuning with `train` API on CPUs.
- We have 3 new functions in utils. `get_pod_template_spec` to return Pod template spec, `get_container_spec` to return Container Spec,  `get_command_using_train_func` to return args and command for train function.
- I made a few changes to reduce number of typing errors in Pylance.
Please take a look.
/assign @deepanker13 @johnugeorge @tenzen-y @droctothorpe @kuizhiqing
> [SDK] Add resources per worker for Create Job API

- docs/development/developer_guide.md
- This PR updates the development guide by update the command for installing dependancies to ```go mod tidy``` .
- Also updating the path for the example.
**Checklist:**
> [docs] development guide update

- examples/pytorch/README.md
- examples/pytorch/cpu-demo/demo.yaml
- examples/pytorch/mnist/v1/pytorch_job_mnist_gloo.yaml
- examples/pytorch/mnist/v1/pytorch_job_mnist_mpi.yaml
- examples/pytorch/mnist/v1/pytorch_job_mnist_nccl.yaml
Examples do not work because of istio sidecar injection causing trouble
**Which issue(s) this PR fixes** _(optional, in `Fixes #<issue number>, #<issue number>, ...` format, will close the issue(s) when PR gets merged)_: 
Fixes #1637
**Checklist:**
> Updated examples/pytorch to disable istio sidecar injection

- examples/pytorch/mnist/mnist.py
- examples/sdk/create-pytorchjob-from-func.ipynb
I fixed PyTorch training examples where we forgot to distribute data across PyTorch workers using `DistributedSampler(dataset)`. After that change each PyTorch worker will correctly process chunk of training data.
Also, for FashionMNIST example I removed check if this script is running in distributed mode since for PyTorch we can just set arbitrary values for env variables and run this script in 1 Worker.
/assign @johnugeorge @tenzen-y @kuizhiqing
> Fix Distributed Data Samplers in PyTorch Examples

- .github/workflows/publish-example-images.yaml
Signed-off-by: PeterWright <peterwrighten@gmail.com>
In order to close #2017 
Publish torchrun example via DockerRegistry
Fixes #2017 
**Checklist:**
> publish torchrun example via Dockerfile

- .github/workflows/publish-example-images.yaml
In order to fix context-specific issue stated in #2019 
Fixes #2019 
**Checklist:**
> Fix build workflow config for pytorch-torchrun-example

- .github/workflows/publish-core-images.yaml
- .github/workflows/template-publish-image/action.yaml
Following suggestion from @tenzen-y I have implemented a fix in the CI workflow to add support for multi-platform _linux/amd64_ and _linux/arm64_ image building for the Hugging Face trainer.
The necessary code changes follow from https://github.com/kserve/kserve/pull/3411.
In particular, docker images are pruned and the docker data directory is moved from the root volume to the _/mnt_ volume.
The resulting reduction in disk space usage in the root volume helps the CI workflow to complete without errors.
Fixes https://github.com/kubeflow/training-operator/issues/1986
**Checklist:**
> Support arm64 for Hugging Face trainer

- Makefile
- manifests/base/crds/kubeflow.org_mpijobs.yaml
- manifests/base/crds/kubeflow.org_mxjobs.yaml
- manifests/base/crds/kubeflow.org_paddlejobs.yaml
- manifests/base/crds/kubeflow.org_pytorchjobs.yaml
- manifests/base/crds/kubeflow.org_tfjobs.yaml
- manifests/base/crds/kubeflow.org_xgboostjobs.yaml
Upgrade controller-gen to v0.14.0, in order to avoid runtime panic when conducting `make install` with Go 1.22.
(About this problem and solution is mentioned in [controller-gen: #888](https://github.com/kubernetes-sigs/controller-tools/issues/888))
Fixes #2025
**Checklist:**
> fix: Upgrade controller-gen to v0.14.0

- docs/api/kubeflow.org_v1_generated.asciidoc
- hack/generate-apidoc.sh
Upgrade version of crd-ref-docs v0.0.8 -> v0.0.11. Default version causes panic with Go v1.22. This issue might prevent new developers from contributing to the project.
**Which issue(s) this PR fixes**:
Fixes #2025 . 
**Checklist:**
> Fix: upgrade version of crd-ref-docs, which caused panic with go v1.22

- .github/workflows/template-publish-image/action.yaml
I replaced cache-to mode with min (default value) to avoid the following timeout errors:
```
#7 writing layer sha256:202111e1e67fd289b555ea0a5f198b9919220afe610c9e070268fdd75c3dd5e2 600.1s done
#7 ERROR: error writing layer blob: maximum timeout reached
------
> exporting to GitHub Actions Cache:
------
WARNING: No output specified with docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load
ERROR: failed to solve: error writing layer blob: maximum timeout reached
Error: buildx failed with: ERROR: failed to solve: error writing layer blob: maximum timeout reached
```
https://github.com/kubeflow/training-operator/actions/runs/8635377472/job/2367456 …
> CI: Use a mode=min in the builder cache

- manifests/base/webhook/manifests.yaml
- manifests/base/webhook/patch.yaml
- pkg/controller.v1/mxnet/suite_test.go
- pkg/webhooks/mxnet/mxnet_webhook.go
- pkg/webhooks/webhooks.go
I implemented the webhook warnings to notify users that the MXJob will be deprecated in the v1.9.0.
Fixes #1993
**Checklist:**
> Implement webhook warnings for the MXJob

- docs/development/developer_guide.md
Adding [Kind](https://kind.sigs.k8s.io) as an alternative in getting setup with local Kubernetes.
Fixes #
**Checklist:**
> Updated developer docs to include Kind

- examples/pytorch/simple.yaml
some filepath is wrong in the simple example
Fixes #
**Checklist:**
> fix wrong filepath in the simple example command

- pkg/webhooks/pytorch/pytorchjob_webhook.go
- pkg/webhooks/pytorch/pytorchjob_webhook_test.go
Currently, the PyTorchJob webhook shows a warning only when the Job has the `.spec.nprocPerNode` and the `.spec.elasticPolicy.nProcPerNode`, but we should always show a warning when using the `.spec.elasticPolicy.nProcPerNode`.
Fixes #
**Checklist:**
> PyTorchJob: Always show warnings when using elasticPolicy.nProcPerNode

- sdk/python/kubeflow/storage_initializer/hugging_face.py
- sdk/python/kubeflow/training/api/training_client.py
Related: https://github.com/kubeflow/training-operator/issues/2013.
I added valid docstring for `train` API and added `print` message for users to provide a feedback.
Also, I renamed:
HuggingFaceTrainParams -> HuggingFaceTrainerParams
train_parameters -> trainer_parameters
We need to update SDK examples once we merge this change.
/assign @StefanoFioravanzo @kubeflow/wg-training-leads @deepanker13 
/hold for review
> [SDK] Add docstring for Train API

- .github/workflows/build-and-publish-images.yaml
- .github/workflows/free-up-disk-space/action.yaml
- .github/workflows/integration-tests.yaml
- .github/workflows/template-publish-image/action.yaml
- examples/mpi/tensorflow-mnist.yaml
- examples/pytorch/mnist/v1/pytorch_job_mnist_gloo.yaml
- examples/pytorch/mnist/v1/pytorch_job_mnist_mpi.yaml
- examples/pytorch/mnist/v1/pytorch_job_mnist_nccl.yaml
- sdk/python/test/e2e/test_e2e_mpijob.py
- sdk/python/test/e2e/test_e2e_mxjob.py
- sdk/python/test/e2e/test_e2e_paddlejob.py
- sdk/python/test/e2e/test_e2e_pytorchjob.py
- sdk/python/test/e2e/test_e2e_tfjob.py
- sdk/python/test/e2e/test_e2e_xgboostjob.py
In the current PyTorch (`gcr.io/kubeflow-ci/pytorch-dist-mnist-test:v1.0`) and Horovod (`horovod/horovod:0.20.0-tf2.3.0-torch1.6.0-mxnet1.5.0-py3.7-cpu`) images, it seems that we can not download the model because both images are too older. So, I replaced those images with the `horovod/horovod:0.28.1` and the `kubeflow/pytorch-dist-mnist:latest`.
```shell
root@0f45e95838e4:/var# python mnist.py --backend=gloo
Downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz
Traceback (most recent call last):
File "mnist.py", line 150, in <module>
main()
File "mnist.py", line 123, in main
transforms.Normalize((0.1307,), (0.3081,))
File "/opt/conda/lib/python3.6/site-packages/torchvision-0.2.1-py3.6.egg/torchvision/datasets/mnist.py", line 46, …
```
> E2E: Replace outdated images with latest ones

- pkg/controller.v1/common/pod.go
- pkg/controller.v1/tensorflow/pod_test.go
> Fail job for non-retryable exit codes

- pkg/controller.v1/common/job_controller.go
- pkg/controller.v1/common/scheduling.go
Actually, we never operate PDB in the training-operator, and those functions are never referred from any others.
Fixes #
**Checklist:**
> Remove deadcode related to PodDisruptionBudget

- pkg/controller.v1/tensorflow/pod_test.go
As we discussed here: https://github.com/kubeflow/training-operator/pull/2071#discussion_r1581157170, I investigated the reason why we could not use the `gomega.ContainElements`, and fixed that.
Follow-up of #2071 
**Checklist:**
> Test: Simplify and Identify pod-controller envtest

- examples/pytorch/cpu-demo/demo.py
- examples/pytorch/elastic/echo/echo.py
Python imports are out of order in examples/pytorch. 
**Which issue(s) this PR fixes** _(optional, in `Fixes #<issue number>, #<issue number>, ...` format, will close the issue(s) when PR gets merged)_: NA
> Fix isort on examples/pytorch

- sdk/python/setup.py
I run into this error trying to pip install for pytest `pip install '.[test]':`
```
ERROR: Could not find a version that satisfies the requirement flake==4.0.1; extra == "test" (from kubeflow-training[test]) (from versions: none)
ERROR: No matching distribution found for flake==4.0.1; extra == "test"
```
When changing the line to `"flake8==4.0.1",` I get a successful run:
```
Successfully built kubeflow-training
Installing collected packages: kubeflow-training
Attempting uninstall: kubeflow-training
Found existing installation: kubeflow-training 1.7.0
Uninstalling kubeflow-training-1.7.0:
Successfully uninstalled kubeflow-training-1.7.0
Successfully installed kubeflow-training-1.7.0
```
No changes to the version, or anything else really.
> changed package name to flake8 to fix pytests pip install

- .github/workflows/publish-example-images.yaml
- Support ARM64 platform in XGBoost examples
Fixes #2113
**Checklist:**
> Feat: Support ARM64 platform in XGBoost examples

- sdk/python/kubeflow/training/utils/utils.py
I fixed `add_event_to_dict` function to correctly check key in `events_dict` dictionary.
I introduced this bug in this commit: https://github.com/kubeflow/training-operator/pull/1975/commits/b2d9c365fdcf7ba71988e8bfe803ac7584a85447.
Also, I made the key as follows:
```
<object_kind>/<object_name>
pytorchjob/training-job
```
/assign @kubeflow/wg-training-leads @droctothorpe
> [SDK] Fix Incorrect Events in get_job_logs API

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yaml
I added similar issue template to help us triage issues: https://github.com/kubeflow/katib/pull/2335
> Add GitHub Issue Template

- manifests/base/crds/kubeflow.org_mpijobs.yaml
- manifests/base/crds/kubeflow.org_mxjobs.yaml
- manifests/base/crds/kubeflow.org_paddlejobs.yaml
- manifests/base/crds/kubeflow.org_pytorchjobs.yaml
- manifests/base/crds/kubeflow.org_tfjobs.yaml
- manifests/base/crds/kubeflow.org_xgboostjobs.yaml
- pkg/apis/kubeflow.org/v1/common_types.go
- pkg/controller.v1/common/job.go
- pkg/controller.v1/common/scheduling.go
- pkg/controller.v1/pytorch/pytorchjob_controller_test.go
This is the fix cause by this [PR](https://github.com/kubeflow/common/pull/207), the minMember may be updated when the number of replica is changed. However, this also accidentally change the queue value. It also sync up the queue value in the podGroup with the value in runPolicy.SchedulingPolicy.Queue, which is not always applicable to all use cases. 
In our use cases we'll inject the queue value according to which org this user belongs to. This change will override the value we set in the queue. The queue value should not be updated once the it is set. 
Fixes #
**Checklist:**
> fix volcano podgroup update issue

- pkg/controller.v1/pytorch/pytorchjob_controller_test.go
I refined the integration tests for the PyTorchJob queueName.
By passing the root Gomega instance, the Gomega could clarify the reason for the test failure.
Follow-up #2079
**Checklist:**
> Refine the integration tests for the immutable PyTorchJob queueName

- sdk/python/setup.py
Cherry pick of #2109 on v1.8-branch.
#2109: changed package name to flake8 to fix pip install
For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.
I stole the commit since #2109 was not signed in CLA...
> Automated cherry pick of #2109: changed package name to flake8 to fix pip install

- sdk/python/setup.py
We should keep Transformers version the same with [our Trainer image](https://github.com/kubeflow/training-operator/blob/master/sdk/python/kubeflow/trainer/requirements.txt#L3).
Otherwise, users can see the errors with incompatible arguments for HuggingFace [Trainer](https://github.com/kubeflow/training-operator/blob/bb8bba00ff0b48de922c523b0d3051f8b2d4ee74/sdk/python/kubeflow/trainer/hf_llm_training.py#L120-L125)
/assign @johnugeorge @deepanker13 @tenzen-y
> [SDK] Sync Transformers version for train API

- sdk/python/setup.py
Cherry pick this fix to the release branch: https://github.com/kubeflow/training-operator/pull/2146
/assign @tenzen-y @johnugeorge
> Cherry pick: [SDK] Sync Transformers version for train API (#2146)

- manifests/overlays/kubeflow/kustomization.yaml
- manifests/overlays/standalone/kustomization.yaml
I updated image tag for `v1.8.0-rc.1` release.
> Release Training Operator Image for v1.8.0-rc.1

- sdk/python/kubeflow/training/api/training_client.py
We should check if Failed is not in `expected_conditions` set. We need to add more unit tests for our SDK. I will create issues for it.
/assign @kubeflow/wg-training-leads @droctothorpe
> [SDK] Fix Failed condition in wait Job API

- sdk/python/kubeflow/training/api/training_client.py
Cherry pick this PR to the 1.8 release branch: https://github.com/kubeflow/training-operator/pull/2160
> Cherry pick: [SDK] Fix Failed condition in wait Job API (#2160)

- docs/proposals/jax-integration.md
Enhancement Proposal for integrating JAX with Kubeflow Training Operator for distributed training on Kubernetes
Ref: 
- #1619
- https://www.kubeflow.org/events/gsoc-2024/#project-5-support-distributed-jax-for-training-operator
/area gsoc
> JAX Integration Enhancement Proposal

- docs/proposals/jax-integration.md
A separate Coordinator replica for JAX is not  needed, since Pod template will be the same and Worker with `process_id` 0 will act as the Coordinator.
- https://jax.readthedocs.io/en/latest/multi_process.html
- https://jax.readthedocs.io/en/latest/_autosummary/jax.distributed.initialize.html#jax-distributed-initialize
> Update JAX integration proposal

- .github/workflows/trigger-rerun-test.yaml
Followup on Katib: https://github.com/kubeflow/katib/pull/2385 and KFP: https://github.com/kubeflow/pipelines/pull/10930 PRs.
I added ability to re-run failed GitHub Actions without manually re-trigger them.
That allows contributors without GitHub write access to trigger the failed actions.
The following commands are supported by this action:
`/rerun-all` - rerun all failed workflows.
`/rerun-workflow <workflow name>` - rerun a specific failed workflow. Only one workflow name can be specified.
Reference: https://github.com/estroz/rerun-actions
/assign @kubeflow/wg-training-leads @rimolive
> Add command to re-run GitHub Actions tests

- manifests/overlays/kubeflow/kustomization.yaml
- manifests/overlays/standalone/kustomization.yaml
I updated image tag for `v1.8.0` release.
> Release Training Operator Image for v1.8.0

- sdk/python/setup.py
Updating Training Python SDK to the 1.8 version.
> Bump Training Python SDK to 1.8.0 version

- CHANGELOG.md
I added changelog for Training Operator v1.8.0
Thanks everyone for your contribution to Training Operator 🎉
I will create GitHub release after.
/hold for review
/assign @kubeflow/wg-training-leads @deepanker13 @tariq-hasan @afritzler @champon1020 @shruti2522 @kellyaa @qzoscar @champon1020 @PeterWrighten @garymm @lowang-bh @double12gzh @rpemsel @franciscojavierarceo @jdcfd @shashank-iitbhu @daniel-hutao @kuizhiqing @testwill @Syulin7 @rpemsel @kubeflow/release-team
> Add Changelog for Training Operator v1.8.0

- sdk/python/kubeflow/training/api/training_client_test.py
- sdk/python/kubeflow/training/constants/constants.py
- sdk/python/kubeflow/training/utils/utils.py
New unit test for get_job_pods function
Fixes #2161
**Checklist:**
> [SDK] Add more unit tests for TrainingClient APIs - get_job_pods

- sdk/python/kubeflow/training/api/training_client.py
- sdk/python/kubeflow/training/constants/constants.py
According to [the discussion](https://github.com/kubeflow/katib/pull/2393#discussion_r1691781750), this PR updates the name of PVC in `train` API to have pvc_name == job_name. In this case, each job will have a separate PVC.
Fixes #
**Checklist:**
> Update the name of PVC in `train` API

- docs/proposals/2170-kubeflow-training-v2/README.md
I updated the below API definitions for the Training v2 API:
1. `trainingRuntimeRef`
1. I removed the `namespace` field since we should use the TrainingRuntime deployed in the same namespace with the TrainJob. Otherwise, users should define the ClusterTrainingRuntime instead of the namespace-scoped TrainingRuntime resource.
2. I renamed the `version` field with `apiVersion` since we are sometimes confused if the version indicates the runtime revision or API version.
2. `managedBy`
1. I added limitations and restrictions based on discussions in https://github.com/kubeflow/training-operator/issues/2193. The `managedBy` field is acceptable only for either an empty value, "training-operator.kubeflow.org/trainjob-controller" or …
> KEP-2170: Make API specification more restricting

- docs/proposals/2170-kubeflow-training-v2/README.md
Based on [this discussion](https://github.com/kubeflow/training-operator/pull/2198#discussion_r1707795122), I added the `apiGroup` field to the `.spec.trainingRuntimeRef` in the TrainJob.
Part-of #2170
**Checklist:**
> KEP-2170: Add the apiGroup to the TrainingRuntimeRef

- sdk/python/kubeflow/trainer/hf_llm_training.py
Add data preprocessing for `train_args` and `lora_config` to ensure each parameter's type is consistent with the reference value. This will be necessary for developing the Katib `tune` API to optimize hyperparameters.
Fixes #
**Checklist:**
> Update trainer to ensure type consistency for `train_args` and `lora_config`

- .pre-commit-config.yaml
- examples/pytorch/elastic/echo/echo.py
- examples/pytorch/elastic/imagenet/imagenet.py
- sdk/python/kubeflow/storage_initializer/s3.py
- sdk/python/kubeflow/training/api/training_client.py
- sdk/python/kubeflow/training/api/training_client_test.py
- sdk/python/kubeflow/training/constants/constants.py
This PR implements the flake8 linter as a pre-commit hook to ensure code quality and adherence to style guidelines. It also addresses and fixes the issues identified by flake8.
Fixes #1910 
**Checklist:**
> Enhance pre-commit hooks with flake8 linting

- .github/workflows/build-and-publish-images.yaml
- .github/workflows/publish-core-images.yaml
- .github/workflows/template-publish-image/action.yaml
- cmd/training-operator.v2alpha1/Dockerfile
- cmd/training-operator.v2alpha1/main.go
- pkg/apis/kubeflow.org/v2alpha1/trainingruntime_types.go
- pkg/apis/kubeflow.org/v2alpha1/trainjob_types.go
- pkg/controller.v2/trainjob_controller.go
- pkg/webhook.v2/trainjob_webhook.go
Related: https://github.com/kubeflow/training-operator/issues/2206
I added directory structure for the V2 APIs.
/assign @tenzen-y @kubeflow/wg-training-leads
> KEP-2170: Add directories for the V2 APIs

- cmd/training-operator.v2alpha1/Dockerfile
I replaced the approach of copying repository files in the container image build env.
We can avoid the copy of files by using `--mont=bind` option.
Additionally, I resolved https://docs.docker.com/reference/build-checks/from-as-casing/ warning.
Part-of #2206
Follow-up-of: #2221
**Checklist:**
> KEP-2170: Bind repository into the build environment instead of filecopy

- .github/workflows/test-go.yaml
- hack/swagger/go.mod
- hack/swagger/go.sum
`hack/swagger/go.mod` is outdated. So, I performed `go mod tidy`.
Additionally, I added a CI command so that we can detect the outdated Go modules in CI.
Fixes #
**Checklist:**
> Clean up Go modules

- sdk/python/kubeflow/storage_initializer/hugging_face.py
- sdk/python/kubeflow/trainer/Dockerfile
- sdk/python/kubeflow/trainer/hf_llm_training.py
- sdk/python/kubeflow/training/api/training_client.py
This PR fixes the error encountered when training using the `train` API in a CPU environment by updating the trainer's base image version and adding the "num_labels" attribute to `HuggingFaceModelParams` for downloading pretrained models.
Fixes #2228
**Checklist:**
> [SDK] Fix trainer error: Update the version of base image and add "num_labels" for downloading pretrained models

- sdk/python/kubeflow/training/api/training_client_test.py
I add some UTs for function `wait_for_job_conditions` in the Python SDK
Ref #2161 
**Checklist:**
> [SDK] Add UTs for `wait_for_job_conditions`

- pkg/controller.v1/common/job.go
- pkg/controller.v1/tensorflow/job_test.go
To fix the bug related to the situation when the job was both suspended` and `runPolicy.ttlSecondsAfterFinished` was set.
In such situation CleanupJob was returning an error and activate status of the replicas couldn't be removed.
Fixes #2239
**Checklist:**
> [Bug] Finish CleanupJob early if the job is suspended.

- sdk/python/kubeflow/training/api/training_client_test.py
add unit tests for delete_job() method
Ref: #2161
To verify run:
```
pytest -v sdk/python/kubeflow/training/api/training_client_test.py -k test_delete_job
```
**Checklist:**
> [SDK] test: add unit tests for delete_job() method

- sdk/python/kubeflow/training/api/training_client_test.py
add unit test for get_job method of the training_client
To verify run:
```
pytest -v sdk/python/kubeflow/training/api/training_client_test.py -k test_get_job
```
Ref: #2161
**Checklist:**
> [SDK] test: add unit test for get_job method of the training_client

- .github/workflows/unittests.yaml
- Makefile
- cmd/training-operator.v2alpha1/main.go
- pkg/controller.v2/setup.go
- pkg/controller.v2/trainjob_controller.go
- pkg/webhook.v2/webhook.go
- test/integration/controller.v2/suite_test.go
- test/integration/controller.v2/trainjob_controller_test.go
- test/integration/framework/framework.go
I implemented the skeleton v2 manager. So, this PR introduces only the following things:
- Main manager setupper.
- The skeleton controllers for TrainJob, TrainingRuntime, and ClusterTrainingRuntime.
- The minimum integration tests using envtest so that we can be confident that this manager can be launched successfully.
These skeleton implementations allow us to unblock webhooks or other implementations for other contributors.
This depends on #2237, and #2237 blocks this PR.
Part-of #2207
**Checklist:**
> KEP-2170: Initial Implementations for v2 Manager

- Makefile
- manifests/v2/base/webhook/kustomization.yaml
- manifests/v2/base/webhook/manifests.yaml
- pkg/webhook.v2/clustertrainingruntime_webhook.go
- pkg/webhook.v2/setup.go
- pkg/webhook.v2/trainingruntime_webhook.go
- test/integration/framework/framework.go
- test/integration/webhook.v2/clustertrainingruntime_test.go
- test/integration/webhook.v2/suite_test.go
- test/integration/webhook.v2/trainingruntime_test.go
- test/integration/webhook.v2/trainjob_test.go
I implemented the skeleton webhook servers for v2 operator.
Part-of #2209 
**Checklist:**
> KEP-2170: Implement skeleton webhook servers

- sdk/python/kubeflow/training/utils/utils.py
This will allow the SDK to read namespace from the current context instead of using the `default` namespace.
/assign @kubeflow/wg-training-leads @droctothorpe
> [SDK] Read namespace from the current context

- sdk/python/setup.py
Updating Training Python SDK to the 1.8.1 version.
> Bump Training Python SDK to 1.8.1 version

- sdk/python/kubeflow/training/api/training_client.py
- sdk/python/kubeflow/training/constants/constants.py
Allow customising base storage_initializer and trainer images through Env vars.
Example use case: Train API could be expanded to use ROCm libs in addition to CUDA. 
Fixes #2247 
TODO: Docs to be updated in https://github.com/kubeflow/website.
**Checklist:**
> [SDK] Allow customising base trainer and storage images in Train API

- .github/workflows/publish-example-images.yaml
- PROJECT
- cmd/training-operator.v1/main.go
- examples/jax/cpu-demo/Dockerfile
- examples/jax/cpu-demo/demo.yaml
- examples/jax/cpu-demo/train.py
- manifests/base/crds/kustomization.yaml
- manifests/base/rbac/role.yaml
- manifests/base/webhook/manifests.yaml
- manifests/base/webhook/patch.yaml
- pkg/controller.v1/jax/envvar.go
- pkg/controller.v1/jax/envvar_test.go
- pkg/controller.v1/jax/jaxjob_controller.go
- pkg/controller.v1/jax/jaxjob_controller_suite_test.go
- pkg/controller.v1/jax/jaxjob_controller_test.go
- pkg/controller.v1/register_controller.go
- pkg/webhooks/jax/jaxjob_webhook.go
- pkg/webhooks/jax/jaxjob_webhook_test.go
- pkg/webhooks/webhooks.go
- sdk/python/kubeflow/training/api/training_client.py
- sdk/python/kubeflow/training/constants/constants.py
- sdk/python/test/e2e/test_e2e_jaxjob.py
Implement JAX controller
Ref: https://github.com/kubeflow/training-operator/issues/1619 https://github.com/kubeflow/training-operator/issues/2145
- https://jax.readthedocs.io/en/latest/multi_process.html
- https://jax.readthedocs.io/en/latest/_autosummary/jax.distributed.initialize.html#jax.distributed.initialize
/area gsoc
> Add JAX controller

- README.md
- examples/jax/cpu-demo/demo.yaml
- pkg/controller.v1/jax/envvar_test.go
- pkg/webhooks/jax/jaxjob_webhook_test.go
- sdk/python/kubeflow/training/constants/constants.py
- sdk/python/test/e2e/test_e2e_jaxjob.py
Follow up of #2194 
/area gsoc
> Update JAX image to use image published by Kubeflow 

- sdk/python/kubeflow/training/api/training_client.py
This PR fixes a minor bug in the wait_for_job_conditions function of the python training SDK
Fixes #
**Checklist:**
**Bug**
- Encountered this bug when testing the [create-tfjob.ipynb](https://github.com/kubeflow/training-operator/blob/da11d1116c29322c481d0b8f174df8d6f05004aa/examples/tensorflow/image-classification/create-tfjob.ipynb#L315) notebook example
- When `job_kind` (which is not PyTorch job kind) is passed in `wait_for_job_conditions` the SDK throws a ValueError.
Example code:
`TrainingClient(namespace=namespace).wait_for_job_conditions(name, job_kind=constants.TFJOB_KIND)`
Error:
``` …
```
> [SDK] Minor fix in wait_for_job_conditions with job_kind python training API

- sdk/python/kubeflow/training/api/training_client_test.py
The following unit tests are added with this PR. 
* get_job_conditions
* is_job_created
* is_job_running
* is_job_restarting
* is_job_failed
* is_job_succeeded
You can verify each unit test with the following command substituting `<test_name>` for one of the tests above.
```
pytest -v sdk/python/kubeflow/training/api/training_client_test.py -k <test_name>
```
Related to #2161
**Checklist:**
> [SDK] Training Client Conditions related unit tests

- examples/pytorch/image-classification/Train-CNN-with-FashionMNIST.ipynb
- sdk/python/kubeflow/training/api/training_client.py
- sdk/python/kubeflow/training/api/training_client_test.py
- sdk/python/kubeflow/training/constants/constants.py
- sdk/python/kubeflow/training/utils/utils.py
Fixes: https://github.com/kubeflow/training-operator/issues/1991
I updated the SDK to use `torchrun` when distributed PyTorchJob is created from function.
Also, I updated the unit tests and example.
/assign @kubeflow/wg-training-leads @Electronic-Waste @helenxie-bit @YosiElias @droctothorpe @Bobbins228 @akshay @deepanker13 @akshaychitneni @shravan-achar @kuizhiqing
> [SDK] Use torchrun to create PyTorchJob from function

- .github/workflows/publish-example-images.yaml
- examples/pytorch/deepspeed-demo/Dockerfile
- examples/pytorch/deepspeed-demo/README.md
- examples/pytorch/deepspeed-demo/pytorch_deepspeed_demo.yaml
- examples/pytorch/deepspeed-demo/requirements.txt
- examples/pytorch/deepspeed-demo/train_bert_ds.py
Add DeepSpeed Example with Pytorch Operator. The script used is HelloDeepSpeed from [DeepSpeedExamples](https://github.com/microsoft/DeepSpeedExamples/blob/master/training/HelloDeepSpeed/README.md).
Part-of https://github.com/kubeflow/training-operator/issues/2091
**Checklist:**
> Add DeepSpeed Example with Pytorch Operator

- manifests/v2/base/crds/kubeflow.org_trainjobs.yaml
- pkg/apis/kubeflow.org/v2alpha1/openapi_generated.go
- pkg/apis/kubeflow.org/v2alpha1/trainjob_types.go
- test/integration/controller.v2/trainjob_controller_test.go
This PR relates to https://github.com/kubeflow/training-operator/issues/2209 adding CEL validations on TrainJob CRD. I will followup with validations implemented in webhook in separate PR
cc @andreyvelich @tenzen-y
> KEP-2170: Adding CEL validations on v2 TrainJob CRD

- .github/workflows/publish-core-images.yaml
- Makefile
- cmd/training-operator.v1/main.go
- cmd/training-operator.v2alpha1/main.go
- manifests/v2/base/kustomization.yaml
- manifests/v2/base/manager/kustomization.yaml
- manifests/v2/base/manager/manager.yaml
- manifests/v2/base/rbac/kustomization.yaml
- manifests/v2/base/rbac/role.yaml
- manifests/v2/base/rbac/role_binding.yaml
- manifests/v2/base/rbac/service_account.yaml
- manifests/v2/base/webhook/kustomization.yaml
- manifests/v2/base/webhook/kustomizeconfig.yaml
- manifests/v2/base/webhook/patch.yaml
- manifests/v2/overlays/standalone/kustomization.yaml
- manifests/v2/overlays/standalone/namespace.yaml
- pkg/cert/cert.go
- pkg/controller.v2/trainjob_controller.go
- pkg/runtime.v2/core/core.go
- pkg/runtime.v2/framework/plugins/coscheduling/coscheduling.go
- pkg/runtime.v2/framework/plugins/jobset/jobset.go
- test/integration/framework/framework.go
Fixes: https://github.com/kubeflow/training-operator/issues/2208
I added manifests for Training Operator V2. I renamed the manager image to:
```
docker.io/kubeflow/training-operator-v2
```
That will allow users to use `latest` version for both V1 and V2 version of Training Operator.
In the future, we can deprecate the old version of Training Operator.
For now, I install JobSet using the release manifests in the Kustomize overlay. Let's discuss with @kubeflow/wg-manifests-leads what is the better approach long-term.
Additionally, I fixed the invalid validating webhook configuration name in our cert generator.
/assign @kubeflow/wg-training-leads 
/hold for review
> KEP-2170: Add manifests for Kubeflow Training V2

- .gitignore
- Makefile
- pkg/controller.v2/trainjob_controller.go
- pkg/runtime.v2/core/clustertrainingruntime_test.go
- pkg/runtime.v2/core/trainingruntime_test.go
- pkg/runtime.v2/framework/core/framework_test.go
- pkg/runtime.v2/framework/plugins/jobset/builder.go
- pkg/runtime.v2/framework/plugins/jobset/jobset.go
- pkg/util.v2/testing/wrapper.go
- test/integration/controller.v2/trainjob_controller_test.go
- test/integration/framework/framework.go
- test/util/constants.go
I implemented the object creation and update in the TrainJob reconciler.
I will implement the TrainJob status operation in a follow-up PR.
Additionally, I restricted the directories in `make test` so that we can perform tests only for the v1 APIs and controllers.
Part-of #2207 
Relates to #2170
**Checklist:**
> KEP-2170: Implement TrainJob Reconciler to manage objects

- docs/proposals/2170-kubeflow-training-v2/README.md
- manifests/v2/base/crds/kubeflow.org_trainjobs.yaml
- pkg/apis/kubeflow.org/v2alpha1/openapi_generated.go
- pkg/apis/kubeflow.org/v2alpha1/trainjob_types.go
- pkg/util.v2/testing/errormatcher.go
- pkg/util.v2/testing/wrapper.go
- test/integration/controller.v2/trainjob_controller_test.go
I refactored the CRD marker integration testing so that we could more strictly verify the expected behavior.
Additionally, I made the `.spec.runtimeRef` field as immutable field to reduce unexpected errors when actual Jobs are built.
Fixes #2293
Relates to #2170
**Checklist:**
> KEP-2170: Strictly verify the CRD marker validation and defaulting in the integration testings

- cmd/training-operator.v2alpha1/main.go
I fixed the bug that the runtime initialization is performed after the manager starts.
```shell
NAME                                    READY   STATUS             RESTARTS      AGE
training-operator-v2-6446df9d8f-dtcmz   0/1     CrashLoopBackOff   6 (19s ago)   6m31s
```
```shell
{"level":"error","ts":"2024-10-24T19:43:24.046731262Z","logger":"setup","caller":"training-operator.v2alpha1/main.go:159","msg":"Could not initialize runtimes","error":"initializing runtime \"TrainingRuntime.kubeflow.org\": setting index on TrainingRuntime for TrainJob: informer has already started","stacktrace":"main.setupControllers\n\t/workspace/cmd/training-operator.v2alpha1/main.go:159"}
```
The manager starting indicates that informers (including indexers) cache …
> KEP-2170: Initialize runtimes before the manager starts

- pkg/apis/kubeflow.org/v2alpha1/trainingruntime_types.go
- pkg/apis/kubeflow.org/v2alpha1/trainjob_types.go
- pkg/constants/constants.go
- pkg/runtime.v2/core/clustertrainingruntime_test.go
- pkg/runtime.v2/core/trainingruntime.go
- pkg/runtime.v2/core/trainingruntime_test.go
- pkg/runtime.v2/framework/core/framework.go
- pkg/runtime.v2/framework/core/framework_test.go
- pkg/runtime.v2/framework/interface.go
- pkg/runtime.v2/framework/plugins/coscheduling/coscheduling.go
- pkg/runtime.v2/framework/plugins/jobset/builder.go
- pkg/runtime.v2/framework/plugins/jobset/jobset.go
- pkg/runtime.v2/framework/plugins/mpi/mpi.go
- pkg/runtime.v2/framework/plugins/plainml/plainml.go
- pkg/runtime.v2/framework/plugins/torch/torch.go
- pkg/runtime.v2/runtime.go
- pkg/runtime.v2/runtime_test.go
- pkg/util.v2/testing/wrapper.go
- test/integration/controller.v2/trainjob_controller_test.go
- test/integration/webhook.v2/clustertrainingruntime_test.go
- test/integration/webhook.v2/trainingruntime_test.go
Part of: https://github.com/kubeflow/training-operator/issues/2290.
I implemented JobSet and PlainML plugins, and I was able to submit our first TrainJob and ClusterTrainingRuntime 🎉 
<details><summary>Working ClusterTrainingRuntime</summary>
apiVersion: kubeflow.org/v2alpha1
kind: ClusterTrainingRuntime
metadata:
name: first-runtime
spec:
mlPolicy:
numNodes: 5
template:
spec:
replicatedJobs:
- name: trainer-node
template:
spec:
template:
spec:
containers:
- name: trainer
image: python:alpine3.20
command:
- "/bin/sh"
- -c
- "echo 'Hello From Training Runtime'"
---
apiVersion: kubeflow.org/v2alpha1
kind: TrainJob
metadata:
name: first-job
spec:
runtimeRef:
name: first-runtime
kind: ClusterTrainingRuntime
apiGroup: kubeflow.org
trainer:
numNodes: 2
</details>
A few details:
- We discussed …
> KEP-2170: Implement JobSet, PlainML, and Torch Plugins

- .github/workflows/test-go.yaml
- Makefile
- api.v2/openapi-spec/swagger.json
- docs/proposals/2170-kubeflow-training-v2/README.md
- manifests/v2/base/crds/kubeflow.org_trainjobs.yaml
- pkg/apis/kubeflow.org/v2alpha1/openapi_generated.go
- pkg/apis/kubeflow.org/v2alpha1/trainjob_types.go
- pkg/apis/kubeflow.org/v2alpha1/zz_generated.deepcopy.go
- pkg/constants/constants.go
- pkg/controller.v1/pytorch/elastic.go
- pkg/controller.v1/pytorch/master.go
- pkg/runtime.v2/core/clustertrainingruntime_test.go
- pkg/runtime.v2/core/trainingruntime_test.go
- pkg/runtime.v2/framework/core/framework_test.go
- pkg/runtime.v2/framework/plugins/jobset/builder.go
- pkg/runtime.v2/framework/plugins/jobset/constants.go
- pkg/runtime.v2/framework/plugins/jobset/jobset.go
- pkg/util.v2/testing/wrapper.go
- sdk_v2/docs/KubeflowOrgV2alpha1DatasetConfig.md
- sdk_v2/docs/KubeflowOrgV2alpha1InputModel.md
- sdk_v2/docs/KubeflowOrgV2alpha1OutputModel.md
- sdk_v2/kubeflow/training/models/kubeflow_org_v2alpha1_dataset_config.py
- sdk_v2/kubeflow/training/models/kubeflow_org_v2alpha1_input_model.py
- sdk_v2/kubeflow/training/models/kubeflow_org_v2alpha1_output_model.py
- test/integration/controller.v2/trainjob_controller_test.go
Part of: https://github.com/kubeflow/training-operator/issues/2290, https://github.com/kubeflow/training-operator/issues/2170.
I implemented builder for dataset and model initializers.
/assign @kubeflow/wg-training-leads @varshaprasad96 @akshaychitneni @deepanker13 @helenxie-bit @Electronic-Waste @saileshd1402 @kannon92 @kuizhiqing @shravan-achar
> KEP-2170: Implement Initializer builders in the JobSet plugin 

- docs/proposals/2170-kubeflow-training-v2/README.md
I added the TrainJob state machine design.
Part-of #2207
Relates to: #2170 
**Checklist:**
> KEP-2170: Add the TrainJob state transition design

- api.v2/openapi-spec/swagger.json
- hack/violation_exception_v2alpha1.list
- manifests/v2/base/crds/kubeflow.org_trainjobs.yaml
- pkg/apis/kubeflow.org/v2alpha1/openapi_generated.go
- pkg/apis/kubeflow.org/v2alpha1/trainjob_types.go
- pkg/constants/constants.go
- pkg/controller.v2/trainjob_controller.go
- pkg/runtime.v2/core/clustertrainingruntime.go
- pkg/runtime.v2/core/trainingruntime.go
- pkg/runtime.v2/framework/core/framework.go
- pkg/runtime.v2/framework/core/framework_test.go
- pkg/runtime.v2/framework/interface.go
- pkg/runtime.v2/framework/plugins/coscheduling/coscheduling.go
- pkg/runtime.v2/framework/plugins/jobset/jobset.go
- pkg/runtime.v2/interface.go
- pkg/util.v2/testing/wrapper.go
- test/integration/controller.v2/trainjob_controller_test.go
- test/integration/framework/framework.go
- test/util/constants.go
I implemented the TrainJob condition mechanism based on https://github.com/kubeflow/training-operator/tree/master/docs/proposals/2170-kubeflow-training-v2#state-transition
However, the current implementation depends on the JobSet status.conditions as opposed to the status.terminalState since the terminalState was introduced in JobSet v0.6, then the JobSet depends on the K8s lib. After we upgrade the training-operator dep version to 1.30 in https://github.com/kubeflow/training-operator/pull/2299, we can rely on the termonalState.
So, after we upgrade the K8s libs to 1.30, we can revisit the JobSet status.terminalState.
**Which issue(s) this PR fixes** _(optional, in `Fixes #<issue number>, #<issue number>, ...` format, will close the issue(s) when PR …
> KEP-2170: Add TrainJob conditions

- examples/jax/cpu-demo/Dockerfile
Pin the Gloo repository to a specific commit in the JAX Dockerfile to prevent build failures caused by a recent bug introduced in the Gloo codebase. By locking the version of Gloo to a known working commit, we ensure that the JAX build remains stable and functional until the issue is resolved upstream.
The build failure occurs when compiling the `gloo/transport/tcp/buffer.cc` file due to an undefined `__NR_gettid` constant, which was introduced after the pinned commit.
**Related Issue/Context:**
- Gloo GitHub Commit: https://github.com/facebookincubator/gloo/commit/43b7acbf372cdce14075f3526e39153b7e433b53
- JAX Example Image build failure: https://github.com/kubeflow/training-operator/actions/runs/11864108924/job/33066900230?pr=2328
Thanks to @andreyvelich for reporting the issue.
> Pin Gloo repository in JAX Dockerfile to a specific commit

- .github/workflows/template-publish-image/action.yaml
We often manually restart CI jobs due to cache exporting errors like
```
#14 [7/8] RUN mkdir -p /root/deepspeed_data
#14 DONE 0.1s
#15 exporting to GitHub Actions Cache
#15 preparing build cache for export
#15 preparing build cache for export 607.8s done
#15 ERROR: maximum timeout reached
------
> exporting to GitHub Actions Cache:
------
WARNING: No output specified with docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load
ERROR: failed to solve: maximum timeout reached
Error: buildx failed with: ERROR: failed to solve: maximum timeout reached
```
https://github.com/kubeflow/training-operator/actions/runs/11731087630/job/32680387684#step:6:136 …
> Ignore cache exporting errors in the image building workflows

- manifests/v2/base/kustomization.yaml
- manifests/v2/base/manager/kustomization.yaml
- manifests/v2/base/rbac/kustomization.yaml
- manifests/v2/base/runtimes/pre-training/kustomization.yaml
- manifests/v2/base/runtimes/pre-training/torch-distributed.yaml
- manifests/v2/base/webhook/kustomization.yaml
- manifests/v2/overlays/only-manager/kustomization.yaml
- manifests/v2/overlays/only-manager/namespace.yaml
- manifests/v2/overlays/only-runtimes/kustomization.yaml
Fixes: https://github.com/kubeflow/training-operator/issues/2211
I added Torch distributed runtime and more overlays (only-runtimes, only-manager) as we discussed with @tenzen-y and @deepanker13 offline.
Since it might be useful for GitOps to install everything, only manager, or only runtimes.
/assign  @kubeflow/wg-training-leads @varshaprasad96 @akshaychitneni @helenxie-bit @Electronic-Waste @saileshd1402 @seanlaii
> KEP-2170: Add Torch Distributed Runtime

- Makefile
- README.md
- scripts/gha/setup-training-operator.sh
- scripts/setup-training-operator.sh
The `=true` is not needed.
Fixes #
**Checklist:**
> Refine the server-side apply installation args

- pkg/webhooks/pytorch/pytorchjob_webhook.go
- pkg/webhooks/pytorch/pytorchjob_webhook_test.go
This PR adds a check in the Pytorchjob validating webhook to ensure that if a user configures an elastic policy that they have defined a worker spec. Previously defining an elastic policy with no worker spec was resulting in a nil pointer exception on [this line](https://github.com/kubeflow/training-operator/blob/master/pkg/apis/kubeflow.org/v1/pytorch_defaults.go#L49). Additionally, we added validation to ensure that the worker spec defines at least one replica.
Fixes #2278
**Checklist:**
> Validate pytorchjob workers are configured when elasticpolicy is configured

- manifests/v2/base/rbac/role.yaml
- pkg/controller.v2/trainjob_controller.go
This PR adds RBAC on TrainJob finalizer sub-resources, that's required for clusters with https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#ownerreferencespermissionenforcement.
Fixes #2349
**Checklist:**
> Add required RBAC on TrainJob finalizer sub-resources

- Makefile
This PR runs `go mod download` prior to running code generation to ensure the required dependencies are present.
Before:
```
$ sudo rm -rf `go list -m -mod=readonly -f "{{.Dir}}" k8s.io/code-generator`
$ make generate
GOBIN=/workdir/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.16.5
/workdir/bin/controller-gen "crd:generateEmbeddedObjectMeta=true,maxDescLen=400" rbac:roleName=training-operator webhook paths="./pkg/apis/kubeflow.org/v1/..." \
output:crd:artifacts:config=manifests/base/crds \
output:rbac:artifacts:config=manifests/base/rbac \
output:webhook:artifacts:config=manifests/base/webhook
/workdir/bin/controller-gen "crd:generateEmbeddedObjectMeta=true" rbac:roleName=training-operator-v2 webhook \ …
```
> Ensure code generation dependencies are downloaded

- pkg/controller.v2/trainjob_controller.go
This PR fixes the comparison that compares the TrainJob status state and fixes some flakes in the tests.
Fixes #2354.
**Checklist:**
> Fix TrainJob status comparison and update

- .github/workflows/setup-e2e-test/action.yaml
This follows #2332 that required using an unreleased version of helm/kind-action to get #127.
This PR upgrades helm/kind-action to the latest version that has just been released:
https://github.com/helm/kind-action/releases/tag/v1.11.0.
**Checklist:**
> Upgrade helm/kind-action to v1.11.0

- CONTRIBUTING.md
buildx comes by default with docker v23 and newer
BuildKit is the default Docker build engine, so both `docker build` and `docker buildx build` use BuildKit to build images. `docker build` is now an alias for the `docker buildx build` command.
BuildKit is the default builder for users on Docker Desktop and Docker Engine v23.0 and later.
https://docs.docker.com/build/buildkit/
**Checklist:**
> buildx link was broken

- .github/workflows/e2e-test-train-api.yaml
- sdk/python/kubeflow/storage_initializer/requirements.txt
- sdk/python/kubeflow/trainer/Dockerfile.cpu
- sdk/python/kubeflow/trainer/requirements.txt
Fixes: https://github.com/kubeflow/training-operator/issues/2367.
This should fix our dataset initializer for `train` API in V1.
The issue was due to incompatible version between `datasets` and `huggingface_hub`.
I removed `huggingface_hub` from the requirements file since `datasets` installs this package.
/assign @kubeflow/wg-training-leads @helenxie-bit @Electronic-Waste @deepanker13 @saileshd1402 @thuytrang32
> V1: Fix versions in HuggingFace dataset initializer

- .github/workflows/build-and-publish-images.yaml
Since we decided to use `release-` branch, we need to update the image push trigger in our CI.
> Add release branch to the image push trigger

- manifests/overlays/kubeflow/kustomization.yaml
- manifests/overlays/standalone/kustomization.yaml
Part of: https://github.com/kubeflow/training-operator/issues/2169
I updated image tag for `v1.9.0-rc.0` release.
> Release Training Operator Image for v1.9.0-rc.0

- CHANGELOG.md
Part of: https://github.com/kubeflow/training-operator/issues/2169.
I added changelog for the `v1.9.0-rc.0` release.
Thanks everyone for your contribution to Training Operator 🎉 
I grouped PR by:
- Breaking Changes
- New Features
- Kubeflow Training V2
- SDK Updates
- APIs and ML Frameworks Updates
- Bug Fixes
- Misc
Let me know what changes we should make.
/cc @kubeflow/wg-training-leads @astefanutti @helenxie-bit @tariq-hasan @akshaychitneni @varshaprasad96 @tarekabouzeid @tarat44 @Syulin7 @sandipanpanda @mszadkow @akhilsaivenkata @tico88612 @danielsuh05 @kannon92 @gavrissh @saileshd1402 @ckyuto @Veer0x1 @astefanutti @oksanabaza @YosiElias @sophie0730 @seanlaii @Bobbins228 @Electronic-Waste @droctothorpe @lowang-bh @mimowo @hkiiita @ChristopheBrown @harshithbelagur @marcmaliar …
> Add Changelog for Training Operator v1.9.0-rc.0

- cmd/initializer_v2/dataset/requirements.txt
This upgrades `huggingface_hub` in the dataset initializer container image to v0.27.1 and includes https://github.com/huggingface/huggingface_hub/pull/2333 that fixes #2378.
Fixes #2378
**Checklist:**
> Upgrade huggingface_hub to v0.27.x in dataset initializer v2

- .github/workflows/integration-tests.yaml
- .github/workflows/test-python.yaml
- cmd/initializer_v2/model/requirements.txt
- pkg/initializer_v2/conftest.py
- pkg/initializer_v2/dataset/__main__.py
- pkg/initializer_v2/dataset/huggingface_test.py
- pkg/initializer_v2/dataset/main_test.py
- pkg/initializer_v2/model/__main__.py
- pkg/initializer_v2/model/huggingface_test.py
- pkg/initializer_v2/model/main_test.py
- pkg/initializer_v2/utils/utils_test.py
- test/integration/initializer_v2/__init__.py
- test/integration/initializer_v2/conftest.py
- test/integration/initializer_v2/dataset_test.py
- test/integration/initializer_v2/model_test.py
- test/integration/initializer_v2/utils.py
I added unit tests and integration tests for model and dataset initializers.
Fixes #2305
**Checklist:**
> KEP-2170: Add unit and Integration tests for model and dataset initializers

- manifests/v2/third-party/jobset/kustomization.yaml
A follow up of #2388 to fix the following warning when installing the v2 operator:
```
Fixed fields:
patchesJson6902 -> patches
patchesStrategicMerge -> patches
commonLabels -> labels
```
**Checklist:**
> Fix Kustomize patchesStrategicMerge deprecation warning

- examples/pytorch/image-classification/mnist.ipynb
This PR adds an example that demonstrates how to train MNIST with PyTorch DDP using the training operator and SDK v2.
**Checklist:**
> KEP-2170: Add PyTorch DDP MNIST training example

- test/integration/controller.v2/trainjob_controller_test.go
I fixed the below flake testing case: https://github.com/kubeflow/training-operator/actions/runs/13138882885/job/36660860125
Fixes #
**Checklist:**
> ControlPlane: Fix flaky integraion testings due to missing the latest version of object

- manifests/base/runtimes/pretraining/torch_distributed.yaml
We should use `trainer.kubeflow.org/v1alpha1` as API Group for Torch Distributed Runtime.
/assign @kubeflow/wg-training-leads @astefanutti @Electronic-Waste
> Fix API Group for Torch Runtime

- OWNERS
I would like to nominate @Electronic-Waste as a reviewer for Kubeflow Trainer project.
Shao, has done a lot of great contributions to the Kubeflow Trainer V2 project including:
- 163 contributions [in the last year.](https://kubeflow.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1&var-period_name=Last%20year&var-metric=contributions&var-repogroup_name=kubeflow%2Ftraining-operator&var-country_name=All&var-companies=All)
- Helping us with Kubeflow Trainer implementation: https://github.com/kubeflow/training-operator/issues/2170
- Driving the LLM Trainer work: https://github.com/kubeflow/training-operator/pull/2410
Thanks again for all of you great contributions, Shao, and I am looking forward to continue working with you 🎉 
/hold for WG leads review
/assign …
> Nominate @Electronic-Waste as a reviewer

- README.md
Updating the link to the migration webpage in the README file.
The link to the migration content  in the README file is not working.
> update migration url on readme file

- manifests/base/crds/trainer.kubeflow.org_clustertrainingruntimes.yaml
- manifests/base/crds/trainer.kubeflow.org_trainingruntimes.yaml
- pkg/apis/trainer/v1alpha1/trainingruntime_types.go
- pkg/runtime/framework/plugins/plainml/plainml_test.go
- pkg/util/testing/wrapper.go
- test/integration/webhooks/trainingruntime_webhook_test.go
I added the missing `sshAuthMountPath` defaulter and related integration tests.
Fixes #
**Checklist:**
> Add MPIMLPolicySource CRD defaulters

- .github/workflows/build-and-push-images.yaml
The builder launch multiple VMs in a single runner. Especially, for trainer-controller-manager, we launch 3 VMs. So I think we can justify using the large runner.
Fixes #
**Checklist:**
> Use large runner for building container image

- pkg/runtime/core/core.go
- pkg/runtime/core/registry.go
I refactored `Registry` typed from 
```go
type Registry map[string]func(ctx context.Context, client client.Client, indexer client.FieldIndexer) (runtime.Runtime, error)
``` 
to 
```go
type RuntimeRegistrar struct {
factory      func(ctx context.Context, client client.Client, indexer client.FieldIndexer) (runtime.Runtime, error)
dependencies []string
}
```
so that we can represent dependencies on each runtimes and initialize dependencies first.
Fixes #2477
**Checklist:**
> Add dependencies to RuntimeRegistrar

- .github/workflows/test-e2e.yaml
- Makefile
- hack/e2e-setup-cluster.sh
I added a shell script to generate E2E dedicated manifests and store them in the `artifacts` directory.
It would be better not to modify production manifests.
Fixes #
**Checklist:**
> Store E2E manifests to artifacts directory

- api/openapi-spec/swagger.json
- manifests/base/crds/trainer.kubeflow.org_clustertrainingruntimes.yaml
- manifests/base/crds/trainer.kubeflow.org_trainingruntimes.yaml
- pkg/apis/trainer/v1alpha1/trainingruntime_types.go
- pkg/apis/trainer/v1alpha1/zz_generated.openapi.go
- sdk/kubeflow/trainer/models/trainer_v1alpha1_mpiml_policy_source.py
- test/integration/webhooks/trainingruntime_webhook_test.go
I added a MPI numProcPerNode defaulter since the MPI slots should be `1` as a default.
Fixes #
**Checklist:**
> Implement MPI numProcPerNode defaulter

- pkg/runtime/framework/plugins/torch/torch.go
This PR fixes a minor issue in the `shouldUseCPU` function definition in the `pkg/runtime/framework/plugins/torch/torch.go` file.  
This fix is based on code review feedback from PR #2492.
> fix: remove unused parameter name in default case of shouldUseCPU function

- pkg/runtime/framework/core/framework_test.go
- pkg/runtime/framework/plugins/jobset/builder.go
- pkg/runtime/framework/plugins/jobset/jobset.go
- pkg/runtime/framework/plugins/plainml/plainml.go
- pkg/runtime/framework/plugins/plainml/plainml_test.go
- pkg/runtime/framework/plugins/torch/torch.go
- pkg/runtime/framework/plugins/torch/torch_test.go
- pkg/runtime/runtime.go
- pkg/runtime/runtime_test.go
I migrated `runtime.Info.Trainer` to `runtime.Info.TemplateSpec.PodSet`, and then I removed the outdated `DeprecatedTrainer` from the JobSet builder.
Part-of https://github.com/kubeflow/trainer/issues/2495
**Checklist:**
> Migrate Info.Trainer to Info.TemplateSpec.PodSet

- pkg/constants/constants.go
- pkg/controller/trainjob_controller.go
- pkg/runtime/core/clustertrainingruntime.go
- pkg/runtime/core/trainingruntime.go
- pkg/runtime/framework/core/framework.go
- pkg/runtime/framework/core/framework_test.go
- pkg/runtime/framework/interface.go
- pkg/runtime/framework/plugins/jobset/jobset.go
- pkg/runtime/framework/plugins/mpi/mpi.go
- pkg/runtime/framework/plugins/torch/torch.go
- pkg/runtime/runtime.go
- pkg/webhooks/clustertrainingruntime_webhook.go
- pkg/webhooks/setup.go
- pkg/webhooks/trainjob_webhook.go
- test/integration/controller/trainjob_controller_test.go
- test/integration/framework/framework.go
- test/integration/webhooks/clustertrainingruntime_webhook_test.go
- test/integration/webhooks/trainingruntime_webhook_test.go
- test/integration/webhooks/trainjob_test.go
Adds validation webhook for v2 trainjob. 
Relates to https://github.com/kubeflow/training-operator/issues/2209
Fixes # https://github.com/kubeflow/training-operator/issues/2209
**Checklist:**
> KEP-2170: Adding validation webhook for v2 trainjob

- pkg/runtime/core/trainingruntime.go
- pkg/runtime/framework/core/framework_test.go
- pkg/runtime/framework/plugins/coscheduling/coscheduling.go
- pkg/runtime/framework/plugins/jobset/jobset.go
- pkg/runtime/framework/plugins/mpi/mpi.go
- pkg/runtime/framework/plugins/mpi/mpi_test.go
- pkg/runtime/framework/plugins/plainml/plainml.go
- pkg/runtime/framework/plugins/plainml/plainml_test.go
- pkg/runtime/framework/plugins/torch/torch.go
- pkg/runtime/framework/plugins/torch/torch_test.go
- pkg/runtime/runtime.go
- pkg/runtime/runtime_test.go
I removed duplicated internal data structure, `InfoOptions.podSpecReplicas` and `Info.Scheduler.TotalRequests` 
and migrate its usage to `Info.TemplateSpec.PodSet`.
Part-of https://github.com/kubeflow/trainer/issues/2495
**Checklist:**
> Migrate InfoOptions.podSpecReplias and info.Scheduler.TotalRequests to info.TemplateSpec.PodSet

- .github/workflows/build-and-push-images.yaml
We should have correct names for DockerHub images.
/assign @kubeflow/wg-training-leads @Electronic-Waste @astefanutti @mahdikhashan
> fix(test): Update images for DockerHub publish

- .github/workflows/build-and-push-images.yaml
This commit optimizes the container image build and publishes workflow by:
* Merging the previously separate GHCR and DockerHub publishing jobs into a single job
* Creating a unified publish condition to determine when images should be published
Fixes #2532
**Checklist:**
> [feature] merge GHCR and DockerHub CI jobs

- .golangci.yaml
- pkg/controller/trainjob_controller.go
- pkg/runtime/framework/plugins/mpi/mpi.go
- pkg/runtime/framework/plugins/mpi/mpi_test.go
- pkg/runtime/framework/plugins/torch/torch.go
- pkg/runtime/runtime_test.go
- pkg/util/testing/compare.go
- pkg/util/testing/wrapper.go
It's challenging to keep maintaining the dependencies group, manually. So, It would be great to add golangci-lint opt-in linter, ["GCI"](https://github.com/daixiang0/gci).
Fixes #
**Checklist:**
> chore: Enable GCI for golangci-lint

- pkg/runtime/core/clustertrainingruntime.go
- pkg/runtime/core/trainingruntime.go
- pkg/runtime/core/trainingruntime_test.go
- pkg/runtime/framework/core/framework_test.go
- pkg/runtime/framework/plugins/coscheduling/coscheduling.go
- pkg/runtime/framework/plugins/jobset/builder.go
- pkg/runtime/framework/plugins/jobset/jobset.go
- pkg/runtime/framework/plugins/jobset/jobset_test.go
- pkg/runtime/framework/plugins/mpi/mpi.go
- pkg/runtime/framework/plugins/mpi/mpi_test.go
- pkg/runtime/framework/plugins/plainml/plainml.go
- pkg/runtime/framework/plugins/plainml/plainml_test.go
- pkg/runtime/framework/plugins/torch/torch.go
- pkg/runtime/framework/plugins/torch/torch_test.go
- pkg/runtime/runtime.go
- pkg/runtime/runtime_test.go
- pkg/util/testing/wrapper.go
- test/integration/controller/trainjob_controller_test.go
- test/integration/webhooks/trainingruntime_webhook_test.go
I replaced the `runtime.Info.RuntimePolicy.MLPolicy` with `runtime.Info.RuntimePolicy.MLPolicySource` so that we can store all rJob numNodes to `runtime.Info.TemplateSpec.PodSet.Count`.
Previously, we stored the non-Trainer numNodes to `runtime.Info.TemplateSpec.PodSet.Count` and stored the Trainer numNodes to `runtime.Info.RuntimePolicy.MLPolicy.NumNodes`, which introduce internal data structure fragmentation.
Part-of: https://github.com/kubeflow/trainer/issues/2495
**Checklist:**
> Store the TrainingRuntime numNodes as runtime.Info.PodSet.Count

- sdk/kubeflow/trainer/__init__.py
We need to expose `types.Initializer` to users. It seems that we forgot to import it in:
https://github.com/kubeflow/trainer/blob/b47d385928fb7d82fb07cd1e0229861bf8856900/sdk/kubeflow/trainer/__init__.py#L26-L31
I create a small fix PR to add it to the import list so that it would not be blocked by: #2522
Fixes #
**Checklist:**
> fix(sdk): add missing import type Initializer.

- hack/e2e-setup-cluster.sh
- manifests/base/runtimes/pretraining/mpi_distributed.yaml
- manifests/base/runtimes/pretraining/torch_distributed.yaml
- pkg/constants/constants.go
- pkg/runtime/core/clustertrainingruntime_test.go
- pkg/runtime/core/trainingruntime.go
- pkg/runtime/core/trainingruntime_test.go
- pkg/runtime/framework/core/framework_test.go
- pkg/runtime/framework/plugins/jobset/builder.go
- pkg/runtime/framework/plugins/jobset/jobset.go
- pkg/runtime/framework/plugins/jobset/jobset_test.go
- pkg/runtime/framework/plugins/mpi/mpi.go
- pkg/runtime/framework/plugins/mpi/mpi_test.go
- pkg/runtime/framework/plugins/plainml/plainml.go
- pkg/runtime/framework/plugins/plainml/plainml_test.go
- pkg/runtime/framework/plugins/torch/torch.go
- pkg/runtime/framework/plugins/torch/torch_test.go
- pkg/runtime/runtime.go
- pkg/runtime/runtime_test.go
- pkg/util/testing/wrapper.go
- pkg/webhooks/trainingruntime_webhook_test.go
- test/integration/controller/trainjob_controller_test.go
- test/integration/webhooks/trainingruntime_webhook_test.go
As @andreyvelich described in https://github.com/kubeflow/trainer/pull/2523, we construct actual Trainers based on `trainer.kubeflow.org/trainjob-ancestor-step` label. Additionally, I enabled runLauncherAsNode by default for MPI runtime.
By this change, MLEs can override commands, args, images.... via TrainJob.
```yaml
apiVersion: trainer.kubeflow.org/v1alpha1
kind: TrainJob
metadata:
name: mpirun
namespace: default
spec:
runtimeRef:
name: mpi-distributed
trainer:
numNodes: 10
command:
- "mpirun"
args:
- "--tag-output"
- "/home/mpiuser/pi"
```
```shell
$ kubectl get pod
NAME                        READY   STATUS      RESTARTS   AGE
mpirun-launcher-0-0-t5k6p   0/2     Completed   0          2s
mpirun-node-0-0-5nzbd       0/1     Running     0 …
```
> Construct Trainer based on trainer.kubeflow.org/trainjob-ancestor-step label

- pkg/util/testing/wrapper.go
- pkg/webhooks/trainingruntime_webhook.go
- pkg/webhooks/trainingruntime_webhook_test.go
We would like to add webhook validations against `.spec.template.spec.replicatedJobs[*].replicas` to the TrainingRuntime and ClusterTrainingRuntime Webhook Validations. It must be 1 if replica name (`.spec.template.spec.replicatedJobs[*].name`) is Trainer, Initializer, or Launcher.
Fixes #2502 
**Checklist:**
> feat: add replicatedJobs.replicas validations in validateReplicatedJobs function.

- sdk/kubeflow/trainer/api/trainer_client.py
- sdk/kubeflow/trainer/constants/constants.py
- sdk/kubeflow/trainer/types/types.py
- sdk/kubeflow/trainer/utils/utils.py
For the MPI use-cases the Python file must be available on all Pods: Launcher + Node.
Thus, we should modify the command and args compare to `torchrun`.
After this change, the container command and args looks as follows for `mpirun`:
```yaml
args:
- |2-
read -r -d '' SCRIPT << EOM
def train_func():
print("script here")
train_func()
EOM
printf "%s" "$SCRIPT" > "/home/mpiuser/4070280887.py"
python3 "/home/mpiuser/4070280887.py"
command:
- mpirun
- --hostfile
- /etc/mpi/hostfile
- -x
- LD_LIBRARY_PATH=/usr/local/lib/
- bash
- -c
```
/assign @tenzen-y @kubeflow/wg-training-leads @Electronic-Waste @astefanutti @saileshd1402
> fix(sdk): Using correct entrypoint for mpirun

- pkg/runtime/core/clustertrainingruntime.go
- pkg/runtime/core/trainingruntime.go
- pkg/runtime/framework/core/framework.go
- pkg/runtime/framework/core/framework_test.go
- pkg/runtime/framework/interface.go
- pkg/runtime/framework/plugins/jobset/jobset.go
- pkg/runtime/framework/plugins/mpi/mpi.go
- pkg/runtime/framework/plugins/torch/torch.go
Instead of directly passing the JobSet object to `CustomValidation`, we can retrieve the JobSetSpec ApplyConfigurations from `runtime.Info`, and then could use it while validations.
https://github.com/kubeflow/trainer/blob/8aa97a4806b00752acac14fbad2cdee6e36d40c2/pkg/runtime/runtime.go#L205-L208
Fixes #
**Checklist:**
> Retrieve JobSetSpec from runtime.Info in CustomValidations

- .github/workflows/build-and-publish-images.yaml
- Makefile
- examples/jax/cpu-demo/demo.yaml
- examples/jax/jax-dist-spmd-mnist/jaxjob_dist_spmd_mnist_gloo.yaml
- examples/pytorch/deepspeed-demo/pytorch_deepspeed_demo.yaml
- examples/pytorch/elastic/echo/echo.yaml
- examples/pytorch/elastic/imagenet/imagenet.yaml
- examples/pytorch/image-classification/create-pytorchjob.ipynb
- examples/pytorch/mnist/v1/pytorch_job_mnist_gloo.yaml
- examples/pytorch/mnist/v1/pytorch_job_mnist_mpi.yaml
- examples/pytorch/mnist/v1/pytorch_job_mnist_nccl.yaml
- examples/pytorch/smoke-dist/pytorch_job_sendrecv.yaml
- examples/tensorflow/dist-mnist/tf_job_mnist.yaml
- examples/tensorflow/distribution_strategy/multi_worker_tfjob.yaml
- examples/tensorflow/mnist_with_summaries/tf_job_mnist.yaml
- examples/tensorflow/simple.yaml
- examples/xgboost/lightgbm-dist/xgboostjob_v1_lightgbm_dist_training.yaml
- examples/xgboost/smoke-dist/xgboostjob_v1_rabit_test.yaml
- examples/xgboost/smoke-dist/xgboostjob_v1alpha1_rabit_test.yaml
- examples/xgboost/xgboost-dist/xgboostjob_v1_iris_predict.yaml
- examples/xgboost/xgboost-dist/xgboostjob_v1_iris_predict_local.yaml
- examples/xgboost/xgboost-dist/xgboostjob_v1_iris_train.yaml
- examples/xgboost/xgboost-dist/xgboostjob_v1_iris_train_local.yaml
- examples/xgboost/xgboostjob.yaml
- manifests/overlays/kubeflow/kustomization.yaml
- manifests/overlays/standalone/kustomization.yaml
- pkg/config/config.go
- scripts/setup-training-operator.sh
- sdk/python/kubeflow/training/constants/constants.py
Update Manifest images to GHCR instead of Dockerhub. Required to decrease rate limiting issues
Address this comment to update manifest images: https://github.com/kubeflow/trainer/pull/2491#discussion_r1989054861
cc: @andreyvelich @Electronic-Waste @mahdikhashan @tenzen-y 
**Checklist:**
> Update Manifest Images to GHCR

- manifests/overlays/kubeflow/kustomization.yaml
- manifests/overlays/standalone/kustomization.yaml
Part of: https://github.com/kubeflow/training-operator/issues/2169
I updated image tag for v1.9.1 release.
/assign @kubeflow/wg-training-leads @Electronic-Waste @saileshd1402 @astefanutti
> Release Training Operator Image for v1.9.1

- pkg/runtime/core/trainingruntime_test.go
- pkg/runtime/framework/plugins/plainml/plainml_test.go
- pkg/runtime/framework/plugins/torch/torch.go
- pkg/runtime/framework/plugins/torch/torch_test.go
- pkg/util/testing/wrapper.go
- test/integration/controller/trainjob_controller_test.go
Add specific UT for torch runtime `Valid` function.
Fixes #2556
**Checklist:**
PTAL, @tenzen-y
> test(runtime): add UT for torch runtime valid function.

- CONTRIBUTING.md
- Makefile
Updates the CONTRIBUTING.md documentation to reflect Kubeflow Trainer V2. This PR updates the contributing [guide](https://github.com/kubeflow/trainer/blob/master/CONTRIBUTING.md) with accurate and updated installation instructions, contributor workflows. These changes ensure new contributors have proper guidance when developing with Kubeflow Trainer V2. 
NOTE : The update is still incomplete in the commented out parts.
Key changes include:
- Update title and remove TODO note
- Add a more detailed and digestable contributor workflow section
- Update installation paths and commands for the new architecture
- Replace old namespace references (kubeflow → kubeflow-system)
- Update Kubernetes deployment instructions for controller manager and runtimes
- …
> docs: update CONTRIBUTING.md for Kubeflow Trainer V2

- README.md
We've updated our Slack channel name.
/assign @kubeflow/wg-training-leads @Electronic-Waste @astefanutti @terrytangyuan
> chore(docs): Update Slack channel

- pkg/runtime/framework/plugins/mpi/mpi.go
- pkg/runtime/framework/plugins/mpi/mpi_test.go
Part of https://github.com/kubeflow/trainer/issues/2556
Fixes #
**Checklist:**
> Implement CustomValidation UT for MPI plugin

- pkg/runtime/framework/plugins/mpi/mpi_test.go
The `Validate()` function is no more acceptable for JobSetTemplate as a dedicated argument. However, when we merge https://github.com/kubeflow/trainer/pull/2555, unfortunately added the no available arguments to our MPI UTs
> ```
> # github.com/kubeflow/trainer/pkg/runtime/framework/plugins/mpi [github.com/kubeflow/trainer/pkg/runtime/framework/plugins/mpi.test]
> Error: pkg/runtime/framework/plugins/mpi/mpi_test.go:821:93: too many arguments in call to p.(framework.CustomValidationPlugin).Validate
> 	have (nil, *"github.com/kubeflow/trainer/pkg/runtime".Info, *"github.com/kubeflow/trainer/pkg/apis/trainer/v1alpha1".TrainJob, *"github.com/kubeflow/trainer/pkg/apis/trainer/v1alpha1".TrainJob)
> 	want (*"github.com/kubeflow/trainer/pkg/runtime".Info, …
```
> Fix MPI Test runnable errors

- charts/kubeflow-trainer/values.yaml
Remove kubeflow-trainer prefix from jobset resource names.
Fixes #2595
**Checklist:**
> Remove kubeflow-trainer prefix from jobset resource names

- .github/workflows/test-go.yaml
> fix: remove redundant K8s version matrix from integration tests

- .github/workflows/github-stale.yaml
Update the message shown when a PR is closed due to inactivity via Stale GitHub action
**Checklist:**
> Fix close-pr message in Stale GitHub Action

- .github/workflows/build-and-push-images.yaml
~Splits GHA Workflows for Build and Publish.~
~This refactors actions by splitting the image handling into two separate workflows:~
~1. **Build Images** - Runs on PRs to validate Docker builds without publishing~
~2. **Publish Images** - Runs on master/release branches and version tags to build and publish images~
* Adds a condition at the job to make it run only on `kubeflow/trainer` repo 
* Earlier this action was failing in forked repo due to unavailability of `ubuntu-latest-16-cores` runners which results in failure
* Publishing logic only when event is `push` 
Fixes #2601
**Checklist:**
> ci: refactor build-push-images workflow

- manifests/base/rbac/role.yaml
- pkg/controller/trainjob_controller.go
TrainJob controller doesn't require `create and delete` RBAC.
Ref: https://github.com/kubeflow/trainer/pull/2608#discussion_r2068580203
/assign @tenzen-y @astefanutti
> fix(controller): Fix RBAC permissions for TrainJob controller

- manifests/base/rbac/role.yaml
- pkg/controller/clustertrainingruntime_controller.go
- pkg/controller/clustertrainingruntime_controller_test.go
- pkg/controller/setup.go
- pkg/util/testing/wrapper.go
- pkg/util/trainjob/trainjob.go
- pkg/util/trainjob/trainjob_test.go
- test/integration/controller/clustertrainingruntime_controller_test.go
I implemented the ClusterTrainingRuntime controller with the finalizer trainer.kubeflow.org/resource-in-use mechanism.
The event dispatching conditions are completely the same as TrainingRuntime. So, please see https://github.com/kubeflow/trainer/pull/2608 description for more details.
This PR depends on and is blocked by https://github.com/kubeflow/trainer/pull/2608.
Fixes https://github.com/kubeflow/trainer/issues/2609
**Checklist:**
> Implement trainer.kubeflow.org/resource-in-use finalizer mechanism to ClusterTrainingRuntime

- docs/proposals/2170-kubeflow-trainer-v2/README.md
- pkg/apis/trainer/v1alpha1/trainjob_types.go
- pkg/constants/constants.go
- pkg/controller/trainjob_controller.go
- sdk/kubeflow/trainer/api/trainer_client.py
- sdk/kubeflow/trainer/constants/constants.py
- test/e2e/e2e_test.go
- test/integration/controller/trainjob_controller_test.go
This removes the `TrainJobCreated` condition.
The `TrainJobCreated` condition will be revisited with #2459.
To avoid any backward incompatible changes once there is an agreement on the new condition(s), we've decided to remove it for now as discussed in https://github.com/kubeflow/trainer/issues/2459#issuecomment-2822457310.
**Checklist:**
> Remove TrainJobCreated condition

- CHANGELOG.md
I've added changelog for Training Operator v1.9.2.
/assign @kubeflow/wg-training-leads @Electronic-Waste @mahdikhashan @astefanutti @helenxie-bit @abhijeet-dhumal
> chore(docs): Add Training Operator v1.9.2 Changelog

- .github/workflows/github-stale.yaml
the current version of gh stale action is 9, ours is 5 (backs to 2022). ref: https://github.com/actions/stale 
Fixes #
**Checklist:**
> [chore] update stale action version to latest

- sdk/kubeflow/trainer/api/trainer_client.py
Previously, the type annotation `Optional[types.CustomTrainer]` was specified for the `trainer` parameter. This change adds `types.BuiltinTrainer` to the union type, as this is a valid type for this parameter.
**Checklist:**
> fix(sdk): Fix type annotation for `train` method's `trainer` parameter

- sdk/kubeflow/trainer/utils/utils.py
The datatype for the arg provided to this function should be of type `TorchTuneConfig`, but prior to this change an arg of type `BuiltinTrainer` was provided.
**Checklist:**
> fix(sdk): Fix bad arg passed to `get_args_using_torchtune_config`

- OWNERS
I would like to nominate @Electronic-Waste as an approver and @astefanutti as a reviewer for Kubeflow Trainer project.
I believe that both of them perfectly fits [the requirements](https://www.kubeflow.org/docs/about/membership/):
- @Electronic-Waste being a reviewer for at least 3 months, @astefanutti being a member for at least 3 months.
- @Electronic-Waste made 1495 contributions and @astefanutti made 426 contributions in [the last year](https://kubeflow.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1&var%5B%E2%80%A6%5Dubeflow%2Ftrainer&var-country_name=All&var-companies=All&var-period_name=Last%20year&var-metric=contributions&var-repogroup_name=All).
- Helping with GSoC, Kubeflow Trainer V2, and Kubeflow SDK.
- Driving the design and implementation of Kubeflow LLM …
> Nominate @Electronic-Waste as approver and @astefanutti as reviewer

- CHANGELOG.md
Given that we will release Kubeflow Trainer 2.0 soon, we will update the changelog with the changes.
I think, it is better to preserve the history of previous releases in the changelog before we start working on Kubeflow Trainer 2.0 (e.g. Training Operator 1.9.0).
So users don't get confused why the previous release before `v2.0.0` was `1.9.0-rc.0`. 
For the minor and patch releases after 1.9.0, we should guide users to check `release-1.9` branch.
Does it look good @kubeflow/wg-training-leads @Electronic-Waste @astefanutti ?
> chore(docs): Cherry-pick changelog for Training Operator v1.9.0 

- pkg/runtime/framework/plugins/torch/torch_test.go
The `FromInt` has already been deprecated.
Fixes #
**Checklist:**
> chore: Replace the deprecated intstr.FromInt with intstr.FromInt32

- Makefile
- charts/kubeflow-trainer/crds/trainer.kubeflow.org_trainjobs.yaml
Automatically copy generated CRDs into Helm charts to keep them in sync.
It follows the discussion in https://github.com/kubeflow/trainer/pull/2700#discussion_r2180633744.
**Checklist:**
> chore: Copy generated CRDs into Helm charts

- api/openapi-spec/swagger.json
- api/python_api/kubeflow_trainer_api/models/trainer_v1alpha1_pod_spec_override.py
- charts/kubeflow-trainer/crds/trainer.kubeflow.org_trainjobs.yaml
- manifests/base/crds/trainer.kubeflow.org_trainjobs.yaml
- pkg/apis/trainer/v1alpha1/trainjob_types.go
- pkg/apis/trainer/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/trainer/v1alpha1/zz_generated.openapi.go
- pkg/client/applyconfiguration/trainer/v1alpha1/podspecoverride.go
- pkg/runtime/core/trainingruntime_test.go
- pkg/util/testing/wrapper.go
Add scheduling gates to PodSpecOverrides.
Fixes #2680
**Checklist:**
> feat: Add schedulingGates to PodSpecOverrides

- .github/workflows/build-and-push-images.yaml
- .github/workflows/test-e2e.yaml
CNCF has hosted ephemeral GitHub runners on Oracle that we want projects to use instead of the GitHub-hosted ones, which now incur a cost to use.
Please direct any questions to me, @jeefy, @krook, and @RobertKielty. You can also join `#cncf-ci-infra` channel on CNCF Slack.
> chore: update github runners to oci gh arc runners

- CHANGELOG.md
Fixes: https://github.com/kubeflow/trainer/issues/2170
This is Changelog for Kubeflow Trainer v2.0.0 🎉 
I am super happy to finally release this project after almost one year of work, and exciting for our future ROADMAP!
Huge congratulations to all contributors 🎉 
/hold for https://github.com/kubeflow/website/pull/4142, https://github.com/kubeflow/blog/pull/169
/assign @kubeflow/wg-training-leads @Electronic-Waste @kramaranya @ChenYi015 @IRONICBo @akshaychitneni @Harshal292004 @solanyn @astefanutti @eoinfennessy @rudeigerc @tr33k @mahdikhashan @Diasker @szaher @koksay @Doris-xm @kannon92 @franciscojavierarceo @mszadkow @mimowo @varodrig @vsoch @ahg-g @shravan-achar @bigsur0
> chore(docs): Add Changelog for Kubeflow Trainer v2.0.0

- examples/deepspeed/text-summarization/T5-Fine-Tuning.ipynb
- examples/mlx/image-classification/MLX-Distributed-Mnist.ipynb
- examples/pytorch/image-classification/mnist.ipynb
- examples/pytorch/question-answering/fine-tune-distilbert.ipynb
- examples/torchtune/llama3_2/alpaca-trainjob-yaml.ipynb
We should update examples according to our recent changes to the SDK: https://github.com/kubeflow/sdk/pull/56
That should fix the failed examples.
/assign @kubeflow/kubeflow-trainer-team @astefanutti @kramaranya
> fix(examples): Update the argument for Runtime framework

- .gitignore
- api/python_api/pyproject.toml
While trying to publish `kubeflow_trainer_api` to PyPI, I get this error:
```
OSError: License file does not exist: ../../LICENSE
```
All files must be local to the Python project that we want to publish.
We should also update the Kubeflow SDK: https://github.com/kubeflow/sdk/blob/main/python/pyproject.toml
/assign @kubeflow/kubeflow-trainer-team @astefanutti @kramaranya @szaher @briangallagher @eoinfennessy
> fix(api): Fix license path for Kubeflow Trainer Python API

- README.md
I've added latest news to the Kubeflow Trainer readme, it would be nice to share updates with our users.
If you want to add more items, please let me know!
Also, I updated the README badges to remove Go status and to add Slack + DeepWiki
/assign @kubeflow/kubeflow-trainer-team @kramaranya @kubeflow/wg-training-leads @astefanutti @franciscojavierarceo @szaher
> feat(docs): Introduce latest news to the README

- .github/workflows/gh-workflow-approve.yaml
Makes workflows run on `/ok-to-test` by org member.
Copied this action from `kubeflow/dashboard`: https://github.com/kubeflow/dashboard/blob/bf28ef115c7cedaabfc5727582034b45422799dc/.github/workflows/gh-workflow-approve.yaml
Fixes #
**Checklist:**
> feat: run workflows on `/ok-to-test` label

- .github/workflows/test-e2e.yaml
- CONTRIBUTING.md
- examples/deepspeed/text-summarization/T5-Fine-Tuning.ipynb
- examples/mlx/image-classification/MLX-Distributed-Mnist.ipynb
- examples/pytorch/image-classification/mnist.ipynb
- examples/pytorch/question-answering/fine-tune-distilbert.ipynb
- examples/torchtune/llama3_2/alpaca-trainjob-yaml.ipynb
Since we've moved `pyproject.toml` to root in https://github.com/kubeflow/sdk/pull/61, I updated its references in Trainer repo
/assign @andreyvelich
> fix: update kubeflow sdk reference

- docs/release/README.md
I updated the release guide to explain how to publish KF Trainer Python API modules.
/assign @kramaranya @kubeflow/kubeflow-trainer-team @astefanutti
> feat(docs): How to release Python API modules

- charts/kubeflow-trainer/templates/rbac/clusterrole.yaml
- manifests/base/rbac/role.yaml
- pkg/runtime/framework/plugins/coscheduling/coscheduling.go
Even though podgroup plugin needs to operate LimitRange and RuntimeClass, the trainer does not have proper permissions.
Fixes #
**Checklist:**
> fix(manifests): Add missing permissions for the RuntimeClass and LimitRange

- .github/workflows/test-go.yaml
The workflow will only execute when running in the `kubeflow/trainer` repository and will be skipped in forks or other repositories.
Fixes #2601
**Checklist:**
/cc @andreyvelich
> fix(ci): disable `Unit and Integration Test - Go` gh action in forked repos

- api/python_api/pyproject.toml
Since we have a single package, I removed the redundant hatch build target from pyproject.toml, because hatchling finds the package on its own -- https://hatch.pypa.io/1.9/plugins/builder/wheel/#default-file-selection
/assign @andreyvelich @astefanutti
> chore: Remove tool.hatch.build.targets.wheel from pyproject

- api/openapi-spec/swagger.json
- api/python_api/kubeflow_trainer_api/models/trainer_v1alpha1_pod_spec_override.py
- charts/kubeflow-trainer/crds/trainer.kubeflow.org_trainjobs.yaml
- docs/proposals/2170-kubeflow-trainer-v2/README.md
- manifests/base/crds/trainer.kubeflow.org_trainjobs.yaml
- pkg/apis/trainer/v1alpha1/trainjob_types.go
- pkg/apis/trainer/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/trainer/v1alpha1/zz_generated.openapi.go
- pkg/client/applyconfiguration/trainer/v1alpha1/podspecoverride.go
- pkg/runtime/core/trainingruntime_test.go
- pkg/util/testing/wrapper.go
We’d like the ability to override Affinity through TrainJob’s podSpecOverrides, which was introduced in the [KEP-2170: Kubeflow Trainer V2 API](https://github.com/kubeflow/trainer/tree/master/docs/proposals/2170-kubeflow-trainer-v2).
**Which issue(s) this PR fixes**:
Fixes #2795
**Checklist:**
> feat: support affinity in TrainJob pod spec overrides

- test/integration/controller/clustertrainingruntime_controller_test.go
- test/integration/controller/trainingruntime_controller_test.go
Fix flaky test observed at https://github.com/kubeflow/trainer/actions/runs/17310878465/job/49144635225. It appears that the TrainJob is being created before the TrainingRuntime is actually ready. This change ensures that a TrainJob is only created after confirming the TrainingRuntime has been created. A similar test case exists for ClusterTrainingRuntime, which has also been updated accordingly.
```console
TrainingRuntime controller when Reconcile TrainingRuntime TrainingRuntime can be deleted once referenced TrainJob is deleted
/home/runner/work/trainer/trainer/go/src/github.com/kubeflow/trainer/test/integration/controller/trainingruntime_controller_test.go:99
2025-08-29T00:08:50Z	LEVEL(-5)	Reconciling	{"controller": "trainingruntime_controller", …
```
> chore: deflake test to ensure runtime is created before creating trainjob

- OWNERS
I would like to nominate @astefanutti as Kubeflow Trainer approver.
Antonin has helped a lot with the development of this project, and he perfectly fits all of the requirements: https://www.kubeflow.org/docs/about/membership/#approver
- Contributor to more than 100 PRs: https://github.com/kubeflow/trainer/pulls?page=1&q=is%3Apr+commenter%3Aastefanutti
- DevStats: https://kubeflow.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1&var-period_name=Last%202%20years&var-metric=contributions&var-repogroup_name=All&var-country_name=All&var-companies=All
Thanks a lot for all of your contributions @astefanutti 🎉 
/hold for WG leads to review
/assign @tenzen-y @Electronic-Waste @johnugeorge @terrytangyuan @kubeflow/wg-training-leads
> chore: Nominate @astefanutti as Kubeflow Trainer approver

- api/openapi-spec/swagger.json
- api/python_api/kubeflow_trainer_api/models/trainer_v1alpha1_pod_spec_override.py
- charts/kubeflow-trainer/crds/trainer.kubeflow.org_trainjobs.yaml
- docs/proposals/2170-kubeflow-trainer-v2/README.md
- manifests/base/crds/trainer.kubeflow.org_trainjobs.yaml
- pkg/apis/trainer/v1alpha1/trainjob_types.go
- pkg/apis/trainer/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/trainer/v1alpha1/zz_generated.openapi.go
- pkg/client/applyconfiguration/trainer/v1alpha1/podspecoverride.go
- pkg/runtime/core/trainingruntime_test.go
- pkg/util/testing/wrapper.go
We’d like the ability to override imagePullSecrets through TrainJob’s podSpecOverrides, which was introduced in the [KEP-2170: Kubeflow Trainer V2 API](https://github.com/kubeflow/trainer/tree/master/docs/proposals/2170-kubeflow-trainer-v2). Our platform is multi-tenant, and each user or organization maintains its own private registry. This means users can specify both the image and the credentials for image pull when running a job. It would be helpful if we could override imagePullSecrets in TrainJob; otherwise, we’d need to create a separate ServiceAccount for each job and attach the imagePullSecrets to it.
**Which issue(s) this PR fixes**:
Fixes #2797
**Checklist:**
> feat: support imagePullSecrets in TrainJob pod spec overrides

- .github/workflows/test-e2e-gpu.yaml
- Use `HF_TOKEN` from upstream repo.
- We want the action to run on incoming PRs when maintainers add the ok-to-test-gpu-runner label. Since in https://github.com/kubeflow/trainer/pull/2762 we cant have that.
**Which issue(s) this PR fixes** :
Fixes #2814
**Checklist:**
> feat: add HF token and allow gpu workflow to run from pull request target

- manifests/base/runtimes/torchtune/llama3_2/llama3_2_1B.yaml
- manifests/base/runtimes/torchtune/llama3_2/llama3_2_3B.yaml
In https://github.com/kubeflow/trainer/pull/2590, the training task needs to wait for both model initializer and dataset initializer. However, former jobset (`<v0.9.0`) does not support specifying multiple items, which is blocking our implementation.
Currently, jobset has been upgraded to `v0.9.0` and includes Multiple DependsOn feature: https://github.com/kubernetes-sigs/jobset/pull/878. This PR adds the support for this new feature.
/cc @kubeflow/kubeflow-trainer-team @kannon92 @rudeigerc @kramaranya @szaher 
Fixes #2592
**Checklist:**
> chore(runtimes): update torchtune CTRs with multiple dependson feature in jobset v0.9.0
